import type { Recipe, Taste } from './types'
import { importedCookbookRecipes } from './importedCookbookRecipes'
import { recipesBatchA } from './recipesBatchA'
import { recipesBatchB } from './recipesBatchB'
import { recipesBatchC } from './recipesBatchC'
import { recipesBatchD } from './recipesBatchD'
import { hydrateRecipeCollection } from './hydrateRecipeMedia'

export const tasteOptions: Array<{ value: Taste; icon: string; note: string }> = [
  { value: '咸鲜', icon: '🥢', note: '家常耐吃' },
  { value: '微辣', icon: '🌶', note: '轻轻提味' },
  { value: '香辣', icon: '🔥', note: '够香够辣' },
  { value: '酸爽', icon: '🍋', note: '开胃解腻' },
  { value: '酸甜', icon: '🍅', note: '柔和酸甜' },
  { value: '清淡', icon: '🌿', note: '少油舒服' },
  { value: '浓郁', icon: '🍲', note: '酱香下饭' },
]

export const ingredientGroups = [
  { name: '常用', items: ['鸡蛋', '番茄', '土豆', '青椒', '米饭', '小葱'] },
  { name: '肉蛋', items: ['猪里脊', '猪肉末', '鸡翅', '虾仁', '鸡胸肉'] },
  { name: '蔬菜', items: ['胡萝卜', '西兰花', '茄子', '大蒜', '姜', '小白菜', '苦瓜', '丝瓜', '冬瓜', '南瓜', '黄瓜', '节瓜', '佛手瓜'] },
  { name: '豆菌', items: ['豆腐', '香菇', '金针菇'] },
  { name: '主食', items: ['面条', '面粉', '米饭'] },
  { name: '特别调味', items: ['可乐', '豆瓣酱', '花椒', '花生米'] },
]

export const basicSeasonings = ['食用油', '盐', '生抽', '糖', '醋', '胡椒粉', '淀粉']

const recipes: Recipe[] = [
  {
    id: 'qingjiao-rousi',
    title: '青椒肉丝',
    subtitle: '脆嫩不柴的家常下饭菜',
    emoji: '🫑',
    colors: ['#c5d986', '#628c4c'],
    minutes: 18,
    difficulty: 1,
    rating: 4.9,
    calories: 328,
    servings: 2,
    vegetarian: false,
    tastes: ['咸鲜', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '青椒', amount: 2, unit: '个', role: 'core' },
      { name: '猪里脊', amount: 180, unit: '克', role: 'core', substitutes: ['鸡胸肉'] },
      { name: '姜', amount: 2, unit: '片', role: 'support', substitutes: ['姜粉'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 1, unit: '小撮', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切肉上浆', text: '里脊顺纹切成细丝，加 1 汤匙生抽、淀粉和 1 茶匙水，抓到表面发黏。', heat: '不开火', timerSeconds: 300, tip: '顺纹切，肉丝下锅更不容易断。' },
      { title: '处理青椒', text: '青椒去籽切细丝，姜切成末。让食材粗细接近，熟得更均匀。', heat: '不开火' },
      { title: '滑炒肉丝', text: '锅烧热后放油，下肉丝快速划散；刚变色就先盛出。', heat: '中火', timerSeconds: 90, tip: '肉丝不要炒到全熟，回锅时还会继续受热。' },
      { title: '炒香青椒', text: '原锅下姜末和青椒，大火翻炒至青椒颜色变亮、边缘微微起皱。', heat: '大火', timerSeconds: 120 },
      { title: '合炒出锅', text: '倒回肉丝，加剩余生抽和盐，快速翻匀后立刻关火装盘。', heat: '大火', timerSeconds: 45 },
    ],
    tips: ['肉丝上浆时加一小勺水，比单纯加油更嫩。', '青椒想更脆就全程大火，想更软可多炒 1 分钟。'],
  },
  {
    id: 'qingjiao-egg',
    title: '青椒炒蛋',
    subtitle: '十分钟出锅，香嫩又省事',
    emoji: '🍳',
    colors: ['#f7d969', '#73a657'],
    minutes: 10,
    difficulty: 1,
    rating: 4.8,
    calories: 286,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '青椒', amount: 2, unit: '个', role: 'core' },
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '准备蛋液', text: '鸡蛋打散，加一小撮盐和一茶匙清水，搅到蛋白蛋黄完全融合。', heat: '不开火', tip: '少量清水能让炒蛋更松软。' },
      { title: '煸香青椒', text: '青椒切丝。热锅少油，下青椒大火炒到表面微微起皱，先盛出。', heat: '大火', timerSeconds: 90 },
      { title: '滑熟鸡蛋', text: '补少量油，倒入蛋液；边缘凝固后用锅铲向中间推，保留大块。', heat: '中火', timerSeconds: 60 },
      { title: '合炒调味', text: '鸡蛋还有一点湿润时倒回青椒，加盐和葱花，翻两下就关火。', heat: '中火', timerSeconds: 30 },
    ],
    tips: ['蛋液不要炒干，利用余温正好熟透。', '青椒先炒能去生味，也不会让鸡蛋吸太多油。'],
  },
  {
    id: 'sour-potato',
    title: '酸辣土豆丝',
    subtitle: '爽脆开胃，厨房新手也稳',
    emoji: '🥔',
    colors: ['#e9c673', '#dc7352'],
    minutes: 15,
    difficulty: 1,
    rating: 4.8,
    calories: 218,
    servings: 2,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '土豆', amount: 2, unit: '个', role: 'core' },
      { name: '青椒', amount: 1, unit: '个', role: 'core' },
      { name: '大蒜', amount: 2, unit: '瓣', role: 'support' },
      { name: '醋', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切丝去淀粉', text: '土豆切细丝，用清水淘洗两遍后沥干；青椒切丝，蒜切末。', heat: '不开火', tip: '洗掉表面淀粉，是土豆丝爽脆的关键。' },
      { title: '爆香蒜末', text: '锅烧热放油，下蒜末炒出香味，注意不要焦。', heat: '中火', timerSeconds: 20 },
      { title: '大火快炒', text: '倒入土豆丝和青椒，转大火持续翻炒到土豆丝微微透明。', heat: '大火', timerSeconds: 150 },
      { title: '锅边淋醋', text: '沿锅边淋入醋，加盐，快速翻炒均匀后出锅。', heat: '大火', timerSeconds: 30, tip: '醋沿热锅边淋入，香味更圆润。' },
    ],
    tips: ['土豆丝切好后不要久泡，洗净淀粉即可。', '全程大火，出水后口感会变软。'],
  },
  {
    id: 'tomato-egg',
    title: '番茄炒蛋',
    subtitle: '有汤汁，拌饭特别香',
    emoji: '🍅',
    colors: ['#f59d69', '#d84a3c'],
    minutes: 12,
    difficulty: 1,
    rating: 4.9,
    calories: 312,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '酸甜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '番茄', amount: 2, unit: '个', role: 'core' },
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '备好食材', text: '番茄切小块，鸡蛋加一小撮盐打散，小葱切花。', heat: '不开火' },
      { title: '炒嫩鸡蛋', text: '热锅放油，倒入蛋液；刚凝成大块、表面仍润时盛出。', heat: '中火', timerSeconds: 60 },
      { title: '炒出番茄汁', text: '原锅下番茄和一半盐，中火炒软，用锅铲轻压出汁。', heat: '中火', timerSeconds: 180, tip: '先放一点盐，番茄更容易出汁。' },
      { title: '合炒完成', text: '加入糖和鸡蛋，翻匀让蛋块裹上汤汁，撒葱花关火。', heat: '中火', timerSeconds: 45 },
    ],
    tips: ['番茄够熟就少放糖，糖只用来平衡酸味。', '喜欢多汁可以加两汤匙热水再焖 30 秒。'],
  },
  {
    id: 'egg-fried-rice',
    title: '黄金蛋炒饭',
    subtitle: '粒粒分明，剩饭的最佳归宿',
    emoji: '🍚',
    colors: ['#f0d36f', '#d99444'],
    minutes: 10,
    difficulty: 1,
    rating: 4.7,
    calories: 468,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '米饭', amount: 2, unit: '碗', role: 'core' },
      { name: '鸡蛋', amount: 2, unit: '个', role: 'core' },
      { name: '小葱', amount: 2, unit: '根', role: 'support', substitutes: ['洋葱'] },
      { name: '胡萝卜', amount: 0.5, unit: '根', role: 'support', substitutes: ['青椒'] },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '打散米饭', text: '冷米饭提前用手或饭勺拨散，胡萝卜切小丁，葱白葱绿分开。', heat: '不开火' },
      { title: '炒香配料', text: '热锅放油，下葱白和胡萝卜丁炒出香味。', heat: '中火', timerSeconds: 60 },
      { title: '蛋饭同炒', text: '倒入蛋液，立刻加入米饭，大火快速翻炒并压散结块。', heat: '大火', timerSeconds: 150 },
      { title: '调味出锅', text: '米饭变得干爽弹跳时，加盐、生抽和葱绿，翻匀出锅。', heat: '大火', timerSeconds: 30 },
    ],
    tips: ['冷藏过的米饭水分低，更容易炒散。', '生抽不要多，避免米饭发黑发湿。'],
  },
  {
    id: 'potato-pancake',
    title: '土豆鸡蛋饼',
    subtitle: '外酥里软，一锅就是一餐',
    emoji: '🥞',
    colors: ['#e4bd6c', '#bd7d3e'],
    minutes: 20,
    difficulty: 1,
    rating: 4.6,
    calories: 398,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜'],
    cookware: '平底锅 · 1 口锅',
    ingredients: [
      { name: '土豆', amount: 1, unit: '个', role: 'core' },
      { name: '鸡蛋', amount: 2, unit: '个', role: 'core' },
      { name: '面粉', amount: 3, unit: '汤匙', role: 'core' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '胡椒粉', amount: 1, unit: '小撮', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '调好面糊', text: '土豆擦细丝，加入鸡蛋、面粉、葱花、盐和胡椒，拌成能缓慢流动的糊。', heat: '不开火' },
      { title: '摊成薄饼', text: '平底锅刷油，倒入面糊摊成约 1 厘米厚，盖盖煎到底面定型。', heat: '小火', timerSeconds: 240 },
      { title: '翻面煎熟', text: '借助盘子翻面，再煎至两面金黄、中心熟透。', heat: '小火', timerSeconds: 180 },
      { title: '切块装盘', text: '关火静置 1 分钟，切成小块即可。', heat: '不开火', timerSeconds: 60 },
    ],
    tips: ['面糊太干可加一汤匙水，太稀则补少量面粉。', '保持小火，避免外面焦了里面还没熟。'],
  },
  {
    id: 'potato-rice',
    title: '土豆肉丁焖饭',
    subtitle: '饭菜一锅出，酱香入味',
    emoji: '🍲',
    colors: ['#b88959', '#70462f'],
    minutes: 40,
    difficulty: 2,
    rating: 4.8,
    calories: 582,
    servings: 2,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '电饭锅 · 少洗锅',
    ingredients: [
      { name: '米饭', amount: 2, unit: '杯生米', role: 'core' },
      { name: '土豆', amount: 1, unit: '个', role: 'core' },
      { name: '猪里脊', amount: 150, unit: '克', role: 'core', substitutes: ['鸡胸肉'] },
      { name: '胡萝卜', amount: 0.5, unit: '根', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切成小丁', text: '土豆、胡萝卜和猪里脊都切成 1.5 厘米小丁。大米淘洗后沥水。', heat: '不开火' },
      { title: '快速煸炒', text: '炒锅少油，下肉丁炒变色，再加入土豆、胡萝卜、生抽和糖翻匀。', heat: '中火', timerSeconds: 180 },
      { title: '开始焖饭', text: '大米放进电饭锅，加比平时略少的水，铺上炒好的肉菜，启动煮饭。', heat: '不开火', timerSeconds: 1500, tip: '蔬菜会出水，所以水量比普通煮饭少约一成。' },
      { title: '翻拌焖香', text: '煮好后从底部翻拌均匀，盖盖再焖 5 分钟。', heat: '不开火', timerSeconds: 300 },
    ],
    tips: ['没有猪里脊可以换鸡腿肉。', '土豆不要切太小，避免焖成泥。'],
  },
  {
    id: 'mushroom-tofu-soup',
    title: '菌菇豆腐汤',
    subtitle: '鲜而不腻，十几分钟暖胃',
    emoji: '🍄',
    colors: ['#d8c8a7', '#839b75'],
    minutes: 16,
    difficulty: 1,
    rating: 4.7,
    calories: 186,
    servings: 2,
    vegetarian: true,
    tastes: ['清淡', '咸鲜'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '豆腐', amount: 1, unit: '盒', role: 'core' },
      { name: '香菇', amount: 4, unit: '朵', role: 'core', substitutes: ['金针菇'] },
      { name: '小白菜', amount: 2, unit: '棵', role: 'support' },
      { name: '姜', amount: 2, unit: '片', role: 'support' },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '胡椒粉', amount: 1, unit: '小撮', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理食材', text: '豆腐切块，香菇切片，小白菜切段，姜切细丝。', heat: '不开火' },
      { title: '煸出菌香', text: '锅中少油，下姜丝和香菇煸到香菇变软、边缘微黄。', heat: '中火', timerSeconds: 120 },
      { title: '煮豆腐', text: '加入 600 毫升热水和豆腐，水开后转小火煮 5 分钟。', heat: '小火', timerSeconds: 300 },
      { title: '加入青菜', text: '放小白菜煮软，加盐和胡椒调味，关火。', heat: '中火', timerSeconds: 60 },
    ],
    tips: ['先煸香菇再加水，素汤也会有足够鲜味。', '豆腐下锅后少翻动，避免碎。'],
  },
  {
    id: 'garlic-broccoli',
    title: '蒜蓉西兰花',
    subtitle: '脆绿清爽，配什么都合适',
    emoji: '🥦',
    colors: ['#8cbb68', '#3d7650'],
    minutes: 12,
    difficulty: 1,
    rating: 4.6,
    calories: 152,
    servings: 2,
    vegetarian: true,
    tastes: ['清淡', '咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '西兰花', amount: 1, unit: '棵', role: 'core' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'core' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切洗西兰花', text: '西兰花沿小梗分成均匀小朵，清水洗净；大蒜切成末。', heat: '不开火' },
      { title: '快速焯水', text: '水开加一小撮盐和几滴油，下西兰花焯到颜色翠绿，捞出沥干。', heat: '大火', timerSeconds: 60 },
      { title: '炒香蒜末', text: '热锅放油，小火把一半蒜末炒到微黄。', heat: '小火', timerSeconds: 30 },
      { title: '翻炒出锅', text: '倒入西兰花、生抽、盐和剩余蒜末，大火翻匀出锅。', heat: '大火', timerSeconds: 45 },
    ],
    tips: ['焯水控制在 1 分钟内，口感更脆。', '蒜末分两次放，既有焦香也有清新的蒜香。'],
  },
  {
    id: 'cola-wings',
    title: '可乐鸡翅',
    subtitle: '零失败的甜咸酱汁',
    emoji: '🍗',
    colors: ['#b66b43', '#6b3327'],
    minutes: 32,
    difficulty: 1,
    rating: 4.9,
    calories: 526,
    servings: 2,
    vegetarian: false,
    tastes: ['酸甜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鸡翅', amount: 8, unit: '只', role: 'core' },
      { name: '可乐', amount: 330, unit: '毫升', role: 'core' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 1, unit: '小撮', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '鸡翅改刀', text: '鸡翅两面各划两刀，擦干水分；姜切片。', heat: '不开火', tip: '擦干表面，煎的时候更安全也更容易上色。' },
      { title: '煎到金黄', text: '锅中薄薄刷油，下鸡翅和姜片，中小火煎至两面金黄。', heat: '中火', timerSeconds: 360 },
      { title: '加汁焖煮', text: '倒入可乐和生抽，煮开后转小火，盖盖焖至鸡翅熟透。', heat: '小火', timerSeconds: 900 },
      { title: '大火收汁', text: '开盖转大火，不停翻动，让酱汁浓稠地裹住鸡翅。', heat: '大火', timerSeconds: 180 },
    ],
    tips: ['收汁阶段糖分高，务必看锅避免焦糊。', '鸡翅中心需完全熟透，不应有粉红色肉汁。'],
  },
  {
    id: 'mapo-tofu',
    title: '家常麻婆豆腐',
    subtitle: '麻辣滚烫，米饭要多盛一碗',
    emoji: '🌶️',
    colors: ['#df6b4d', '#8a3028'],
    minutes: 22,
    difficulty: 2,
    rating: 4.9,
    calories: 402,
    servings: 2,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '豆腐', amount: 1, unit: '盒', role: 'core' },
      { name: '猪肉末', amount: 100, unit: '克', role: 'core' },
      { name: '豆瓣酱', amount: 1.5, unit: '汤匙', role: 'core' },
      { name: '花椒', amount: 1, unit: '茶匙', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '豆腐焯水', text: '豆腐切 2 厘米块，淡盐水中煮 1 分钟后捞出。', heat: '中火', timerSeconds: 60, tip: '焯水能去豆腥，也让豆腐更不容易碎。' },
      { title: '炒酥肉末', text: '热锅下油，肉末炒散，直到水汽消失、边缘微焦。', heat: '中火', timerSeconds: 150 },
      { title: '炒香红油', text: '转小火加入豆瓣酱，耐心炒出红油，再加 200 毫升热水和生抽。', heat: '小火', timerSeconds: 90 },
      { title: '烧入味', text: '放入豆腐轻轻推匀，小火咕嘟 5 分钟。', heat: '小火', timerSeconds: 300 },
      { title: '勾芡完成', text: '淀粉加水调开，分两次淋入；轻推至汤汁抱住豆腐，撒花椒和葱花。', heat: '中火', timerSeconds: 60 },
    ],
    tips: ['豆瓣酱本身有咸味，出锅前尝过再决定是否加盐。', '分两次勾芡，汤汁更均匀也不易结块。'],
  },
  {
    id: 'shrimp-egg',
    title: '虾仁滑蛋',
    subtitle: '嫩滑鲜甜，十五分钟上桌',
    emoji: '🦐',
    colors: ['#f3b794', '#e18a78'],
    minutes: 14,
    difficulty: 2,
    rating: 4.8,
    calories: 334,
    servings: 2,
    vegetarian: false,
    tastes: ['清淡', '咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '虾仁', amount: 180, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 4, unit: '个', role: 'core' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '胡椒粉', amount: 1, unit: '小撮', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌好虾仁', text: '虾仁擦干，加一小撮盐、胡椒和淀粉抓匀，静置 5 分钟。', heat: '不开火', timerSeconds: 300 },
      { title: '调匀蛋液', text: '鸡蛋加剩余盐和一汤匙清水打散，加入葱花。', heat: '不开火' },
      { title: '滑熟虾仁', text: '热锅放油，下虾仁炒至两面变红、中心刚熟，盛出。', heat: '中火', timerSeconds: 90 },
      { title: '低温滑蛋', text: '转小火倒蛋液和虾仁，用锅铲从外向内慢慢推，约八成凝固就关火。', heat: '小火', timerSeconds: 90, tip: '锅温太高会让鸡蛋迅速变老。' },
    ],
    tips: ['冷冻虾仁要彻底解冻并擦干。', '关火时蛋液略湿润，余温会把它带到刚好熟。'],
  },
  ...importedCookbookRecipes,
  ...recipesBatchA,
  ...recipesBatchB,
  ...recipesBatchC,
  ...recipesBatchD,
]

const hydratedRecipes = hydrateRecipeCollection(recipes)

export const allIngredients = Array.from(new Set([
  ...ingredientGroups.flatMap((group) => group.items),
  ...hydratedRecipes.flatMap((recipe) => recipe.ingredients.map((ingredient) => ingredient.name)),
])).sort((left, right) => left.localeCompare(right, 'zh-CN'))

export default hydratedRecipes
