import type { Recipe } from './types'
import accordionCucumberImage from './assets/recipes/book/accordion-cucumber.jpg'
import buddhaHandGlutenImage from './assets/recipes/book/buddha-hand-gluten.jpg'
import hakkaStuffedBitterMelonImage from './assets/recipes/book/hakka-stuffed-bitter-melon.jpg'
import luffaGlutenImage from './assets/recipes/book/luffa-gluten.jpg'
import pumpkinCakesImage from './assets/recipes/book/pumpkin-cakes.jpg'
import steamedLuffaImage from './assets/recipes/book/steamed-luffa.jpg'
import winterMelonSoupImage from './assets/recipes/book/winter-melon-soup.jpg'
import yaozhuJieguaImage from './assets/recipes/book/yaozhu-jiegua.jpg'

const source = (pdfPage: number, printedPage: number) => ({
  title: '《贝太厨房：家常食材家常菜》',
  pdfPage,
  printedPage,
  note: '由扫描版菜谱整理，步骤已改写为适合手机阅读的格式。',
})

const stepImageModules = import.meta.glob<string>('./assets/recipes/steps/*.jpg', {
  eager: true,
  import: 'default',
})

const importedCookbookRecipeData: Recipe[] = [
  {
    id: 'book-jie-gua-yaozhu',
    title: '瑶柱淡菜焖节瓜',
    subtitle: '海味鲜香，节瓜软润入味',
    emoji: '🥒',
    colors: ['#d6dfaa', '#78905f'],
    image: yaozhuJieguaImage,
    imageAlt: '瑶柱淡菜焖节瓜成品照片',
    imageKind: 'source',
    minutes: 45,
    difficulty: 2,
    servings: 2,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '蒸锅 + 炒锅',
    ingredients: [
      { name: '节瓜', amount: 1, unit: '只', role: 'core' },
      { name: '瑶柱', amount: 10, unit: '克', role: 'core' },
      { name: '淡菜', amount: 10, unit: '粒', role: 'core' },
      { name: '姜', amount: 2, unit: '片', role: 'support' },
      { name: '黄酒', amount: 30, unit: '毫升', role: 'seasoning' },
      { name: '高汤', amount: 200, unit: '毫升', role: 'seasoning' },
      { name: '食用油', amount: 15, unit: '毫升', role: 'seasoning' },
      { name: '盐', amount: 3, unit: '克', role: 'seasoning' },
      { name: '糖', amount: 5, unit: '克', role: 'seasoning' },
    ],
    steps: [
      { title: '泡发海味', text: '瑶柱和淡菜用温水泡软，加入一片姜、黄酒和少量水，蒸约 30 分钟。取出后把瑶柱撕成丝，并清理淡菜杂毛。', heat: '大火', timerSeconds: 1800 },
      { title: '处理节瓜', text: '节瓜去皮，纵切成四瓣，去籽后切成约 3 厘米见方的块。', heat: '不开火' },
      { title: '煸香淡菜', text: '锅中放油，先把姜片和淡菜煸出香味，再倒入高汤煮开。', heat: '大火', timerSeconds: 300 },
      { title: '焖到软润', text: '加入节瓜和瑶柱丝，煮开后转小火，焖至节瓜软熟，最后用盐和糖调味。', heat: '小火', timerSeconds: 600 },
    ],
    tips: ['蒸海味留下的汤汁很鲜，可以一起倒入锅中。'],
    source: source(59, 57),
  },
  {
    id: 'book-hakka-stuffed-bitter-melon',
    title: '客家酿苦瓜',
    subtitle: '苦瓜酿入鲜肉虾仁，蒸得清香多汁',
    emoji: '🥬',
    colors: ['#a9c779', '#567846'],
    image: hakkaStuffedBitterMelonImage,
    imageAlt: '客家酿苦瓜成品照片',
    imageKind: 'source',
    minutes: 60,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '苦瓜', amount: 2, unit: '条', role: 'core' },
      { name: '猪肉末', amount: 250, unit: '克', role: 'core' },
      { name: '虾仁', amount: 50, unit: '克', role: 'core' },
      { name: '香菇', amount: 3, unit: '朵', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '盐', amount: 3, unit: '克', role: 'seasoning' },
      { name: '香油', amount: 5, unit: '毫升', role: 'seasoning' },
      { name: '淀粉', amount: 5, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '焯苦瓜圈', text: '苦瓜切成约 3 厘米厚的段，挖去瓜瓤和籽，放入沸水煮 2 分钟后捞出。', heat: '大火', timerSeconds: 120 },
      { title: '调肉馅', text: '猪肉末、切碎的虾仁、香菇和葱混合，加入盐和香油，顺一个方向搅拌；分次加入少量清水，搅到有弹性。', heat: '不开火' },
      { title: '填入馅料', text: '把肉馅塞入苦瓜圈并压紧，整齐码入盘中。', heat: '不开火' },
      { title: '蒸熟勾芡', text: '水开后上锅大火蒸约 40 分钟。把盘中汤汁倒入小锅，用水淀粉勾成薄芡，再浇回苦瓜。', heat: '大火', timerSeconds: 2400 },
    ],
    tips: ['肉馅分次吸入少量水，蒸好后会更嫩。'],
    source: source(59, 57),
  },
  {
    id: 'book-buddha-hand-gluten',
    title: '佛手烩面筋',
    subtitle: '佛手瓜清脆，面筋吸满鲜汁',
    emoji: '🥗',
    colors: ['#cfe29c', '#7da35f'],
    image: buddhaHandGlutenImage,
    imageAlt: '佛手烩面筋成品照片',
    imageKind: 'source',
    minutes: 30,
    difficulty: 1,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '佛手瓜', amount: 1, unit: '个', role: 'core' },
      { name: '油面筋', amount: 8, unit: '个', role: 'core' },
      { name: '红菜椒', amount: 1, unit: '个', role: 'support' },
      { name: '姜', amount: 1, unit: '块', role: 'support' },
      { name: '盐', amount: 5, unit: '克', role: 'seasoning' },
      { name: '黄酒', amount: 15, unit: '毫升', role: 'seasoning' },
      { name: '淀粉', amount: 15, unit: '毫升', role: 'seasoning' },
      { name: '食用油', amount: 30, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '切配食材', text: '佛手瓜去皮去核后切薄片，红菜椒切菱形片，姜切片；用筷子在油面筋上扎几个小孔。', heat: '不开火' },
      { title: '炒香蔬菜', text: '中火热油，先爆香姜片，再加入佛手瓜炒 2 分钟，随后放红菜椒和面筋翻炒。', heat: '中火', timerSeconds: 150 },
      { title: '焖煮收汁', text: '加入盐、黄酒和约 150 毫升清水，煮开后小火加盖焖 10 分钟，最后淋水淀粉勾薄芡。', heat: '小火', timerSeconds: 600 },
    ],
    tips: ['面筋下锅前轻轻捏瘪，更容易吸收汤汁。'],
    source: source(60, 58),
  },
  {
    id: 'book-winter-melon-soup',
    title: '三丝冬瓜羹',
    subtitle: '冬瓜细滑，火腿鸡丝带来鲜味',
    emoji: '🥣',
    colors: ['#d8e4bb', '#9aa36f'],
    image: winterMelonSoupImage,
    imageAlt: '三丝冬瓜羹成品照片',
    imageKind: 'source',
    minutes: 40,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '高压锅 + 汤锅',
    ingredients: [
      { name: '冬瓜', amount: 400, unit: '克', role: 'core' },
      { name: '鸡胸肉', amount: 100, unit: '克', role: 'core' },
      { name: '火腿', amount: 20, unit: '克', role: 'support' },
      { name: '红菜椒', amount: 0.25, unit: '个', role: 'support' },
      { name: '青椒', amount: 0.25, unit: '个', role: 'support' },
      { name: '高汤', amount: 800, unit: '毫升', role: 'seasoning' },
      { name: '淀粉', amount: 30, unit: '毫升', role: 'seasoning' },
      { name: '盐', amount: 5, unit: '克', role: 'seasoning' },
    ],
    steps: [
      { title: '准备三丝', text: '火腿和红、青菜椒分别切细丝；鸡胸肉煮熟放凉后撕成细丝。', heat: '中火' },
      { title: '煮软冬瓜', text: '冬瓜去皮去瓤后切片，加入少量水煮至很软，再连汤压成粗羹状。', heat: '小火', timerSeconds: 1200 },
      { title: '合煮成羹', text: '高汤煮开，加入冬瓜羹、火腿丝和鸡丝，再次沸腾后淋入水淀粉，煮 2 分钟并用盐调味。', heat: '大火', timerSeconds: 120 },
      { title: '点缀出锅', text: '盛出后撒上红、青菜椒丝即可。', heat: '不开火' },
    ],
    tips: ['没有高压锅时可以把冬瓜蒸软，时间适当延长。'],
    source: source(60, 58),
  },
  {
    id: 'book-pumpkin-cakes',
    title: '南瓜小饼',
    subtitle: '外层香软，里面藏着豆沙馅',
    emoji: '🎃',
    colors: ['#f4c06a', '#d97b3d'],
    image: pumpkinCakesImage,
    imageAlt: '南瓜小饼成品照片',
    imageKind: 'source',
    minutes: 30,
    difficulty: 2,
    servings: 4,
    vegetarian: true,
    tastes: ['酸甜', '浓郁'],
    cookware: '微波炉 + 炒锅',
    ingredients: [
      { name: '南瓜', amount: 500, unit: '克', role: 'core' },
      { name: '豆沙馅', amount: 100, unit: '克', role: 'core' },
      { name: '面粉', amount: 700, unit: '克', role: 'core' },
      { name: '淀粉', amount: 60, unit: '克', role: 'seasoning' },
      { name: '食用油', amount: 500, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '做南瓜泥', text: '南瓜去皮去籽切薄片，放入带盖容器中微波至软，晾凉后压成泥。', heat: '不开火', timerSeconds: 420 },
      { title: '揉成面团', text: '把南瓜泥、面粉和淀粉混合揉匀，不需要另外加水。', heat: '不开火' },
      { title: '包入豆沙', text: '手上蘸少量凉水，取一团面按扁，包入豆沙，收口后轻压成厚圆饼。', heat: '不开火' },
      { title: '炸至金黄', text: '中火把油加热到约六成热，逐个放入小饼；一面定型后翻面，炸至两面金黄后沥油。', heat: '中火', timerSeconds: 360 },
    ],
    tips: ['南瓜含水量不同，面粉可分次加入，以面团柔软但不粘手为准。'],
    source: source(61, 59),
  },
  {
    id: 'book-luffa-gluten',
    title: '丝瓜面筋',
    subtitle: '丝瓜清甜，面筋柔软吸汁',
    emoji: '🥒',
    colors: ['#b9d887', '#648c54'],
    image: luffaGlutenImage,
    imageAlt: '丝瓜面筋成品照片',
    imageKind: 'source',
    minutes: 20,
    difficulty: 1,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '丝瓜', amount: 400, unit: '克', role: 'core' },
      { name: '油面筋', amount: 20, unit: '克', role: 'core' },
      { name: '扁尖笋', amount: 20, unit: '克', role: 'support' },
      { name: '高汤', amount: 150, unit: '毫升', role: 'seasoning' },
      { name: '盐', amount: 5, unit: '克', role: 'seasoning' },
      { name: '糖', amount: 5, unit: '克', role: 'seasoning' },
      { name: '香油', amount: 5, unit: '毫升', role: 'seasoning' },
      { name: '淀粉', amount: 15, unit: '毫升', role: 'seasoning' },
      { name: '食用油', amount: 15, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '处理食材', text: '丝瓜去皮切滚刀块，油面筋切半；扁尖笋提前泡淡，撕条后切段。', heat: '不开火' },
      { title: '快速翻炒', text: '大火热油，放入丝瓜快速翻炒，加入盐、糖和高汤。', heat: '大火', timerSeconds: 60 },
      { title: '煮软面筋', text: '放入面筋和扁尖笋，煮到面筋柔软入味。', heat: '中火', timerSeconds: 300 },
      { title: '勾芡出锅', text: '淋入水淀粉勾薄芡，关火后加香油拌匀。', heat: '中火', timerSeconds: 45 },
    ],
    tips: ['切好的丝瓜可暂时放入加了少量柠檬汁的冷水中，颜色更清亮。'],
    source: source(61, 59),
  },
  {
    id: 'book-steamed-luffa',
    title: '剁椒蒸丝瓜',
    subtitle: '剁椒鲜辣，粉丝吸满丝瓜汤汁',
    emoji: '🌶️',
    colors: ['#d5d98d', '#cc6751'],
    image: steamedLuffaImage,
    imageAlt: '剁椒蒸丝瓜成品照片',
    imageKind: 'source',
    minutes: 30,
    difficulty: 1,
    servings: 2,
    vegetarian: true,
    tastes: ['香辣', '咸鲜'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '丝瓜', amount: 2, unit: '根', role: 'core' },
      { name: '粉丝', amount: 50, unit: '克', role: 'core' },
      { name: '剁椒', amount: 50, unit: '克', role: 'core' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '料酒', amount: 5, unit: '毫升', role: 'seasoning' },
      { name: '蚝油', amount: 5, unit: '毫升', role: 'seasoning' },
      { name: '糖', amount: 10, unit: '克', role: 'seasoning' },
      { name: '食用油', amount: 15, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '泡粉丝切丝瓜', text: '粉丝用凉水泡软；丝瓜去皮切滚刀块，小葱切碎。', heat: '不开火' },
      { title: '炒香剁椒', text: '中火热油，加入葱末和剁椒炒香，再放料酒、蚝油和糖翻匀。', heat: '中火', timerSeconds: 120 },
      { title: '装盘', text: '粉丝铺在盘底，上面码放丝瓜，再把炒香的剁椒均匀铺上。', heat: '不开火' },
      { title: '蒸熟', text: '蒸锅水开后放入菜盘，加盖大火蒸 10 分钟。', heat: '大火', timerSeconds: 600 },
    ],
    tips: ['剁椒本身有盐味，通常不必再加盐；减少剁椒时再酌量补盐。'],
    source: source(62, 60),
  },
  {
    id: 'book-accordion-cucumber',
    title: '蓑衣黄瓜',
    subtitle: '酸甜麻香，层层入味的凉菜',
    emoji: '🥒',
    colors: ['#b9d976', '#4f8d58'],
    image: accordionCucumberImage,
    imageAlt: '蓑衣黄瓜成品照片',
    imageKind: 'source',
    minutes: 80,
    difficulty: 2,
    servings: 3,
    vegetarian: true,
    tastes: ['酸爽', '酸甜', '微辣'],
    cookware: '小锅 · 1 口锅',
    ingredients: [
      { name: '黄瓜', amount: 3, unit: '根', role: 'core' },
      { name: '朝天椒', amount: 3, unit: '个', role: 'support' },
      { name: '花椒', amount: 5, unit: '克', role: 'support' },
      { name: '白芝麻', amount: 5, unit: '克', role: 'support' },
      { name: '香醋', amount: 30, unit: '毫升', role: 'seasoning' },
      { name: '糖', amount: 15, unit: '克', role: 'seasoning' },
      { name: '盐', amount: 10, unit: '克', role: 'seasoning' },
      { name: '食用油', amount: 15, unit: '毫升', role: 'seasoning' },
      { name: '香油', amount: 10, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '准备配料', text: '朝天椒切丝后泡冷水，白芝麻用小火焙到微黄并晾凉。', heat: '小火' },
      { title: '切蓑衣刀', text: '黄瓜斜刀切至约三分之二深，不要切断；翻转 180 度，再用同样方法切另一面。', heat: '不开火', tip: '黄瓜两侧垫筷子，可以防止下刀过深。' },
      { title: '制作麻香油', text: '小火加热食用油，放花椒和辣椒丝炸香，变色后离火。', heat: '小火', timerSeconds: 90 },
      { title: '冷藏腌制', text: '黄瓜加入香醋、糖、盐、香油和麻香油拌匀，冷藏腌 1 小时；吃前切段并撒白芝麻。', heat: '不开火', timerSeconds: 3600 },
    ],
    tips: ['用筷子垫住黄瓜两侧，是新手切出蓑衣形最稳的方法。'],
    source: source(62, 60),
  },
]

export const importedCookbookRecipes: Recipe[] = importedCookbookRecipeData.map((recipe) => ({
  ...recipe,
  steps: recipe.steps.map((step, index) => ({
    ...step,
    image: stepImageModules[`./assets/recipes/steps/${recipe.id}-${index + 1}.jpg`],
    imageAlt: `${recipe.title}第 ${index + 1} 步“${step.title}”的 AI 示意图`,
    imageKind: 'ai-generated',
  })),
}))
