import type { Recipe } from './types'

export const recipesBatchB: Recipe[] = [
  {
    id: 'steamed-sea-bass',
    title: '清蒸鲈鱼',
    subtitle: '葱姜提鲜，鱼肉细嫩清爽',
    emoji: '🐟',
    colors: ['#d7e4cf', '#71947b'],
    minutes: 25,
    difficulty: 2,
    rating: 4.9,
    calories: 238,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '鲈鱼', amount: 1, unit: '条（约 600 克）', role: 'core' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '红菜椒', amount: 0.25, unit: '个', role: 'support' },
      { name: '蒸鱼豉油', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['生抽'] },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清理腌鱼', text: '鲈鱼去鳞、去鳃和内脏，冲净腹腔血水后擦干；鱼身划两刀，抹黄酒并放一半姜葱。', heat: '不开火', timerSeconds: 600, tip: '鱼腹和脊骨旁的血块要冲净，蒸好才没有腥味。' },
      { title: '沸水上锅', text: '蒸锅水烧开，把鱼盘放入锅中并盖严锅盖，保持足量蒸汽。', heat: '大火' },
      { title: '蒸熟焖透', text: '约 600 克的鱼大火蒸 9 分钟，关火再焖 2 分钟；确认最厚处鱼肉已变白并能轻松剥离鱼骨。', heat: '大火', timerSeconds: 540 },
      { title: '淋汁增香', text: '倒掉盘中腥水，换上葱丝和红椒丝，淋蒸鱼豉油；食用油烧至微微冒烟后浇在葱丝上。', heat: '中火', timerSeconds: 30 },
    ],
    tips: ['鱼的大小会影响蒸制时间，食用前务必确认靠近脊骨的肉完全不透明、没有血色。', '鲈鱼仍有肋骨和细刺，夹取时顺着鱼骨分肉，给老人和儿童食用前要逐块检查去刺。'],
  },
  {
    id: 'braised-hairtail',
    title: '红烧带鱼',
    subtitle: '酱香浓郁，鱼段入味不腥',
    emoji: '🐟',
    colors: ['#d9ad83', '#8f563e'],
    minutes: 40,
    difficulty: 2,
    rating: 4.8,
    calories: 386,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '带鱼', amount: 500, unit: '克', role: 'core' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '淀粉', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '醋', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理带鱼', text: '带鱼段去除内脏和腹内黑膜，洗净擦干，加黄酒和两片姜腌 10 分钟，再薄薄裹一层淀粉。', heat: '不开火', timerSeconds: 600 },
      { title: '煎定鱼段', text: '锅烧热放油，带鱼平码入锅，中火煎至两面金黄定形后盛出。', heat: '中火', timerSeconds: 480, tip: '鱼段下锅后先不要拨动，底面定形再翻面。' },
      { title: '调汁焖烧', text: '原锅炒香姜、蒜和葱白，放回带鱼，加生抽、老抽、醋、糖及约 250 毫升热水，烧开后加盖焖煮。', heat: '小火', timerSeconds: 600 },
      { title: '收汁装盘', text: '开盖转中火，把汤汁收至略稠；轻推鱼段让酱汁裹匀，撒葱花后装盘。', heat: '中火', timerSeconds: 180 },
    ],
    tips: ['带鱼段中心肉必须完全变白且能轻松剥离主骨，未熟透时继续加盖焖煮。', '带鱼有一条硬主骨和边缘细刺，食用时不要整段吞咬，儿童和老人应先拆骨再吃。'],
  },
  {
    id: 'pan-fried-hairtail',
    title: '香煎带鱼',
    subtitle: '外皮焦香，里面鲜嫩多汁',
    emoji: '🐟',
    colors: ['#e3c37d', '#9a7042'],
    minutes: 30,
    difficulty: 2,
    rating: 4.7,
    calories: 348,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜'],
    cookware: '平底锅 · 1 口锅',
    ingredients: [
      { name: '带鱼', amount: 450, unit: '克', role: 'core' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '去腥擦干', text: '带鱼段清理掉内脏和黑膜，洗净后彻底擦干，加姜片、黄酒、盐和胡椒粉腌 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '薄裹淀粉', text: '拣去姜片，用厨房纸吸掉鱼段表面水分，再把两面均匀蘸上薄薄一层淀粉并抖去浮粉。', heat: '不开火' },
      { title: '两面香煎', text: '平底锅烧热放油，鱼段单层排开，中火每面煎约 4 分钟，待金黄定形后只翻一次。', heat: '中火', timerSeconds: 480 },
      { title: '复热出锅', text: '转小火再煎 2 分钟，让较厚鱼段中心熟透；夹出沥油并撒葱花。', heat: '小火', timerSeconds: 120 },
    ],
    tips: ['煎好后掰开最厚的一段检查，鱼肉应完全不透明且没有血色，不能只凭外皮金黄判断熟度。', '带鱼主骨硬、边缘还有细刺，进食时应沿骨慢慢剥肉，儿童食用必须由成人去刺。'],
  },
  {
    id: 'pickled-cabbage-fish',
    title: '酸菜鱼',
    subtitle: '酸香开胃，鱼片滑嫩入味',
    emoji: '🍲',
    colors: ['#d5d080', '#778448'],
    minutes: 40,
    difficulty: 3,
    rating: 4.9,
    calories: 412,
    servings: 4,
    vegetarian: false,
    tastes: ['酸爽', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '草鱼片', amount: 500, unit: '克', role: 'core', substitutes: ['黑鱼片', '鲈鱼片'] },
      { name: '酸菜', amount: 250, unit: '克', role: 'core' },
      { name: '豆芽', amount: 150, unit: '克', role: 'support' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 5, unit: '个', role: 'support' },
      { name: '淀粉', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '蛋清', amount: 1, unit: '个', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '白胡椒粉', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '鱼片上浆', text: '鱼片逐片检查并拔掉明显鱼刺，加黄酒、白胡椒粉、蛋清和淀粉轻轻抓匀，腌 15 分钟。', heat: '不开火', timerSeconds: 900 },
      { title: '炒酸菜底汤', text: '酸菜挤去部分汁水后切段；锅中放油，炒香姜蒜和酸菜，加入约 900 毫升热水煮 8 分钟。', heat: '中火', timerSeconds: 480 },
      { title: '煮熟配菜', text: '放入豆芽煮至断生，加少量盐调味，再把酸菜和豆芽捞到大碗底部。', heat: '大火', timerSeconds: 120 },
      { title: '滑熟鱼片', text: '汤保持微沸，将鱼片逐片放入；轻推至鱼片完全变白卷起，再连汤倒入碗中，撒干辣椒并淋少量热油。', heat: '中火', timerSeconds: 180 },
    ],
    tips: ['鱼片必须煮到内外完全不透明、轻压能分层，较厚的鱼片要适当延长时间。', '即使购买切好的鱼片也可能残留细刺，腌制前和入口前都要检查，老人儿童尤其需要先去刺。'],
  },
  {
    id: 'sichuan-boiled-fish',
    title: '水煮鱼',
    subtitle: '麻辣鲜香，鱼片嫩而不碎',
    emoji: '🌶️',
    colors: ['#e38262', '#a4372c'],
    minutes: 45,
    difficulty: 3,
    rating: 4.9,
    calories: 528,
    servings: 4,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '黑鱼片', amount: 500, unit: '克', role: 'core', substitutes: ['草鱼片', '鲈鱼片'] },
      { name: '豆芽', amount: 200, unit: '克', role: 'support' },
      { name: '莴笋', amount: 200, unit: '克', role: 'support' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '大蒜', amount: 6, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 12, unit: '个', role: 'support' },
      { name: '花椒', amount: 1, unit: '汤匙', role: 'support' },
      { name: '豆瓣酱', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '蛋清', amount: 1, unit: '个', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '食用油', amount: 4, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌制鱼片', text: '鱼片检查去刺后，加生抽、蛋清和淀粉轻抓至有黏性，静置 15 分钟；莴笋切片。', heat: '不开火', timerSeconds: 900 },
      { title: '焯熟垫菜', text: '锅中水烧开，依次把豆芽和莴笋焯至断生，沥水后铺在大碗底部。', heat: '大火', timerSeconds: 180 },
      { title: '熬汤煮鱼', text: '锅中放一半油，炒香姜蒜和豆瓣酱，加约 800 毫升热水煮 5 分钟；转中火逐片下鱼，煮到全部不透明后倒入碗中。', heat: '中火', timerSeconds: 420 },
      { title: '激发麻辣香', text: '鱼片表面铺干辣椒段和花椒；剩余油烧热后均匀浇下，听到滋响即可。', heat: '中火', timerSeconds: 40 },
    ],
    tips: ['鱼片要在汤中彻底变白并熟透，不能为追求嫩滑而缩短到中心仍透明。', '鱼片可能夹带细刺，入口时应小口慢嚼；给老人儿童盛取时需逐片检查去刺。'],
  },
  {
    id: 'chopped-chili-fish-head',
    title: '剁椒鱼头',
    subtitle: '鲜辣蒸透，汤汁拌饭也香',
    emoji: '🌶️',
    colors: ['#e4896d', '#9d3b31'],
    minutes: 40,
    difficulty: 3,
    rating: 4.8,
    calories: 436,
    servings: 4,
    vegetarian: false,
    tastes: ['香辣', '咸鲜'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '胖头鱼头', amount: 1, unit: '个（约 800 克）', role: 'core' },
      { name: '剁椒', amount: 120, unit: '克', role: 'core' },
      { name: '姜', amount: 8, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '蒸鱼豉油', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['生抽'] },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清洗鱼头', text: '鱼头从中间劈开但不切断，去净鱼鳃、牙床附近杂质和血块，冲洗擦干后抹黄酒，垫上姜片。', heat: '不开火', timerSeconds: 600 },
      { title: '铺好剁椒', text: '剁椒沥去部分咸汁，与蒜末、糖拌匀，均匀铺满鱼头表面。', heat: '不开火' },
      { title: '大火蒸透', text: '蒸锅水开后放入鱼头，大火蒸 13 至 15 分钟；关火焖 2 分钟，确认最厚处鱼肉完全变白。', heat: '大火', timerSeconds: 900 },
      { title: '热油收尾', text: '倒掉少量腥水，淋蒸鱼豉油，撒葱花；食用油加热后浇在葱花和剁椒上。', heat: '中火', timerSeconds: 30 },
    ],
    tips: ['鱼头肉厚，必须确认鱼颈和贴骨位置没有血水、肉质完全不透明后再食用。', '鱼头含碎骨、鳃盖硬刺和牙齿，取肉时不要用力啃咬，老人儿童应由成人挑净骨刺。'],
  },
  {
    id: 'sweet-sour-fish-chunks',
    title: '糖醋鱼块',
    subtitle: '外香里嫩，酸甜汁明亮开胃',
    emoji: '🐟',
    colors: ['#efa06f', '#bd4c3f'],
    minutes: 35,
    difficulty: 2,
    rating: 4.7,
    calories: 462,
    servings: 3,
    vegetarian: false,
    tastes: ['酸甜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '去骨鱼柳', amount: 450, unit: '克', role: 'core', substitutes: ['巴沙鱼柳', '龙利鱼柳'] },
      { name: '红菜椒', amount: 0.5, unit: '个', role: 'support' },
      { name: '青椒', amount: 0.5, unit: '个', role: 'support' },
      { name: '姜', amount: 3, unit: '片', role: 'support' },
      { name: '番茄酱', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '醋', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 5, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 4, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切块腌制', text: '鱼柳摸查残刺后切成约 3 厘米块，加黄酒、生抽和姜丝拌匀，腌 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '煎熟鱼块', text: '鱼块裹匀 4 汤匙淀粉；锅中放油，中火把各面煎至金黄，较厚鱼块中心完全变白后盛出。', heat: '中火', timerSeconds: 600 },
      { title: '调糖醋汁', text: '原锅留少量油，下红椒和青椒炒至断生；加入番茄酱、醋、糖及 100 毫升清水煮开。', heat: '中火', timerSeconds: 180 },
      { title: '裹汁出锅', text: '剩余淀粉加少量水调匀倒入锅中，汤汁变亮后放回鱼块，快速翻匀立即出锅。', heat: '中火', timerSeconds: 60 },
    ],
    tips: ['鱼块厚薄不同会影响熟度，最厚的一块应切开确认中心完全不透明、无生冷感。', '标注去骨的鱼柳也可能残留细刺，切块时用指腹摸查，给儿童食用前仍需逐块检查。'],
  },
  {
    id: 'garlic-vermicelli-shrimp',
    title: '蒜蓉粉丝虾',
    subtitle: '蒜香浓郁，粉丝吸足鲜汁',
    emoji: '🦐',
    colors: ['#f1b083', '#b85e49'],
    minutes: 30,
    difficulty: 2,
    rating: 4.9,
    calories: 358,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '鲜虾', amount: 12, unit: '只（约 400 克）', role: 'core' },
      { name: '粉丝', amount: 100, unit: '克', role: 'core' },
      { name: '大蒜', amount: 1, unit: '头', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '红菜椒', amount: 0.25, unit: '个', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '泡粉丝开虾', text: '粉丝用温水泡软后剪短；鲜虾剪去虾须和尖刺，从背部剖开并去虾线，保留虾壳。', heat: '不开火', timerSeconds: 900 },
      { title: '炒制蒜蓉', text: '锅中放油，小火炒香一半蒜末，关火后拌入另一半蒜末、生抽、糖和 3 汤匙清水。', heat: '小火', timerSeconds: 90 },
      { title: '摆盘蒸制', text: '粉丝铺在盘底，虾背朝上排好，把蒜蓉汁填在虾背并淋到粉丝上；水开后大火蒸 7 分钟。', heat: '大火', timerSeconds: 420 },
      { title: '检查出锅', text: '确认虾肉全部不透明、虾壳变红后取出，撒葱花和红椒末，再淋少量热油。', heat: '中火', timerSeconds: 30 },
    ],
    tips: ['鲜虾必须蒸到肉质完全不透明且有弹性，个头较大时应适当延长蒸制时间。', '虾头尖刺、虾须和开背后的壳边可能划口，食用前先去壳；去虾线时也要检查是否残留硬壳碎片。'],
  },
  {
    id: 'blanched-shrimp',
    title: '白灼虾',
    subtitle: '原汁原味，蘸汁清鲜爽口',
    emoji: '🦐',
    colors: ['#f2b18c', '#c66a55'],
    minutes: 18,
    difficulty: 1,
    rating: 4.8,
    calories: 226,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '鲜虾', amount: 500, unit: '克', role: 'core' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '大蒜', amount: 2, unit: '瓣', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '醋', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.25, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '修剪鲜虾', text: '鲜虾冲洗干净，剪去长虾须和头部尖刺，用牙签从背部挑出虾线。', heat: '不开火' },
      { title: '煮香灼水', text: '锅中加入足量清水、姜片、葱结和黄酒，大火煮沸 2 分钟，让香味进入水中。', heat: '大火', timerSeconds: 120 },
      { title: '灼熟鲜虾', text: '倒入鲜虾并轻轻搅散，水重新沸腾后继续煮 2 至 3 分钟，虾壳全红、虾肉不透明即捞出。', heat: '大火', timerSeconds: 180 },
      { title: '调汁装盘', text: '蒜切末，与生抽、醋、糖和一汤匙温水调成蘸汁；鲜虾沥水后装盘。', heat: '不开火' },
    ],
    tips: ['不能仅看虾壳变红，剥开最大的一只确认虾肉从表到里完全不透明后再食用。', '剥虾时避开虾枪和硬壳边缘，儿童食用应由成人去头、去壳并检查硬壳碎片。'],
  },
  {
    id: 'oil-braised-prawns',
    title: '油焖大虾',
    subtitle: '酱汁红亮，虾肉鲜甜入味',
    emoji: '🦐',
    colors: ['#e9906f', '#ad4437'],
    minutes: 28,
    difficulty: 2,
    rating: 4.8,
    calories: 342,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '酸甜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '大虾', amount: 500, unit: '克', role: 'core' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '番茄酱', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '糖', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理大虾', text: '剪去虾须、虾脚和头部尖刺，从背部剪开虾壳并挑出虾线，洗净后充分擦干。', heat: '不开火' },
      { title: '煎出虾油', text: '锅烧热放油，下姜片和葱白，再放大虾中火煎至两面变红，用锅铲轻压虾头释放虾油。', heat: '中火', timerSeconds: 240 },
      { title: '加汁焖熟', text: '加入黄酒、番茄酱、生抽、糖、盐和约 100 毫升热水，加盖小火焖 5 分钟。', heat: '小火', timerSeconds: 300 },
      { title: '收浓亮汁', text: '开盖转中火翻动大虾，把汤汁收至能薄薄挂在虾壳上，撒葱段出锅。', heat: '中火', timerSeconds: 150 },
    ],
    tips: ['出锅前剥开最大的一只检查，虾肉应完全不透明且紧实，中心仍发灰透明时需要继续焖。', '虾枪和剪开的虾壳边缘锋利，夹取与剥壳时注意手部；儿童食用须先去头去壳。'],
  },
  {
    id: 'salt-pepper-shrimp',
    title: '椒盐虾',
    subtitle: '壳香酥脆，椒盐干爽不油腻',
    emoji: '🦐',
    colors: ['#e7b177', '#9f6744'],
    minutes: 30,
    difficulty: 2,
    rating: 4.7,
    calories: 398,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鲜虾', amount: 500, unit: '克', role: 'core' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '红辣椒', amount: 1, unit: '个', role: 'support' },
      { name: '淀粉', amount: 4, unit: '汤匙', role: 'seasoning' },
      { name: '椒盐', amount: 1.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '开背沥干', text: '鲜虾剪去虾须和尖刺，开背去虾线；洗净后用厨房纸彻底吸干水分。', heat: '不开火' },
      { title: '裹粉煎虾', text: '虾薄裹淀粉；锅中油烧热，单层放入鲜虾，中火煎至两面酥红、虾肉完全不透明后盛出。', heat: '中火', timerSeconds: 480 },
      { title: '炒香料头', text: '倒出多余油，留约一茶匙，放蒜末、葱白和红辣椒末小火炒香。', heat: '小火', timerSeconds: 60 },
      { title: '撒粉翻匀', text: '放回煎好的虾，均匀撒椒盐，大火快速翻拌 20 秒后关火。', heat: '大火', timerSeconds: 20 },
    ],
    tips: ['大虾壳变红后还要确认背部最厚处虾肉完全不透明，避免外壳焦香而内部未熟。', '酥壳仍可能有锋利虾枪和硬边，不建议儿童连壳吃，进食前应去头去壳并检查碎壳。'],
  },
  {
    id: 'chive-squid',
    title: '韭菜炒鱿鱼',
    subtitle: '鲜香脆嫩，旺火快炒不出水',
    emoji: '🦑',
    colors: ['#b9d47e', '#56804b'],
    minutes: 22,
    difficulty: 2,
    rating: 4.7,
    calories: 268,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鲜鱿鱼', amount: 400, unit: '克', role: 'core' },
      { name: '韭菜', amount: 200, unit: '克', role: 'core' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '红菜椒', amount: 0.5, unit: '个', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清理切花', text: '鱿鱼去内脏、透明软骨、眼睛和硬嘴，撕掉外膜后洗净；鱼身内侧切浅花刀再切片，韭菜切段。', heat: '不开火' },
      { title: '快速焯水', text: '锅中水烧开，放入鱿鱼片焯 30 秒，刚卷起就捞出并彻底沥水。', heat: '大火', timerSeconds: 30 },
      { title: '爆香鱿鱼', text: '炒锅烧热放油，爆香姜蒜，倒入鱿鱼和红椒，大火翻炒并淋黄酒、生抽。', heat: '大火', timerSeconds: 90 },
      { title: '下韭菜出锅', text: '加入韭菜和盐，大火翻炒到韭菜变软、鱿鱼肉完全不透明后立即出锅。', heat: '大火', timerSeconds: 60 },
    ],
    tips: ['鱿鱼必须炒熟透，达到整体不透明且卷曲定形，较厚部位没有半透明生肉后再食用。', '清理时务必取出透明软骨和触腕中央的硬嘴，这些硬物容易卡喉；给儿童食用应切小并再次检查。'],
  },
  {
    id: 'scallion-ginger-crab',
    title: '葱姜炒蟹',
    subtitle: '葱姜鲜香，蟹肉饱满入味',
    emoji: '🦀',
    colors: ['#e0a069', '#a6503c'],
    minutes: 35,
    difficulty: 3,
    rating: 4.8,
    calories: 356,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '梭子蟹', amount: 2, unit: '只（约 700 克）', role: 'core' },
      { name: '小葱', amount: 5, unit: '根', role: 'support' },
      { name: '姜', amount: 1, unit: '块', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '淀粉', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 3, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清理切蟹', text: '梭子蟹刷洗干净，揭壳后去掉蟹鳃、胃囊和脐部，蟹身斩成块；切口薄蘸淀粉。', heat: '不开火', tip: '处理活蟹时先固定蟹钳，避免夹伤。' },
      { title: '煎封切口', text: '锅中放油，把蟹块切口朝下煎至定形，再翻炒到蟹壳开始变红后盛出。', heat: '中火', timerSeconds: 300 },
      { title: '葱姜焖熟', text: '原锅炒香姜片、蒜和葱白，放回蟹块，淋黄酒和生抽，加 120 毫升热水并盖盖焖 7 分钟。', heat: '中火', timerSeconds: 420 },
      { title: '收汁翻匀', text: '开盖加糖和葱段，大火把汁收浓；确认蟹肉完全不透明、蟹壳通红后装盘。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['蟹肉必须从半透明变为完全不透明，关节和大钳内的肉也要熟透，死蟹或有异味的蟹不要烹食。', '蟹壳碎边和蟹钳尖锐，斩切后尤其容易扎口；儿童食用应由成人拆壳、剔除硬壳碎片。'],
  },
  {
    id: 'clam-steamed-egg',
    title: '蛤蜊蒸蛋',
    subtitle: '蛋羹滑嫩，蛤蜊鲜味自然',
    emoji: '🥚',
    colors: ['#ead79a', '#a88756'],
    minutes: 35,
    difficulty: 2,
    rating: 4.8,
    calories: 252,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 + 蒸锅',
    ingredients: [
      { name: '蛤蜊', amount: 300, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '姜', amount: 3, unit: '片', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '吐沙煮蛤蜊', text: '蛤蜊提前吐沙并刷净外壳；加姜片和 400 毫升水煮至开口，立即捞出，未开口的丢弃，煮蛤蜊的水静置过滤。', heat: '大火', timerSeconds: 240 },
      { title: '调好蛋液', text: '鸡蛋打散，加入约 300 毫升温热的过滤蛤蜊汤和盐，轻轻搅匀后过筛。', heat: '不开火' },
      { title: '小火蒸蛋', text: '开口蛤蜊排入浅碗，倒入蛋液并盖上盘子；水开后转小火蒸 10 分钟，再关火焖 2 分钟。', heat: '小火', timerSeconds: 600 },
      { title: '确认调味', text: '确认蛋液完全凝固、蛤蜊肉熟透后取出，淋生抽和香油，撒葱花。', heat: '不开火' },
    ],
    tips: ['蛤蜊必须煮到开口且肉质熟透，烹煮后仍不开口的要直接丢弃，不要强行掰开食用。', '蛤蜊壳可能有裂片，过滤原汤并检查碗内碎壳；给儿童食用建议先把蛤蜊肉取出再拌入蛋羹。'],
  },
  {
    id: 'stir-fried-clams',
    title: '清炒蛤蜊',
    subtitle: '做法简单，保留蛤蜊本身鲜甜',
    emoji: '🐚',
    colors: ['#d9c8a8', '#7e8067'],
    minutes: 22,
    difficulty: 1,
    rating: 4.6,
    calories: 198,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '蛤蜊', amount: 500, unit: '克', role: 'core' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '吐沙刷壳', text: '蛤蜊提前用淡盐水吐沙，烹调前逐个刷洗外壳并冲净，破壳或有异味的丢弃。', heat: '不开火' },
      { title: '爆香姜蒜', text: '炒锅烧热放油，下姜片、蒜片和葱白，中火炒出香味。', heat: '中火', timerSeconds: 45 },
      { title: '加盖炒开', text: '倒入蛤蜊，沿锅边淋黄酒，立即加盖大火焖 3 至 4 分钟，中途晃锅一次。', heat: '大火', timerSeconds: 240 },
      { title: '调味出锅', text: '开盖挑出始终不开口的蛤蜊，确认其余蛤蜊肉熟透，撒白胡椒粉和葱段翻匀出锅。', heat: '大火', timerSeconds: 30 },
    ],
    tips: ['蛤蜊要加热到开口且肉质熟透，烹煮后仍闭合的不能食用，也不要缩短加盖焖制时间。', '外壳和断裂壳片可能划伤口腔，盛盘前检查碎壳，给儿童食用应先取肉并确认无硬片。'],
  },
  {
    id: 'spicy-clams',
    title: '香辣花甲',
    subtitle: '酱香带辣，鲜汁越炒越入味',
    emoji: '🐚',
    colors: ['#dd8664', '#963e31'],
    minutes: 30,
    difficulty: 2,
    rating: 4.8,
    calories: 286,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '汤锅 + 炒锅',
    ingredients: [
      { name: '花甲', amount: 600, unit: '克', role: 'core' },
      { name: '洋葱', amount: 0.5, unit: '个', role: 'support' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '干辣椒', amount: 8, unit: '个', role: 'support' },
      { name: '豆瓣酱', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '吐沙焯开', text: '花甲提前吐沙并刷净；沸水下锅，壳刚开就捞出，冲去浮沫并丢弃始终不开口或破损的花甲。', heat: '大火', timerSeconds: 180 },
      { title: '炒香辣酱', text: '炒锅放油，先炒香姜、蒜、洋葱和干辣椒，再加入豆瓣酱炒出红油。', heat: '中火', timerSeconds: 120 },
      { title: '回锅烧透', text: '倒入花甲，加生抽、黄酒、糖和 80 毫升热水，大火翻炒后加盖焖 2 分钟，让花甲肉熟透。', heat: '大火', timerSeconds: 120 },
      { title: '收汁撒葱', text: '开盖快速翻炒到酱汁裹壳，撒葱段后关火，装盘前再次挑出异常闭壳。', heat: '大火', timerSeconds: 45 },
    ],
    tips: ['花甲肉必须彻底受热熟透，焯煮和回锅后仍不开口的全部丢弃，不要食用死贝或异味贝。', '花甲壳薄且容易碎，翻炒不要猛砸；入口前检查壳片，儿童应先去壳取肉。'],
  },
  {
    id: 'crucian-carp-tofu-soup',
    title: '鲫鱼豆腐汤',
    subtitle: '汤色奶白，鱼鲜豆腐嫩滑',
    emoji: '🍲',
    colors: ['#e4dfc7', '#87947e'],
    minutes: 45,
    difficulty: 2,
    rating: 4.8,
    calories: 326,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '煎锅 + 汤锅',
    ingredients: [
      { name: '鲫鱼', amount: 1, unit: '条（约 500 克）', role: 'core' },
      { name: '嫩豆腐', amount: 300, unit: '克', role: 'core' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清理鲫鱼', text: '鲫鱼去鳞、去鳃和内脏，刮净腹内黑膜与血水；洗净擦干，在鱼身两面各划两刀。', heat: '不开火' },
      { title: '煎香鱼身', text: '锅烧热放油和姜片，鲫鱼下锅后中火煎至两面金黄定形，沿锅边淋黄酒。', heat: '中火', timerSeconds: 480 },
      { title: '沸煮出白汤', text: '一次加入约 1.2 升沸水，大火煮 8 分钟，再转中火煮 12 分钟，汤色逐渐变白。', heat: '中火', timerSeconds: 1200 },
      { title: '加入豆腐', text: '嫩豆腐切块放入汤中，再煮 8 分钟；确认鱼肉贴骨处完全熟透后，加盐、白胡椒粉和葱花。', heat: '中火', timerSeconds: 480 },
    ],
    tips: ['鲫鱼贴骨处必须完全变白、没有血色后再食用，汤滚并不代表厚处鱼肉一定熟透。', '鲫鱼细刺很多，不适合直接大口喝带鱼肉的汤；老人儿童食用应过滤汤汁并由成人仔细拆肉去刺。'],
  },
  {
    id: 'seaweed-dried-shrimp-soup',
    title: '紫菜虾皮汤',
    subtitle: '十分钟鲜汤，清爽省事',
    emoji: '🥣',
    colors: ['#bac4a7', '#5d7168'],
    minutes: 12,
    difficulty: 1,
    rating: 4.6,
    calories: 136,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '紫菜', amount: 10, unit: '克', role: 'core' },
      { name: '虾皮', amount: 20, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 2, unit: '个', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '姜', amount: 2, unit: '片', role: 'support' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清洗备料', text: '紫菜快速冲洗后挤干，虾皮用细筛淘洗并挑去杂质和较硬虾壳，鸡蛋充分打散。', heat: '不开火' },
      { title: '煮透虾皮', text: '锅中加入 800 毫升水和姜片，水开后放入虾皮，中火煮 3 分钟至鲜味释出。', heat: '中火', timerSeconds: 180 },
      { title: '加入紫菜', text: '放入紫菜拨散，再次煮沸 1 分钟，加盐和白胡椒粉调味。', heat: '大火', timerSeconds: 60 },
      { title: '淋入蛋花', text: '保持汤微沸，细细淋入蛋液，待蛋花完全凝固后关火，加入葱花和香油。', heat: '中火', timerSeconds: 45 },
    ],
    tips: ['虾皮虽然多为熟制或干制品，也要在滚汤中充分煮透；蛋花应完全凝固后再食用。', '虾皮可能混有坚硬头壳或杂质，清洗时要仔细挑除，给儿童食用建议过滤后再盛汤。'],
  },
  {
    id: 'tomato-fish-slice-soup',
    title: '番茄鱼片汤',
    subtitle: '酸甜鲜润，鱼片嫩滑无负担',
    emoji: '🍅',
    colors: ['#ef9b7a', '#b8493f'],
    minutes: 30,
    difficulty: 2,
    rating: 4.8,
    calories: 278,
    servings: 3,
    vegetarian: false,
    tastes: ['酸甜', '咸鲜'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '去骨鱼片', amount: 350, unit: '克', role: 'core', substitutes: ['鲈鱼片', '黑鱼片'] },
      { name: '番茄', amount: 3, unit: '个', role: 'core' },
      { name: '金针菇', amount: 120, unit: '克', role: 'support' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '淀粉', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '鱼片上浆', text: '鱼片逐片摸查去刺，加黄酒、淀粉和一小撮盐轻轻抓匀，腌 10 分钟；番茄切块。', heat: '不开火', timerSeconds: 600 },
      { title: '炒出番茄汁', text: '汤锅放油和姜片，加入番茄与一半盐，中火炒软并用锅铲轻压出汁。', heat: '中火', timerSeconds: 300 },
      { title: '煮好汤底', text: '加入约 800 毫升热水和金针菇，大火烧开后转中火煮 5 分钟，加糖和剩余盐调味。', heat: '中火', timerSeconds: 300 },
      { title: '滑熟鱼片', text: '保持汤微沸，将鱼片逐片铺入，先不要大力搅动；煮到每片完全变白卷起后撒葱花。', heat: '中火', timerSeconds: 180 },
    ],
    tips: ['鱼片要煮到中心完全不透明且能轻松分层，厚片应多煮一会儿，不能只看表面变白。', '去骨鱼片仍可能残留细刺，腌制前用指腹检查，给老人儿童盛汤时还要再次逐片去刺。'],
  },
  {
    id: 'home-braised-yellow-croaker',
    title: '家常烧黄花鱼',
    subtitle: '咸鲜微甜，整鱼入味不易碎',
    emoji: '🐟',
    colors: ['#dfbd78', '#8e6740'],
    minutes: 40,
    difficulty: 2,
    rating: 4.8,
    calories: 378,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '黄花鱼', amount: 1, unit: '条（约 600 克）', role: 'core' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '醋', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清理鱼身', text: '黄花鱼去鳞、去鳃和内脏，冲净腹内黑膜与贴骨血水后擦干；两面划斜刀并抹黄酒腌 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '煎至定形', text: '锅烧热放油，黄花鱼下锅后中火煎至两面金黄；翻面时用两把锅铲托住鱼身。', heat: '中火', timerSeconds: 480 },
      { title: '加汁烧透', text: '放入姜、蒜和葱白，加生抽、老抽、醋、糖及约 300 毫升热水，烧开后加盖小火焖 12 分钟。', heat: '小火', timerSeconds: 720 },
      { title: '收汁装盘', text: '开盖将汤汁反复浇在鱼身，转中火收至略浓；确认贴骨鱼肉完全熟透后撒葱花装盘。', heat: '中火', timerSeconds: 180 },
    ],
    tips: ['黄花鱼最厚处和贴脊骨位置都要烧到肉质完全不透明、没有血丝，鱼较大时需延长焖煮。', '整鱼含主骨、肋骨和细刺，取肉时沿骨分离；老人儿童食用前应由成人逐块检查去刺。'],
  },
]
