import type { Recipe } from './types'

export const recipesBatchE: Recipe[] = [
  {
    id: 'red-braised-chicken-pieces',
    title: '红烧鸡块',
    subtitle: '酱色红亮，鸡肉软嫩咸香',
    emoji: '🍗',
    colors: ['#c98158', '#7e4939'],
    minutes: 50,
    difficulty: 2,
    rating: 4.9,
    calories: 468,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡块', amount: 800, unit: '克', role: 'core' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '八角', amount: 2, unit: '个', role: 'support' },
      { name: '生抽', amount: 2.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '冰糖', amount: 15, unit: '克', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯洗鸡块', text: '鸡块冷水下锅，加两片姜和一半黄酒；大火煮开后再煮 2 分钟，捞出用温水洗净浮沫并沥干。', heat: '大火', timerSeconds: 120 },
      { title: '煸香上色', text: '炒锅放油和冰糖，小火炒至糖融化呈浅琥珀色，放鸡块中火翻炒至表面微黄，再加入姜、蒜、八角和葱白。', heat: '中火', timerSeconds: 360 },
      { title: '加汁焖烧', text: '淋入生抽、老抽和剩余黄酒，加入约 550 毫升热水，大火煮开后加盖转小火焖 25 分钟。', heat: '小火', timerSeconds: 1500 },
      { title: '检查收汁', text: '取最厚鸡块确认关节附近没有血色、肉汁清澈，再开盖转大火收至汤汁浓亮，撒葱花出锅。', heat: '大火', timerSeconds: 240 },
    ],
    tips: ['带骨鸡块大小会影响熟制时间，最厚处应达到至少 75°C，肉质完全不透明、关节无血水后才能食用。'],
  },
  {
    id: 'mushroom-chicken-stew',
    title: '香菇炖鸡',
    subtitle: '香菇吸汁，鸡汤鲜醇温润',
    emoji: '🍄',
    colors: ['#b7976c', '#675748'],
    minutes: 75,
    difficulty: 2,
    rating: 4.8,
    calories: 438,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡块', amount: 900, unit: '克', role: 'core' },
      { name: '干香菇', amount: 50, unit: '克', role: 'core', substitutes: ['鲜香菇'] },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '红枣', amount: 6, unit: '颗', role: 'support' },
      { name: '枸杞', amount: 10, unit: '克', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '泡菇焯鸡', text: '干香菇冷水泡软后挤干并去蒂，泡菇水静置取上层清液；鸡块冷水下锅，加黄酒和两片姜，煮开 2 分钟后洗净。', heat: '大火', timerSeconds: 120 },
      { title: '煮开汤底', text: '鸡块、香菇、剩余姜片和去核红枣放入汤锅，加入过滤后的泡菇水及热水共约 1.6 升，大火煮开并撇去浮沫。', heat: '大火', timerSeconds: 300 },
      { title: '小火炖透', text: '锅盖留小缝，转小火炖 45 分钟，中途轻轻翻动鸡块一次，避免锅底粘连。', heat: '小火', timerSeconds: 2700 },
      { title: '加盐完成', text: '确认最厚鸡块关节处完全熟透，加入枸杞和盐再煮 5 分钟，关火后撒葱花。', heat: '中火', timerSeconds: 300 },
    ],
    tips: ['泡香菇应放在阴凉处或冰箱中，泡菇水只取无泥沙的上层并煮沸；鸡肉最厚处需达到至少 75°C。'],
  },
  {
    id: 'huangmen-chicken',
    title: '黄焖鸡',
    subtitle: '鸡腿滑嫩，香菇土豆酱汁浓',
    emoji: '🍲',
    colors: ['#d4a55d', '#896140'],
    minutes: 45,
    difficulty: 2,
    rating: 4.9,
    calories: 526,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '微辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鸡腿肉', amount: 700, unit: '克', role: 'core' },
      { name: '土豆', amount: 350, unit: '克', role: 'core' },
      { name: '干香菇', amount: 30, unit: '克', role: 'support' },
      { name: '青椒', amount: 120, unit: '克', role: 'support' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 3, unit: '个', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '蚝油', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切配腌鸡', text: '香菇冷水泡软后切半；鸡腿肉切块，加黄酒和 1 汤匙生抽拌匀腌 10 分钟；土豆、青椒切块。', heat: '不开火', timerSeconds: 600 },
      { title: '煸炒鸡块', text: '炒锅放油，炒香姜、蒜和干辣椒，放鸡块中火翻炒至各面变色、表面略微焦黄。', heat: '中火', timerSeconds: 420 },
      { title: '焖鸡和土豆', text: '加入香菇、土豆、蚝油、剩余生抽、老抽和糖，倒入约 450 毫升热水，煮开后加盖小火焖 18 分钟。', heat: '小火', timerSeconds: 1080 },
      { title: '加椒收汁', text: '确认鸡块中心完全熟透、土豆能被筷子扎透后放青椒，大火翻炒收汁 2 分钟。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['鸡腿块需煮到中心至少 75°C、无粉红色和血水；干香菇也必须完全泡软并煮透。'],
  },
  {
    id: 'lemon-chicken-breast',
    title: '柠檬鸡胸',
    subtitle: '酸甜清香，鸡胸多汁不柴',
    emoji: '🍋',
    colors: ['#e4cf69', '#8c9c56'],
    minutes: 30,
    difficulty: 2,
    rating: 4.7,
    calories: 286,
    servings: 2,
    vegetarian: false,
    tastes: ['酸甜', '清淡'],
    cookware: '平底锅 · 1 口锅',
    ingredients: [
      { name: '鸡胸肉', amount: 500, unit: '克', role: 'core' },
      { name: '柠檬', amount: 1, unit: '个', role: 'core' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '蜂蜜', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['白糖'] },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黑胡椒', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '拍匀腌味', text: '鸡胸从厚处横向片开，轻拍成约 1.5 厘米均匀厚度，加盐、黑胡椒和淀粉抹匀，冷藏腌 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '煎香两面', text: '平底锅中火烧热放油，鸡胸平码入锅，每面煎约 3 分钟至表面金黄。', heat: '中火', timerSeconds: 360 },
      { title: '加盖焖熟', text: '沿锅边加入 3 汤匙清水，加盖转小火焖 3 至 5 分钟，测量最厚处达到至少 74°C 后盛出静置。', heat: '小火', timerSeconds: 300 },
      { title: '熬汁回裹', text: '原锅小火炒香蒜末，加入半个柠檬的汁、蜂蜜、生抽和 2 汤匙清水，煮至微稠，放回切片鸡胸快速裹汁。', heat: '小火', timerSeconds: 90 },
    ],
    tips: ['柠檬汁要在鸡胸熟透后才入锅，以免长时间酸腌影响口感；切片前先静置 3 分钟，并确认中心没有粉红色。'],
  },
  {
    id: 'mouthwatering-chicken',
    title: '口水鸡',
    subtitle: '鸡腿鲜嫩，红油麻辣层次足',
    emoji: '🌶️',
    colors: ['#d96f4e', '#8f302d'],
    minutes: 45,
    difficulty: 2,
    rating: 4.9,
    calories: 448,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡全腿', amount: 700, unit: '克', role: 'core' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '熟花生米', amount: 30, unit: '克', role: 'support' },
      { name: '熟白芝麻', amount: 1, unit: '汤匙', role: 'support' },
      { name: '辣椒油', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '花椒粉', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '冷水下鸡腿', text: '鸡腿放入汤锅，加入姜片、葱结和足量冷水，大火煮开后撇去浮沫。', heat: '大火', timerSeconds: 300 },
      { title: '小火煮透', text: '转小火保持微沸，煮 22 分钟后关火焖 8 分钟；测量最厚处达到至少 75°C、关节无血水后捞出。', heat: '小火', timerSeconds: 1320 },
      { title: '调麻辣料汁', text: '蒜末、辣椒油、生抽、香醋、花椒粉、糖、香油和 3 汤匙煮鸡原汤搅匀。', heat: '不开火' },
      { title: '斩件淋汁', text: '鸡腿沥干并晾至不烫手，斩成小块装盘，淋满料汁，撒熟花生碎、芝麻和葱花。', heat: '不开火' },
    ],
    tips: ['不要仅凭鸡皮颜色判断熟度，鸡腿贴骨处必须完全熟透；斩切前用干净刀板，不能接触处理生鸡的器具。'],
  },
  {
    id: 'dry-chili-chicken',
    title: '辣子鸡丁',
    subtitle: '鸡丁焦香，干椒花椒麻辣酥香',
    emoji: '🌶️',
    colors: ['#cf563e', '#8b2928'],
    minutes: 35,
    difficulty: 2,
    rating: 4.9,
    calories: 496,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '去骨鸡腿肉', amount: 550, unit: '克', role: 'core' },
      { name: '干辣椒', amount: 30, unit: '克', role: 'support' },
      { name: '花椒', amount: 1, unit: '汤匙', role: 'support' },
      { name: '姜', amount: 15, unit: '克', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '熟白芝麻', amount: 1, unit: '汤匙', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '淀粉', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌制鸡丁', text: '鸡腿肉切成约 2 厘米丁，加生抽、黄酒、盐和淀粉抓匀，冷藏腌 15 分钟；干辣椒剪段并抖去部分籽。', heat: '不开火', timerSeconds: 900 },
      { title: '煎炸至熟', text: '炒锅放油加热至木筷周围冒小泡，鸡丁分批下锅，中火煎炸至金黄，取一块确认中心完全不透明后捞出。', heat: '中火', timerSeconds: 480 },
      { title: '炒香椒料', text: '锅中留约 1 汤匙底油，转小火放干辣椒和花椒炒香，再加入姜片、蒜片和葱白。', heat: '小火', timerSeconds: 90 },
      { title: '回锅翻匀', text: '倒回熟鸡丁，加糖大火快速翻匀，撒熟白芝麻和葱花后立即出锅。', heat: '大火', timerSeconds: 60 },
    ],
    tips: ['鸡丁须分批烹调至中心至少 75°C；生鸡腌料不要再次使用，煎炸时保持食材干燥并防止热油飞溅。'],
  },
  {
    id: 'xinjiang-big-plate-chicken',
    title: '大盘鸡',
    subtitle: '鸡块酱香浓厚，土豆软糯带辣',
    emoji: '🍲',
    colors: ['#cc7848', '#7f5f3e'],
    minutes: 60,
    difficulty: 3,
    rating: 4.9,
    calories: 612,
    servings: 5,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡块', amount: 1, unit: '千克', role: 'core' },
      { name: '土豆', amount: 600, unit: '克', role: 'core' },
      { name: '青椒', amount: 150, unit: '克', role: 'support' },
      { name: '红菜椒', amount: 100, unit: '克', role: 'support' },
      { name: '洋葱', amount: 200, unit: '克', role: 'support' },
      { name: '姜', amount: 20, unit: '克', role: 'support' },
      { name: '大蒜', amount: 8, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 12, unit: '个', role: 'support' },
      { name: '花椒', amount: 1, unit: '茶匙', role: 'support' },
      { name: '八角', amount: 2, unit: '个', role: 'support' },
      { name: '生抽', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 15, unit: '克', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯鸡切配', text: '鸡块冷水下锅煮开 2 分钟，捞出洗净并沥干；土豆切大块，青红椒和洋葱切片。', heat: '大火', timerSeconds: 120 },
      { title: '炒糖和香料', text: '锅中放油和糖，小火炒成浅琥珀色，放鸡块中火翻炒上色，再加入姜、蒜、干辣椒、花椒和八角炒香。', heat: '中火', timerSeconds: 480 },
      { title: '焖鸡和土豆', text: '加入生抽、老抽和约 750 毫升热水，煮开后加盖小火焖 18 分钟；放入土豆再焖 15 分钟。', heat: '小火', timerSeconds: 1980 },
      { title: '加椒收浓', text: '确认鸡块彻底熟透、土豆软而不散，加入洋葱和青红椒，大火翻炒至断生且汤汁浓厚。', heat: '大火', timerSeconds: 180 },
    ],
    tips: ['带骨鸡块最厚处必须达到至少 75°C且关节无血水；炒糖色只需浅琥珀色，过深会发苦并可能冒烟。'],
  },
  {
    id: 'three-cup-chicken',
    title: '三杯鸡',
    subtitle: '麻油姜蒜浓香，九层塔清新提味',
    emoji: '🌿',
    colors: ['#a87351', '#596f45'],
    minutes: 45,
    difficulty: 2,
    rating: 4.9,
    calories: 536,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '砂锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡腿块', amount: 800, unit: '克', role: 'core' },
      { name: '九层塔', amount: 30, unit: '克', role: 'support', substitutes: ['罗勒'] },
      { name: '姜', amount: 30, unit: '克', role: 'support' },
      { name: '大蒜', amount: 10, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 3, unit: '个', role: 'support' },
      { name: '米酒', amount: 100, unit: '毫升', role: 'seasoning', substitutes: ['黄酒'] },
      { name: '生抽', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '冰糖', amount: 18, unit: '克', role: 'seasoning' },
      { name: '芝麻油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯净鸡块', text: '鸡腿块冷水下锅，水开后煮 2 分钟，捞出用温水洗净浮沫并充分沥干。', heat: '大火', timerSeconds: 120 },
      { title: '麻油煸香', text: '砂锅放芝麻油，小火煸姜片至边缘卷起，加入大蒜和干辣椒炒香，再放鸡块转中火煎至表面微黄。', heat: '中火', timerSeconds: 480 },
      { title: '加三味焖煮', text: '加入米酒、生抽、老抽、冰糖和约 150 毫升热水，煮开后加盖小火焖 22 分钟。', heat: '小火', timerSeconds: 1320 },
      { title: '收汁加塔香', text: '确认鸡肉贴骨处熟透后开盖收汁，放入九层塔，盖盖焖 30 秒后拌匀出锅。', heat: '中火', timerSeconds: 150 },
    ],
    tips: ['“三杯”指米酒、酱油和麻油的风味组合，不必各倒一整杯；鸡肉必须达到至少 75°C，砂锅端取时要防烫。'],
  },
  {
    id: 'beer-braised-duck',
    title: '啤酒鸭',
    subtitle: '鸭肉酱香软嫩，麦芽香去腥',
    emoji: '🦆',
    colors: ['#b77b4e', '#655046'],
    minutes: 80,
    difficulty: 2,
    rating: 4.8,
    calories: 584,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸭块', amount: 1, unit: '千克', role: 'core' },
      { name: '啤酒', amount: 500, unit: '毫升', role: 'seasoning' },
      { name: '姜', amount: 20, unit: '克', role: 'support' },
      { name: '大蒜', amount: 6, unit: '瓣', role: 'support' },
      { name: '青椒', amount: 120, unit: '克', role: 'support' },
      { name: '干辣椒', amount: 5, unit: '个', role: 'support' },
      { name: '八角', amount: 2, unit: '个', role: 'support' },
      { name: '桂皮', amount: 1, unit: '小段', role: 'support' },
      { name: '生抽', amount: 2.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯洗鸭块', text: '鸭块冷水下锅，煮开后继续 3 分钟，捞出用温水冲掉浮沫并沥干；青椒切块。', heat: '大火', timerSeconds: 180 },
      { title: '煸出鸭油', text: '锅中放少量油和鸭块，中火煸炒至表面微黄并析出鸭油，加入姜、蒜、干辣椒、八角和桂皮炒香。', heat: '中火', timerSeconds: 600 },
      { title: '倒啤酒焖烧', text: '加入生抽、老抽、糖和啤酒，液面不足时补热水至刚没过鸭块，煮开后加盖小火焖 45 分钟。', heat: '小火', timerSeconds: 2700 },
      { title: '加椒收汁', text: '确认最厚鸭块贴骨处完全熟透且肉质软嫩，放青椒大火翻炒 2 分钟，将汤汁收浓。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['鸭肉最厚处应达到至少 75°C且贴骨无血水；啤酒烹调后仍可能残留少量酒精，不适合需完全避免酒精的人群。'],
  },
  {
    id: 'old-duck-soup',
    title: '老鸭汤',
    subtitle: '鸭汤清醇，山药绵软滋味朴实',
    emoji: '🥣',
    colors: ['#d3c8a1', '#7d785f'],
    minutes: 120,
    difficulty: 2,
    rating: 4.8,
    calories: 456,
    servings: 5,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '老鸭块', amount: 1.2, unit: '千克', role: 'core' },
      { name: '山药', amount: 400, unit: '克', role: 'core' },
      { name: '姜', amount: 8, unit: '片', role: 'support' },
      { name: '红枣', amount: 6, unit: '颗', role: 'support' },
      { name: '枸杞', amount: 10, unit: '克', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯净鸭块', text: '鸭块用冷水浸泡 20 分钟后冲净，冷水下锅，加黄酒和三片姜，煮开 3 分钟后捞出温水洗净。', heat: '大火', timerSeconds: 180 },
      { title: '小火炖鸭', text: '鸭块、剩余姜片、去核红枣和约 2.2 升热水放入汤锅，大火煮开撇沫，转小火炖 70 分钟。', heat: '小火', timerSeconds: 4200 },
      { title: '加入山药', text: '山药去皮切滚刀块放入汤中，继续小火炖 25 分钟，直至山药软糯、鸭肉容易离骨。', heat: '小火', timerSeconds: 1500 },
      { title: '检查调味', text: '确认鸭肉贴骨处无血色，加入枸杞和盐煮 5 分钟，关火后撒葱花。', heat: '中火', timerSeconds: 300 },
    ],
    tips: ['老鸭肉质较紧，需炖到最厚处至少 75°C且贴骨无血水；山药汁液可能刺激皮肤，去皮时可戴手套。'],
  },
  {
    id: 'steamed-mushroom-chicken',
    title: '香菇滑鸡',
    subtitle: '豉香菇鲜，鸡腿蒸得嫩滑多汁',
    emoji: '🍄',
    colors: ['#b39470', '#6a5949'],
    minutes: 40,
    difficulty: 2,
    rating: 4.8,
    calories: 396,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '去骨鸡腿肉', amount: 600, unit: '克', role: 'core' },
      { name: '鲜香菇', amount: 180, unit: '克', role: 'core', substitutes: ['泡发干香菇'] },
      { name: '姜', amount: 15, unit: '克', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '豆豉', amount: 1, unit: '汤匙', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '蚝油', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '淀粉', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切配食材', text: '鸡腿肉切约 3 厘米块，鲜香菇去蒂切厚片，姜切丝，豆豉粗略切碎。', heat: '不开火' },
      { title: '抓匀腌制', text: '鸡块加入生抽、蚝油、黄酒、淀粉和香油抓至发黏，再拌入香菇、姜丝和豆豉，冷藏腌 15 分钟。', heat: '不开火', timerSeconds: 900 },
      { title: '平铺蒸制', text: '鸡块和香菇在浅盘中铺成一层，蒸锅水开后上锅，加盖大火蒸 12 至 15 分钟。', heat: '大火', timerSeconds: 900 },
      { title: '测温出锅', text: '检查最厚鸡块中心达到至少 75°C且完全不透明，如不足继续蒸；熟透后拌匀盘中汁水并撒葱花。', heat: '大火' },
    ],
    tips: ['鸡块不要堆得过厚，否则受热不均；腌生鸡的容器和筷子应清洗消毒，不能直接接触熟食。'],
  },
  {
    id: 'chestnut-braised-chicken',
    title: '板栗烧鸡',
    subtitle: '板栗粉糯甘甜，鸡块酱香入味',
    emoji: '🌰',
    colors: ['#c58b55', '#74503b'],
    minutes: 60,
    difficulty: 2,
    rating: 4.9,
    calories: 548,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡块', amount: 800, unit: '克', role: 'core' },
      { name: '去皮板栗', amount: 300, unit: '克', role: 'core' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '八角', amount: 2, unit: '个', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '生抽', amount: 2.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '冰糖', amount: 15, unit: '克', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯鸡煮栗', text: '鸡块冷水下锅煮开 2 分钟后捞出洗净；板栗另入沸水煮 5 分钟，捞出沥干。', heat: '大火', timerSeconds: 300 },
      { title: '煸香上色', text: '炒锅放油，鸡块中火煸至表面微黄，加入姜、蒜、八角和冰糖翻炒至糖融化。', heat: '中火', timerSeconds: 420 },
      { title: '同锅焖烧', text: '加入板栗、生抽、老抽、黄酒和约 600 毫升热水，煮开后加盖小火焖 30 分钟。', heat: '小火', timerSeconds: 1800 },
      { title: '检查收汁', text: '确认鸡肉贴骨处熟透、板栗中心软糯，开盖转大火收汁，轻轻翻动防止板栗碎裂，撒葱花。', heat: '大火', timerSeconds: 240 },
    ],
    tips: ['鸡块最厚处必须达到至少 75°C；板栗要煮至中心软透，整颗板栗不宜直接给幼儿食用，以防噎食。'],
  },
  {
    id: 'curry-chicken-pieces',
    title: '咖喱鸡块',
    subtitle: '咖喱温香浓滑，鸡肉土豆饱满',
    emoji: '🍛',
    colors: ['#e0b550', '#8c6438'],
    minutes: 45,
    difficulty: 2,
    rating: 4.8,
    calories: 566,
    servings: 4,
    vegetarian: false,
    tastes: ['浓郁', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '去骨鸡腿肉', amount: 700, unit: '克', role: 'core' },
      { name: '土豆', amount: 400, unit: '克', role: 'core' },
      { name: '胡萝卜', amount: 180, unit: '克', role: 'support' },
      { name: '洋葱', amount: 200, unit: '克', role: 'support' },
      { name: '咖喱块', amount: 90, unit: '克', role: 'seasoning', substitutes: ['咖喱粉'] },
      { name: '椰浆', amount: 150, unit: '毫升', role: 'seasoning', substitutes: ['牛奶'] },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切成均匀块', text: '鸡腿肉、土豆和胡萝卜切成约 3 厘米块，洋葱切片；土豆用清水冲去表面淀粉。', heat: '不开火' },
      { title: '炒鸡和洋葱', text: '炒锅放油，先把鸡块中火炒至各面变色，再加入洋葱炒软出香。', heat: '中火', timerSeconds: 420 },
      { title: '焖熟根茎', text: '放土豆、胡萝卜和约 550 毫升热水，煮开后加盖小火焖 18 分钟，直到鸡肉熟透、土豆可扎透。', heat: '小火', timerSeconds: 1080 },
      { title: '融化咖喱', text: '关火放入咖喱块搅至完全融化，再开小火加入椰浆煮 3 分钟；尝味后少量补盐。', heat: '小火', timerSeconds: 180 },
    ],
    tips: ['鸡肉中心必须达到至少 75°C；咖喱加入后容易沉底焦糊，要保持小火并持续搅动，浓汁入口前充分晾温。'],
  },
  {
    id: 'scallion-oil-chicken',
    title: '葱油鸡',
    subtitle: '鸡肉嫩润，热葱油鲜香扑鼻',
    emoji: '🌿',
    colors: ['#d1bd70', '#668050'],
    minutes: 45,
    difficulty: 2,
    rating: 4.8,
    calories: 428,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '蒸锅 + 小锅',
    ingredients: [
      { name: '带骨鸡全腿', amount: 750, unit: '克', role: 'core' },
      { name: '小葱', amount: 80, unit: '克', role: 'core' },
      { name: '姜', amount: 25, unit: '克', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 3, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '盐腌鸡腿', text: '鸡腿擦干，均匀抹盐，放姜片和一半葱段，盖好后冷藏腌 15 分钟。', heat: '不开火', timerSeconds: 900 },
      { title: '蒸熟静置', text: '蒸锅水开后放入鸡腿，大火蒸 22 至 25 分钟；最厚处达到至少 75°C且关节无血水后取出静置 5 分钟。', heat: '大火', timerSeconds: 1500 },
      { title: '调葱姜汁', text: '剩余小葱切末，姜磨成蓉，与生抽、糖和 2 汤匙蒸鸡原汁拌匀，铺在斩好的鸡块上。', heat: '不开火' },
      { title: '泼油增香', text: '小锅把食用油加热至微微起纹，离火后均匀浇在葱姜末上，静置 1 分钟再上桌。', heat: '中火', timerSeconds: 60 },
    ],
    tips: ['蒸制时间需随鸡腿大小调整，必须用熟度而非时间判断；热油浇葱时会飞溅，应使用深盘并保持脸部远离。'],
  },
  {
    id: 'white-cut-chicken',
    title: '白切鸡',
    subtitle: '鸡皮爽滑，鸡肉原味鲜嫩',
    emoji: '🍗',
    colors: ['#e0ca8e', '#9a7e57'],
    minutes: 65,
    difficulty: 3,
    rating: 4.9,
    calories: 412,
    servings: 5,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '深汤锅 · 1 口锅',
    ingredients: [
      { name: '三黄鸡', amount: 1, unit: '只（约 1.3 千克）', role: 'core' },
      { name: '姜', amount: 40, unit: '克', role: 'support' },
      { name: '小葱', amount: 80, unit: '克', role: 'support' },
      { name: '黄酒', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '清理整鸡', text: '确认鸡腹腔已清理干净，冲去血水并擦干；姜拍裂，小葱打结。处理生鸡后立刻清洗水槽、刀板和双手。', heat: '不开火' },
      { title: '浸入热汤', text: '深锅加入足以没过整鸡的水、半量姜葱和黄酒，大火烧开；提住鸡颈在热汤中提浸三次，再将鸡完全放入。', heat: '大火' },
      { title: '微沸煮透', text: '汤重新接近沸腾后转小火，保持轻微冒泡煮约 30 分钟，关火加盖焖 15 分钟；测量大腿最厚处至少 75°C。', heat: '小火', timerSeconds: 1800 },
      { title: '斩件配蘸汁', text: '鸡捞出沥干并静置 10 分钟，确认关节无血水后用干净刀板斩件；剩余姜葱切末，加生抽、香油和少量热鸡汤调成蘸汁。', heat: '不开火', timerSeconds: 600 },
    ],
    tips: ['家庭制作白切鸡必须以食品温度计达到至少 75°C为准，不追求带血或粉红骨髓；煮熟后只能用干净刀板和刀具斩切。'],
  },
  {
    id: 'sauce-fried-chicken-dices',
    title: '酱爆鸡丁',
    subtitle: '甜酱浓香，鸡丁嫩滑黄瓜爽脆',
    emoji: '🥢',
    colors: ['#b4744f', '#6f493c'],
    minutes: 25,
    difficulty: 2,
    rating: 4.8,
    calories: 388,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鸡胸肉', amount: 450, unit: '克', role: 'core' },
      { name: '黄瓜', amount: 200, unit: '克', role: 'support' },
      { name: '甜面酱', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '黄豆酱', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌鸡切瓜', text: '鸡胸切约 1.5 厘米丁，加黄酒、生抽和淀粉抓匀，冷藏腌 10 分钟；黄瓜去瓤后切同样大小的丁。', heat: '不开火', timerSeconds: 600 },
      { title: '滑炒鸡丁', text: '炒锅烧热放一半油，鸡丁单层下锅，中火快速划散，炒至中心完全不透明后盛出。', heat: '中火', timerSeconds: 240 },
      { title: '小火炒酱', text: '原锅补油，放甜面酱、黄豆酱、糖和 2 汤匙清水，小火不停搅炒至酱香浓郁、表面油亮。', heat: '小火', timerSeconds: 90 },
      { title: '回锅裹味', text: '倒回熟鸡丁大火翻炒至酱汁均匀包裹，最后加入黄瓜丁翻炒约 30 秒出锅。', heat: '大火', timerSeconds: 60 },
    ],
    tips: ['鸡丁中心必须达到至少 75°C；甜面酱含糖易焦，应以小火炒香，若锅底发干可补少量清水。'],
  },
  {
    id: 'teriyaki-chicken-thighs',
    title: '照烧鸡腿',
    subtitle: '鸡皮焦香，甜咸照烧汁亮润',
    emoji: '🍗',
    colors: ['#c17d4d', '#754634'],
    minutes: 35,
    difficulty: 2,
    rating: 4.9,
    calories: 498,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '平底锅 · 1 口锅',
    ingredients: [
      { name: '去骨带皮鸡腿', amount: 650, unit: '克', role: 'core' },
      { name: '姜', amount: 10, unit: '克', role: 'support' },
      { name: '生抽', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '味醂', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['米酒加糖'] },
      { name: '蜂蜜', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['白糖'] },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '整平鸡腿', text: '鸡腿肉较厚处浅划两刀，不要切断；用厨房纸吸干表面水分。生抽、味醂、蜂蜜、黄酒和姜末调匀。', heat: '不开火' },
      { title: '鸡皮朝下煎', text: '平底锅薄薄抹油，鸡皮朝下放入，中小火压平煎约 7 分钟，倒去过多油脂后翻面。', heat: '小火', timerSeconds: 420 },
      { title: '焖至熟透', text: '另一面煎 3 分钟，加入 4 汤匙清水并加盖小火焖 4 分钟，确认最厚处达到至少 75°C。', heat: '小火', timerSeconds: 420 },
      { title: '加汁照烧', text: '倒入调好的照烧汁，中火反复翻面，让酱汁煮至浓亮并包裹鸡腿；静置 3 分钟后切条。', heat: '中火', timerSeconds: 150 },
    ],
    tips: ['含蜂蜜的照烧汁容易焦，必须在鸡腿熟透后再收汁；切开最厚处应完全不透明且无粉红肉汁。'],
  },
  {
    id: 'potato-braised-chicken',
    title: '土豆烧鸡',
    subtitle: '土豆吸足肉汁，鸡块家常醇香',
    emoji: '🥔',
    colors: ['#c99b59', '#776040'],
    minutes: 50,
    difficulty: 2,
    rating: 4.8,
    calories: 516,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '带骨鸡块', amount: 800, unit: '克', role: 'core' },
      { name: '土豆', amount: 600, unit: '克', role: 'core' },
      { name: '胡萝卜', amount: 150, unit: '克', role: 'support' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '八角', amount: 2, unit: '个', role: 'support' },
      { name: '生抽', amount: 2.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯鸡切菜', text: '鸡块冷水下锅煮开 2 分钟，捞出洗净沥干；土豆和胡萝卜切成大小接近的滚刀块。', heat: '大火', timerSeconds: 120 },
      { title: '煸炒鸡块', text: '锅中放油，加入鸡块中火炒至表面微黄，再加入姜、蒜和八角炒香。', heat: '中火', timerSeconds: 420 },
      { title: '加料焖烧', text: '加入生抽、老抽、黄酒、糖和约 550 毫升热水，煮开后加盖小火焖 15 分钟，再放土豆和胡萝卜焖 15 分钟。', heat: '小火', timerSeconds: 1800 },
      { title: '熟透收汁', text: '确认鸡块贴骨无血水、土豆可轻松扎透后，开盖转大火收汁，轻推食材防止土豆碎散。', heat: '大火', timerSeconds: 240 },
    ],
    tips: ['土豆发绿或严重发芽时不可食用；鸡块最厚处需达到至少 75°C，不能只凭土豆是否软烂判断鸡肉熟度。'],
  },
  {
    id: 'winter-melon-old-duck-soup',
    title: '冬瓜老鸭汤',
    subtitle: '冬瓜清润，老鸭汤鲜而不腻',
    emoji: '🍲',
    colors: ['#b8c99c', '#68745c'],
    minutes: 115,
    difficulty: 2,
    rating: 4.8,
    calories: 398,
    servings: 5,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '老鸭块', amount: 1.1, unit: '千克', role: 'core' },
      { name: '冬瓜', amount: 700, unit: '克', role: 'core' },
      { name: '薏米', amount: 50, unit: '克', role: 'support' },
      { name: '姜', amount: 8, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '泡米焯鸭', text: '薏米洗净浸泡 30 分钟；鸭块冷水下锅，加黄酒和三片姜，煮开 3 分钟后捞出温水洗净。', heat: '大火', timerSeconds: 1800 },
      { title: '先炖鸭肉', text: '鸭块、薏米、剩余姜片和约 2.2 升热水放入汤锅，大火煮开撇沫，转小火炖 65 分钟。', heat: '小火', timerSeconds: 3900 },
      { title: '加入冬瓜', text: '冬瓜去皮去瓤切大块，放入鸭汤继续小火煮 20 分钟，至冬瓜半透明且保持形状。', heat: '小火', timerSeconds: 1200 },
      { title: '确认调味', text: '检查鸭肉最厚处熟透、贴骨无血水，加入盐煮 3 分钟，关火后撒葱花。', heat: '中火', timerSeconds: 180 },
    ],
    tips: ['老鸭必须炖至至少 75°C且贴骨无血水；冬瓜后放可避免煮散，热汤端取和入口时注意蒸汽与烫伤。'],
  },
  {
    id: 'pickled-radish-old-duck-soup',
    title: '酸萝卜老鸭汤',
    subtitle: '酸香开胃，鸭汤醇厚不腻',
    emoji: '🦆',
    colors: ['#c9bb8d', '#746957'],
    minutes: 120,
    difficulty: 2,
    rating: 4.9,
    calories: 416,
    servings: 5,
    vegetarian: false,
    tastes: ['酸爽', '咸鲜'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '老鸭块', amount: 1.1, unit: '千克', role: 'core' },
      { name: '酸萝卜', amount: 350, unit: '克', role: 'core' },
      { name: '白萝卜', amount: 350, unit: '克', role: 'support' },
      { name: '泡姜', amount: 30, unit: '克', role: 'support', substitutes: ['生姜'] },
      { name: '花椒', amount: 0.5, unit: '茶匙', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯鸭洗萝卜', text: '鸭块冷水下锅，加黄酒煮开 3 分钟后捞出洗净；酸萝卜快速冲去表面过多盐分并切块，白萝卜切滚刀块。', heat: '大火', timerSeconds: 180 },
      { title: '炒香酸萝卜', text: '汤锅不放油，加入酸萝卜、泡姜和花椒，中火翻炒约 2 分钟，炒出酸香。', heat: '中火', timerSeconds: 120 },
      { title: '小火炖鸭', text: '放入鸭块和约 2.2 升热水，大火煮开撇沫，转小火炖 70 分钟。', heat: '小火', timerSeconds: 4200 },
      { title: '加白萝卜完成', text: '加入白萝卜再炖 25 分钟，确认鸭肉贴骨处熟透；先尝汤味，仅在确有需要时补少量盐，撒葱花。', heat: '小火', timerSeconds: 1500 },
    ],
    tips: ['酸萝卜和泡姜含盐较高，应先尝味再加盐；鸭肉最厚处必须达到至少 75°C，汤中骨块需防止老人儿童误吞。'],
  },
]
