import type { Recipe } from './types'

export const recipesBatchC: Recipe[] = [
  {
    id: 'three-earthly-treasures',
    title: '地三鲜',
    subtitle: '茄子绵软，土豆焦香，青椒爽口',
    emoji: '🍆',
    colors: ['#d9b36c', '#788d52'],
    minutes: 35,
    difficulty: 2,
    rating: 4.8,
    calories: 326,
    servings: 3,
    vegetarian: true,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '长茄子', amount: 300, unit: '克', role: 'core' },
      { name: '土豆', amount: 300, unit: '克', role: 'core' },
      { name: '青椒', amount: 150, unit: '克', role: 'core' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 4, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切配调汁', text: '土豆去皮切滚刀块，泡水洗去表面淀粉后擦干；茄子和青椒切相近大小的块。生抽、老抽、糖、淀粉与 80 毫升清水调匀。', heat: '不开火' },
      { title: '煎熟土豆', text: '锅中放一半食用油，土豆块平码入锅，中小火不时翻面，煎到各面金黄且筷子可以扎透后盛出。', heat: '小火', timerSeconds: 600 },
      { title: '炒软茄椒', text: '锅中补入余油，放茄子中火翻炒至明显缩小变软，再加入青椒炒约 1 分钟。', heat: '中火', timerSeconds: 360 },
      { title: '合炒收汁', text: '加入蒜末炒香，倒回土豆并淋入调味汁，大火翻炒至薄芡均匀包裹食材，按口味补盐后出锅。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['土豆和茄子切得大小接近更容易同时入味；茄子炒软后再放青椒，可保留青椒的清脆和颜色。'],
  },
  {
    id: 'dry-fried-green-beans',
    title: '干煸四季豆',
    subtitle: '表皮起皱，肉末芽菜香辣下饭',
    emoji: '🌶️',
    colors: ['#8fa85b', '#a34c38'],
    minutes: 30,
    difficulty: 2,
    rating: 4.8,
    calories: 284,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '四季豆', amount: 500, unit: '克', role: 'core' },
      { name: '猪肉末', amount: 80, unit: '克', role: 'support' },
      { name: '芽菜', amount: 30, unit: '克', role: 'support', substitutes: ['梅干菜'] },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 6, unit: '个', role: 'support' },
      { name: '花椒', amount: 1, unit: '茶匙', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 3, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '择洗擦干', text: '四季豆掐去两端和老筋，洗净后彻底擦干，折成约 6 厘米长的段；芽菜冲去多余盐分并挤干。', heat: '不开火' },
      { title: '煸透豆角', text: '锅中放油，四季豆单层下锅，中火反复翻动，煸到表皮大面积起皱、颜色转深且内部完全变软后盛出。', heat: '中火', timerSeconds: 720, tip: '掰开最粗的一段检查，中心应熟透、没有生硬感。' },
      { title: '炒香肉末', text: '原锅放猪肉末炒散，继续翻炒至肉末完全变色并略微焦香，再加入蒜末、芽菜、干辣椒和花椒炒出香味。', heat: '中火', timerSeconds: 240 },
      { title: '回锅入味', text: '倒回四季豆，加生抽、糖和盐大火翻炒 1 至 2 分钟，让调味料均匀附着后出锅。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['四季豆含有需充分加热破坏的天然成分，必须煸到里外完全熟透、没有豆腥味和生脆口感后再食用，不能只看表皮起皱。'],
  },
  {
    id: 'hand-torn-cabbage',
    title: '手撕包菜',
    subtitle: '锅气十足，脆嫩酸辣不出水',
    emoji: '🥬',
    colors: ['#b6c979', '#6f873f'],
    minutes: 15,
    difficulty: 1,
    rating: 4.7,
    calories: 142,
    servings: 3,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '圆白菜', amount: 500, unit: '克', role: 'core', substitutes: ['牛心菜'] },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 4, unit: '个', role: 'support' },
      { name: '花椒', amount: 0.5, unit: '茶匙', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['陈醋'] },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '手撕菜叶', text: '圆白菜去硬芯，叶片用手撕成大块，较厚的叶梗另放；洗净后充分沥干表面水分。', heat: '不开火' },
      { title: '爆香料头', text: '炒锅充分烧热后放油，转中火加入花椒、干辣椒段和蒜片，快速炒香但不要炒焦。', heat: '中火', timerSeconds: 30 },
      { title: '先炒叶梗', text: '转大火放入较厚叶梗，快速翻炒约 40 秒，再加入其余菜叶继续翻炒至叶片刚刚变软。', heat: '大火', timerSeconds: 100 },
      { title: '沿锅调味', text: '沿锅边淋入生抽和香醋，撒糖和盐，快速翻匀约 20 秒立即出锅。', heat: '大火', timerSeconds: 20 },
    ],
    tips: ['菜叶一定要沥干，锅也要充分预热；大火短炒才能减少出水并保留脆嫩口感。'],
  },
  {
    id: 'vinegar-cabbage',
    title: '醋溜白菜',
    subtitle: '白菜帮爽脆，酸香汁亮开胃',
    emoji: '🥬',
    colors: ['#d8dc9b', '#96a24e'],
    minutes: 20,
    difficulty: 1,
    rating: 4.7,
    calories: 128,
    servings: 3,
    vegetarian: true,
    tastes: ['酸爽', '酸甜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '大白菜', amount: 600, unit: '克', role: 'core' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 3, unit: '个', role: 'support' },
      { name: '香醋', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['陈醋'] },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 2, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '帮叶分切', text: '白菜洗净沥干，菜帮用刀斜片成薄片，菜叶撕成大块并与菜帮分开放置。', heat: '不开火' },
      { title: '调好酸汁', text: '香醋、生抽、糖、淀粉、盐和 3 汤匙清水搅匀，静置前再搅一次防止淀粉沉底。', heat: '不开火' },
      { title: '炒脆菜帮', text: '锅烧热放油，炒香蒜片和干辣椒，先下白菜帮大火翻炒约 2 分钟至边缘略透。', heat: '大火', timerSeconds: 120 },
      { title: '下叶裹汁', text: '加入白菜叶炒至刚变软，倒入酸汁快速翻炒，芡汁变亮并均匀挂在白菜上后立刻出锅。', heat: '大火', timerSeconds: 90 },
    ],
    tips: ['醋汁最后下锅且不要久炒，既能保留醋香，也能避免白菜叶过软、出水过多。'],
  },
  {
    id: 'oyster-sauce-lettuce',
    title: '蚝油生菜',
    subtitle: '叶片爽脆，蒜香蚝汁鲜亮',
    emoji: '🥬',
    colors: ['#91c270', '#4e8544'],
    minutes: 15,
    difficulty: 1,
    rating: 4.8,
    calories: 116,
    servings: 2,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 + 炒锅',
    ingredients: [
      { name: '生菜', amount: 400, unit: '克', role: 'core' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '蚝油', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['素蚝油'] },
      { name: '生抽', amount: 0.5, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '洗菜调汁', text: '生菜逐片洗净并沥水；蚝油、生抽、糖、淀粉和 4 汤匙清水搅匀成料汁。', heat: '不开火' },
      { title: '快速焯菜', text: '汤锅水大火烧开，加几滴食用油，分批放入生菜焯 15 至 20 秒，叶片变翠绿后立即捞出。', heat: '大火', timerSeconds: 40 },
      { title: '沥水装盘', text: '生菜轻轻抖去多余水分，整齐码入盘中，不要挤压叶片。', heat: '不开火' },
      { title: '熬汁浇菜', text: '炒锅放油，小火炒香蒜末，倒入料汁搅拌至微稠透亮，均匀浇在生菜上。', heat: '小火', timerSeconds: 90 },
    ],
    tips: ['生菜要分批短时间焯烫，水量不足或一次放得太多会令水温骤降，叶片容易发黄变软。'],
  },
  {
    id: 'garlic-youmai-lettuce',
    title: '蒜蓉油麦菜',
    subtitle: '蒜香清新，菜梗爽脆叶片嫩',
    emoji: '🥬',
    colors: ['#91bf71', '#3f7c45'],
    minutes: 12,
    difficulty: 1,
    rating: 4.7,
    calories: 104,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '油麦菜', amount: 400, unit: '克', role: 'core' },
      { name: '大蒜', amount: 6, unit: '瓣', role: 'support' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切菜分段', text: '油麦菜洗净后充分沥干，切成约 7 厘米长的段，将较厚菜梗与叶片分开放置；大蒜切末。', heat: '不开火' },
      { title: '煸香蒜末', text: '炒锅烧热放油，下约三分之二蒜末，小火炒至香味明显但颜色仍浅。', heat: '小火', timerSeconds: 30 },
      { title: '先梗后叶', text: '转大火先放菜梗翻炒 30 秒，再放叶片快速翻炒至叶片塌软、梗部仍脆。', heat: '大火', timerSeconds: 80 },
      { title: '调味出锅', text: '加入盐、糖和剩余蒜末，快速翻匀约 15 秒，锅内尚无明显菜汁时立即出锅。', heat: '大火', timerSeconds: 15 },
    ],
    tips: ['洗好的油麦菜要尽量甩干，蒜末分两次加入，既有熟蒜香也保留少许清新的蒜味。'],
  },
  {
    id: 'stir-fried-baby-bok-choy',
    title: '清炒小白菜',
    subtitle: '翠绿脆嫩，简单调味吃本味',
    emoji: '🥬',
    colors: ['#a7ca77', '#568449'],
    minutes: 12,
    difficulty: 1,
    rating: 4.6,
    calories: 92,
    servings: 2,
    vegetarian: true,
    tastes: ['清淡', '咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '小白菜', amount: 450, unit: '克', role: 'core', substitutes: ['上海青'] },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '洗净沥水', text: '小白菜掰开叶片，重点冲洗根部泥沙；较大的菜纵向剖半，洗净后充分沥水。', heat: '不开火' },
      { title: '蒜片炝锅', text: '炒锅大火烧热后放油，加入蒜片迅速炒香，避免蒜片发黑。', heat: '大火', timerSeconds: 20 },
      { title: '先炒菜梗', text: '先把菜梗较厚的部分下锅，大火翻炒约 40 秒，再加入叶片继续翻炒。', heat: '大火', timerSeconds: 80 },
      { title: '轻调本味', text: '叶片刚变软时撒盐和少量糖，翻炒均匀后立即关火装盘。', heat: '大火', timerSeconds: 20 },
    ],
    tips: ['盐要临出锅再放，过早加盐会让小白菜迅速出水，影响脆嫩口感。'],
  },
  {
    id: 'superior-broth-baby-cabbage',
    title: '上汤娃娃菜',
    subtitle: '菜心清甜，金汤鲜润暖胃',
    emoji: '🍲',
    colors: ['#e2d486', '#9a844f'],
    minutes: 25,
    difficulty: 2,
    rating: 4.8,
    calories: 188,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '娃娃菜', amount: 500, unit: '克', role: 'core' },
      { name: '皮蛋', amount: 1, unit: '个', role: 'support' },
      { name: '火腿', amount: 40, unit: '克', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '枸杞', amount: 8, unit: '克', role: 'support' },
      { name: '高汤', amount: 600, unit: '毫升', role: 'seasoning', substitutes: ['清水'] },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '备好配料', text: '娃娃菜纵向切成八瓣，冲净根部后沥水；皮蛋切小块，火腿切丁，枸杞冲洗干净。', heat: '不开火' },
      { title: '煎香蒜蛋', text: '锅中放油，小火把整瓣大蒜煎至表面微黄，加入皮蛋块翻炒至边缘略起泡。', heat: '小火', timerSeconds: 120 },
      { title: '煮成鲜汤', text: '倒入高汤，加入火腿丁，大火煮开后转中火煮约 4 分钟，让汤色略白、鲜味融合。', heat: '中火', timerSeconds: 240 },
      { title: '煨熟娃娃菜', text: '放入娃娃菜和枸杞，加盖中火煮至菜梗变软但不散，尝味后少量加盐，连汤盛出。', heat: '中火', timerSeconds: 360 },
    ],
    tips: ['火腿和高汤本身有咸味，务必在最后尝味后再决定是否加盐，以免汤底过咸。'],
  },
  {
    id: 'tiger-skin-peppers',
    title: '虎皮青椒',
    subtitle: '椒皮焦香起皱，酸甜微辣入味',
    emoji: '🫑',
    colors: ['#739c50', '#b16b3e'],
    minutes: 20,
    difficulty: 1,
    rating: 4.8,
    calories: 156,
    servings: 2,
    vegetarian: true,
    tastes: ['微辣', '酸甜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '薄皮青椒', amount: 400, unit: '克', role: 'core' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '豆豉', amount: 1, unit: '汤匙', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理青椒', text: '青椒洗净擦干，去蒂后根据嗜辣程度去除部分籽和白筋；较长的青椒切成两段。', heat: '不开火' },
      { title: '干煸虎皮', text: '炒锅不放油，中火放入青椒，用锅铲不时按压和翻面，煸到表面大面积焦斑起皱、椒肉变软。', heat: '中火', timerSeconds: 480 },
      { title: '炒香豆豉', text: '把青椒推到锅边，加入食用油、蒜末和豆豉，小火炒出香味后与青椒翻匀。', heat: '小火', timerSeconds: 60 },
      { title: '焖汁入味', text: '淋入生抽、香醋、糖和 3 汤匙清水，中火翻动并略焖，汤汁收浓后出锅。', heat: '中火', timerSeconds: 120 },
    ],
    tips: ['青椒洗后必须擦干再入热锅，避免水珠飞溅；怕辣可彻底去除白筋并选用不辣的薄皮椒。'],
  },
  {
    id: 'fish-fragrant-eggplant',
    title: '鱼香茄子',
    subtitle: '无鱼也有鱼香，酸甜微辣浓郁',
    emoji: '🍆',
    colors: ['#9f6c8d', '#b64c40'],
    minutes: 30,
    difficulty: 2,
    rating: 4.9,
    calories: 268,
    servings: 3,
    vegetarian: true,
    tastes: ['酸甜', '微辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '长茄子', amount: 500, unit: '克', role: 'core' },
      { name: '泡椒', amount: 1.5, unit: '汤匙', role: 'support', substitutes: ['郫县豆瓣酱'] },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '姜', amount: 10, unit: '克', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '盐渍茄条', text: '茄子切成粗条，撒盐抓匀静置 10 分钟，挤去析出的水分并用厨房纸擦干。', heat: '不开火', timerSeconds: 600 },
      { title: '煎软茄子', text: '锅中放油，茄条单层下锅，中火煎炒至表面微黄、内部柔软后盛出。', heat: '中火', timerSeconds: 480 },
      { title: '炒出鱼香', text: '原锅小火炒香泡椒、姜末和蒜末；将生抽、香醋、糖、淀粉与 100 毫升清水调匀后倒入锅中煮开。', heat: '小火', timerSeconds: 90 },
      { title: '回锅收汁', text: '放回茄条，中火轻轻翻动至鱼香汁浓稠均匀，撒葱花后关火装盘。', heat: '中火', timerSeconds: 120 },
    ],
    tips: ['这道菜的鱼香来自泡椒、葱姜蒜、糖和醋的组合，并不需要加鱼；盐渍茄子可减少吸油。'],
  },
  {
    id: 'red-braised-eggplant',
    title: '红烧茄子',
    subtitle: '酱色红亮，茄肉软糯又下饭',
    emoji: '🍆',
    colors: ['#a26b80', '#9d513d'],
    minutes: 30,
    difficulty: 2,
    rating: 4.8,
    calories: 252,
    servings: 3,
    vegetarian: true,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '长茄子', amount: 500, unit: '克', role: 'core' },
      { name: '青椒', amount: 100, unit: '克', role: 'support' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '盐渍备料', text: '茄子切滚刀块，加盐拌匀静置 10 分钟后挤干；青椒切块，生抽、老抽、糖、淀粉和 120 毫升清水调成碗汁。', heat: '不开火', timerSeconds: 600 },
      { title: '煎软茄块', text: '锅中放油，茄块中火煎炒至四周微黄、体积缩小并变软。', heat: '中火', timerSeconds: 480 },
      { title: '加入椒蒜', text: '放入青椒块和一半蒜末，大火翻炒约 1 分钟，让青椒断生并炒出蒜香。', heat: '大火', timerSeconds: 60 },
      { title: '焖烧收汁', text: '倒入碗汁煮开，转中火焖 2 分钟，开盖轻推至汁浓，撒剩余蒜末后出锅。', heat: '中火', timerSeconds: 180 },
    ],
    tips: ['茄子盐渍后要挤干再煎，既能少吸油，也更容易快速煎软；翻动时用锅铲轻推以免茄块碎散。'],
  },
  {
    id: 'chilled-eggplant-salad',
    title: '凉拌茄子',
    subtitle: '蒸得软嫩，蒜醋汁清爽入味',
    emoji: '🍆',
    colors: ['#9d799b', '#66845a'],
    minutes: 25,
    difficulty: 1,
    rating: 4.7,
    calories: 118,
    servings: 3,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '长茄子', amount: 500, unit: '克', role: 'core' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '香菜', amount: 15, unit: '克', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '辣椒油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切段上锅', text: '茄子洗净切成约 8 厘米长的段，再纵向剖半，切面朝上摆入蒸盘。', heat: '不开火' },
      { title: '蒸熟放凉', text: '蒸锅水烧开后放入茄子，大火蒸至筷子可以轻松穿透，取出自然晾至温热。', heat: '大火', timerSeconds: 720 },
      { title: '调蒜醋汁', text: '蒜末、生抽、香醋、辣椒油、糖和香油充分搅匀，让糖完全溶化。', heat: '不开火' },
      { title: '撕条拌匀', text: '将温热茄子顺纤维撕成粗条，淋入蒜醋汁并轻轻拌匀，最后撒香菜。', heat: '不开火' },
    ],
    tips: ['茄子蒸好后盘中若有很多水要先倒掉，再拌调味汁，避免味道被稀释。'],
  },
  {
    id: 'sesame-spinach',
    title: '麻酱菠菜',
    subtitle: '菠菜鲜嫩，芝麻酱醇香顺滑',
    emoji: '🥬',
    colors: ['#5f9256', '#aa855e'],
    minutes: 15,
    difficulty: 1,
    rating: 4.7,
    calories: 184,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '浓郁'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '菠菜', amount: 500, unit: '克', role: 'core' },
      { name: '芝麻酱', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '熟白芝麻', amount: 1, unit: '茶匙', role: 'support' },
    ],
    steps: [
      { title: '洗净菠菜', text: '菠菜切去老根，逐棵冲净根部泥沙；较粗的茎叶分开，沥干备用。', heat: '不开火' },
      { title: '焯熟过凉', text: '锅中水大火烧开，先下菠菜梗 20 秒，再放叶片焯约 30 秒，全部变翠绿后捞入凉开水。', heat: '大火', timerSeconds: 50 },
      { title: '调顺麻酱', text: '芝麻酱分次加入 2 至 3 汤匙温水，朝一个方向搅至顺滑，再加入蒜末、生抽、香醋、糖和香油。', heat: '不开火' },
      { title: '挤水拌味', text: '菠菜轻轻挤去多余水分，切成便于入口的段，装盘后淋麻酱汁并撒熟白芝麻。', heat: '不开火' },
    ],
    tips: ['焯菠菜的水要保持沸腾，焯好后立即过凉并挤水，可保留颜色且不会冲淡麻酱。'],
  },
  {
    id: 'black-fungus-salad',
    title: '凉拌木耳',
    subtitle: '木耳爽脆，酸辣蒜香开胃',
    emoji: '🥗',
    colors: ['#5b5148', '#a34f43'],
    minutes: 90,
    difficulty: 1,
    rating: 4.7,
    calories: 126,
    servings: 3,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '干黑木耳', amount: 25, unit: '克', role: 'core' },
      { name: '洋葱', amount: 80, unit: '克', role: 'support' },
      { name: '红菜椒', amount: 50, unit: '克', role: 'support' },
      { name: '香菜', amount: 15, unit: '克', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '辣椒油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '冷水泡发', text: '干木耳用足量冷水泡约 1 小时至完全舒展，剪去硬根，逐朵搓洗干净并撕成小朵。', heat: '不开火', timerSeconds: 3600 },
      { title: '沸水煮熟', text: '锅中水大火烧开，放入木耳保持沸腾煮 3 分钟，捞出后用凉开水降温并充分沥干。', heat: '大火', timerSeconds: 180 },
      { title: '调制酸辣汁', text: '蒜末、生抽、香醋、辣椒油、糖和香油搅匀；洋葱、红菜椒切细丝，香菜切段。', heat: '不开火' },
      { title: '拌匀入味', text: '木耳、洋葱丝和红椒丝放入大碗，淋入料汁充分拌匀，最后加入香菜即可。', heat: '不开火' },
    ],
    tips: ['木耳宜用冷水在阴凉处或冰箱中泡发，泡好后尽快煮熟食用；不要把泡发木耳长时间放在室温下或隔夜存放。'],
  },
  {
    id: 'smashed-cucumber',
    title: '拍黄瓜',
    subtitle: '清脆多汁，蒜醋香辣又解腻',
    emoji: '🥒',
    colors: ['#8fc66a', '#4f8f64'],
    minutes: 20,
    difficulty: 1,
    rating: 4.8,
    calories: 148,
    servings: 2,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '无需开火',
    ingredients: [
      { name: '黄瓜', amount: 400, unit: '克', role: 'core' },
      { name: '大蒜', amount: 5, unit: '瓣', role: 'support' },
      { name: '熟花生米', amount: 30, unit: '克', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '辣椒油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '拍裂黄瓜', text: '黄瓜洗净擦干，用刀面拍至自然裂开，再斜切成容易入口的块。', heat: '不开火' },
      { title: '盐腌沥水', text: '黄瓜加盐拌匀，静置 8 分钟后倒去析出的水分。', heat: '不开火', timerSeconds: 480 },
      { title: '调蒜醋汁', text: '蒜末、生抽、香醋、辣椒油、糖和香油搅拌至糖溶化。', heat: '不开火' },
      { title: '拌入花生', text: '料汁倒入黄瓜中充分拌匀，临上桌前加入熟花生米再拌两下。', heat: '不开火' },
    ],
    tips: ['花生米最后再放才能保持酥脆；黄瓜拍裂而不是整齐切片，更容易吸附蒜醋汁。'],
  },
  {
    id: 'kelp-salad',
    title: '凉拌海带丝',
    subtitle: '爽滑有嚼劲，酸辣清新不腥',
    emoji: '🌊',
    colors: ['#507d68', '#9b7255'],
    minutes: 20,
    difficulty: 1,
    rating: 4.7,
    calories: 108,
    servings: 3,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '泡发海带丝', amount: 350, unit: '克', role: 'core' },
      { name: '胡萝卜', amount: 60, unit: '克', role: 'support' },
      { name: '香菜', amount: 15, unit: '克', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '辣椒油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '洗净切短', text: '海带丝反复冲洗去除表面黏液和多余盐分，剪成约 8 厘米长的段；胡萝卜切细丝。', heat: '不开火' },
      { title: '煮熟海带', text: '锅中水大火烧开，海带丝下锅煮 5 分钟；最后 30 秒加入胡萝卜丝一同焯熟。', heat: '大火', timerSeconds: 300 },
      { title: '过凉沥干', text: '海带丝和胡萝卜捞入凉开水降温，再用漏勺充分沥干，避免料汁被稀释。', heat: '不开火' },
      { title: '加汁凉拌', text: '加入蒜末、生抽、香醋、辣椒油、糖、香油和香菜，抓拌均匀后静置 5 分钟再装盘。', heat: '不开火', timerSeconds: 300 },
    ],
    tips: ['不同厚度的海带熟化时间不同，煮后尝一根，应熟透且保留适度韧性；若仍硬韧可再煮几分钟。'],
  },
  {
    id: 'lotus-pond-stir-fry',
    title: '荷塘小炒',
    subtitle: '多种时蔬清脆，颜色清雅鲜亮',
    emoji: '🪷',
    colors: ['#b3cf9b', '#78908a'],
    minutes: 25,
    difficulty: 2,
    rating: 4.8,
    calories: 176,
    servings: 3,
    vegetarian: true,
    tastes: ['清淡', '咸鲜'],
    cookware: '汤锅 + 炒锅',
    ingredients: [
      { name: '莲藕', amount: 200, unit: '克', role: 'core' },
      { name: '荷兰豆', amount: 150, unit: '克', role: 'core' },
      { name: '泡发黑木耳', amount: 100, unit: '克', role: 'core' },
      { name: '荸荠', amount: 100, unit: '克', role: 'support', substitutes: ['山药'] },
      { name: '胡萝卜', amount: 80, unit: '克', role: 'support' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切配时蔬', text: '莲藕、荸荠和胡萝卜切薄片，莲藕泡入清水防变色；荷兰豆撕去老筋，木耳撕小朵。', heat: '不开火' },
      { title: '分批焯熟', text: '锅中水大火烧开，先放木耳、莲藕和胡萝卜煮 1 分钟，再加入荷兰豆和荸荠煮 30 秒，全部捞出沥干。', heat: '大火', timerSeconds: 90 },
      { title: '大火快炒', text: '炒锅烧热放油，爆香蒜片，倒入全部焯好时蔬大火快速翻炒约 1 分钟。', heat: '大火', timerSeconds: 60 },
      { title: '薄芡提亮', text: '盐、糖、淀粉与 3 汤匙清水调匀后淋入锅中，快速翻炒至食材表面微亮，立即出锅。', heat: '大火', timerSeconds: 30 },
    ],
    tips: ['木耳必须煮熟；其余蔬菜只需短暂焯烫，炒制也要迅速，才能兼顾安全与清脆口感。'],
  },
  {
    id: 'mushroom-bok-choy',
    title: '香菇青菜',
    subtitle: '香菇滑嫩鲜浓，青菜翠绿爽口',
    emoji: '🍄',
    colors: ['#7fa261', '#8b684b'],
    minutes: 25,
    difficulty: 2,
    rating: 4.8,
    calories: 168,
    servings: 3,
    vegetarian: true,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 + 炒锅',
    ingredients: [
      { name: '上海青', amount: 400, unit: '克', role: 'core', substitutes: ['小白菜'] },
      { name: '鲜香菇', amount: 200, unit: '克', role: 'core' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '素蚝油', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['生抽'] },
      { name: '生抽', amount: 0.5, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理菇菜', text: '上海青纵向剖半并洗净根部泥沙；香菇去硬蒂后切厚片。素蚝油、生抽、糖、淀粉与 100 毫升清水调匀。', heat: '不开火' },
      { title: '焯熟青菜', text: '水烧开后加几滴油，放入上海青焯 40 至 60 秒，菜梗断生后捞出沥水并码盘。', heat: '大火', timerSeconds: 60 },
      { title: '炒透香菇', text: '炒锅放油和蒜片，炒香后加入香菇，中火翻炒至香菇变软、边缘微黄且没有生味。', heat: '中火', timerSeconds: 300 },
      { title: '烧汁装盘', text: '倒入调味汁煮开，轻轻翻动至香菇裹上亮芡，将香菇和酱汁盛到青菜中间。', heat: '中火', timerSeconds: 120 },
    ],
    tips: ['鲜香菇要炒到完全变软且香气充分释放；青菜焯好后沥干，成菜的芡汁才不会被盘中水分冲淡。'],
  },
  {
    id: 'dry-pot-cauliflower',
    title: '干锅花菜',
    subtitle: '花菜脆嫩，五花肉香辣焦香',
    emoji: '🥦',
    colors: ['#c6bd72', '#a34f37'],
    minutes: 35,
    difficulty: 2,
    rating: 4.9,
    calories: 362,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '花菜', amount: 500, unit: '克', role: 'core' },
      { name: '五花肉', amount: 150, unit: '克', role: 'support' },
      { name: '青蒜', amount: 2, unit: '根', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '姜', amount: 10, unit: '克', role: 'support' },
      { name: '干辣椒', amount: 6, unit: '个', role: 'support' },
      { name: '郫县豆瓣酱', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '洗切花菜', text: '花菜拆成大小均匀的小朵，用淡盐水浸泡 10 分钟后冲净；五花肉切薄片，青蒜切段。', heat: '不开火', timerSeconds: 600 },
      { title: '焯水沥干', text: '锅中水烧开，放入花菜焯约 1 分钟，捞出充分沥水，花梗应刚断生并仍有脆度。', heat: '大火', timerSeconds: 60 },
      { title: '煸香五花肉', text: '炒锅放油和五花肉片，中火煸至肉片完全变色、边缘微卷并析出油脂，再加入姜蒜、干辣椒和豆瓣酱炒香。', heat: '中火', timerSeconds: 360 },
      { title: '干炒入味', text: '倒入花菜转大火翻炒，加生抽和糖炒至表面略有焦色、锅中无明显水汽，最后放青蒜炒匀。', heat: '大火', timerSeconds: 180 },
    ],
    tips: ['焯后的花菜一定要充分沥干再下锅，才能炒出干香；五花肉要炒至完全熟透、没有粉红色再加入蔬菜。'],
  },
  {
    id: 'homestyle-tofu',
    title: '家常豆腐',
    subtitle: '豆腐外香内嫩，咸鲜微辣下饭',
    emoji: '🧈',
    colors: ['#d9b96e', '#a3523f'],
    minutes: 35,
    difficulty: 2,
    rating: 4.9,
    calories: 348,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '微辣', '浓郁'],
    cookware: '平底锅 + 炒锅',
    ingredients: [
      { name: '北豆腐', amount: 500, unit: '克', role: 'core', substitutes: ['老豆腐'] },
      { name: '猪肉末', amount: 100, unit: '克', role: 'support' },
      { name: '泡发黑木耳', amount: 80, unit: '克', role: 'support' },
      { name: '青椒', amount: 100, unit: '克', role: 'support' },
      { name: '胡萝卜', amount: 60, unit: '克', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '姜', amount: 10, unit: '克', role: 'support' },
      { name: '郫县豆瓣酱', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切配食材', text: '豆腐切成约 1 厘米厚的三角片并吸干表面水分；木耳撕小朵，青椒和胡萝卜切片。', heat: '不开火' },
      { title: '煎香豆腐', text: '平底锅放一半食用油，豆腐单层排开，中火煎至两面金黄定形后盛出。', heat: '中火', timerSeconds: 480 },
      { title: '炒熟肉蔬', text: '炒锅放余油，将猪肉末炒散至完全变色且没有粉红色，加入姜蒜和豆瓣酱炒香，再放木耳、胡萝卜和青椒翻炒。', heat: '中火', timerSeconds: 300 },
      { title: '焖豆腐收汁', text: '加入生抽、糖和 200 毫升热水，放回豆腐加盖焖 4 分钟；淋入水淀粉，轻推至汤汁浓亮后出锅。', heat: '中火', timerSeconds: 300 },
    ],
    tips: ['豆腐表面水分要擦干再煎，以免油溅；木耳需在焖煮时充分受热，猪肉末也必须炒到完全熟透。'],
  },
]
