import type { Recipe } from './types'

export const recipesBatchD: Recipe[] = [
  {
    id: 'chive-scrambled-eggs',
    title: '韭菜炒鸡蛋',
    subtitle: '韭香清新，鸡蛋松软家常',
    emoji: '🥚',
    colors: ['#d8df78', '#6e944f'],
    minutes: 12,
    difficulty: 1,
    rating: 4.8,
    calories: 286,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '韭菜', amount: 180, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 4, unit: '个', role: 'core' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '准备食材', text: '韭菜择洗干净后彻底沥水，切成约 4 厘米段；鸡蛋加一半盐和白胡椒粉打散。', heat: '不开火' },
      { title: '炒熟鸡蛋', text: '炒锅烧热放油，倒入蛋液，中火推炒成大块，确认没有流动蛋液后先盛出。', heat: '中火', timerSeconds: 90 },
      { title: '快炒韭菜', text: '原锅放入韭菜梗，大火炒 30 秒，再加入韭菜叶和剩余盐。', heat: '大火', timerSeconds: 60 },
      { title: '合炒出锅', text: '倒回鸡蛋，快速翻匀，让韭菜刚好变软后立即关火装盘。', heat: '大火', timerSeconds: 30 },
    ],
    tips: ['鸡蛋必须炒到完全凝固、没有流动蛋液后再食用；韭菜沥干可避免下锅溅油。'],
  },
  {
    id: 'oyster-mushroom-eggs',
    title: '平菇炒鸡蛋',
    subtitle: '菌菇鲜嫩，鸡蛋吸足汤汁',
    emoji: '🍄',
    colors: ['#e2d4a7', '#8b7e61'],
    minutes: 18,
    difficulty: 1,
    rating: 4.7,
    calories: 274,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '平菇', amount: 250, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '大蒜', amount: 2, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '撕洗平菇', text: '平菇切去老根，撕成均匀小条，快速冲洗后轻轻挤去多余水分；蒜切片。', heat: '不开火' },
      { title: '炒熟鸡蛋', text: '鸡蛋加一小撮盐打散；热锅放一半油，倒入蛋液炒至完全凝固后盛出。', heat: '中火', timerSeconds: 90 },
      { title: '炒透平菇', text: '原锅补油，炒香蒜片，加入平菇大火翻炒至出水，再继续炒到水分明显减少、菌菇变软。', heat: '大火', timerSeconds: 300 },
      { title: '合炒调味', text: '倒回鸡蛋，加生抽和剩余盐翻匀，撒葱花后出锅。', heat: '中火', timerSeconds: 45 },
    ],
    tips: ['鸡蛋要完全凝固，平菇也要炒至整体变软、没有生菌味后再食用，不要用不明来源的野生菌替代。'],
  },
  {
    id: 'steamed-minced-pork-egg',
    title: '肉末蒸蛋',
    subtitle: '蛋羹细滑，肉末咸香下饭',
    emoji: '🥚',
    colors: ['#ead294', '#a97854'],
    minutes: 35,
    difficulty: 2,
    rating: 4.8,
    calories: 338,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 + 蒸锅',
    ingredients: [
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '猪肉末', amount: 120, unit: '克', role: 'core' },
      { name: '姜', amount: 2, unit: '片', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '调好蛋液', text: '鸡蛋打散，加入约 280 毫升温水和盐轻轻搅匀，过筛倒入浅碗并盖上耐热盘。', heat: '不开火' },
      { title: '炒熟肉末', text: '肉末加黄酒和淀粉拌匀；炒锅放少量油和姜末，中火把肉末划散，炒到完全变色后加 1 汤匙生抽。', heat: '中火', timerSeconds: 240 },
      { title: '蒸至半凝', text: '蒸锅水开后放入蛋液，小火蒸 8 分钟，待表面基本凝固后轻轻铺上熟肉末。', heat: '小火', timerSeconds: 480 },
      { title: '蒸透调味', text: '继续小火蒸 5 分钟并关火焖 2 分钟，确认蛋羹中心凝固后，淋剩余生抽和香油，撒葱花。', heat: '小火', timerSeconds: 300 },
    ],
    tips: ['猪肉末必须炒到无粉红色、蛋羹中心也要完全凝固；出锅碗和蒸汽都很烫，应戴隔热手套。'],
  },
  {
    id: 'tea-eggs',
    title: '茶叶蛋',
    subtitle: '茶香卤味深入蛋白纹理',
    emoji: '🥚',
    colors: ['#c8a77b', '#69513e'],
    minutes: 180,
    difficulty: 1,
    rating: 4.7,
    calories: 148,
    servings: 4,
    vegetarian: true,
    tastes: ['咸鲜', '浓郁'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '鸡蛋', amount: 8, unit: '个', role: 'core' },
      { name: '红茶', amount: 10, unit: '克', role: 'support' },
      { name: '八角', amount: 2, unit: '个', role: 'support' },
      { name: '桂皮', amount: 1, unit: '小段', role: 'support' },
      { name: '生抽', amount: 4, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '煮熟鸡蛋', text: '鸡蛋刷洗干净后放入冷水，水量没过鸡蛋；中火煮开后继续煮 10 分钟，让蛋黄完全熟透。', heat: '中火', timerSeconds: 600 },
      { title: '敲出裂纹', text: '鸡蛋捞入冷水降温，用勺背轻敲蛋壳，敲出均匀网状裂纹但不要剥壳。', heat: '不开火' },
      { title: '调卤慢煮', text: '锅中加约 1 升水、红茶、八角、桂皮、生抽、老抽、盐和糖，放入鸡蛋，煮开后小火卤 30 分钟。', heat: '小火', timerSeconds: 1800 },
      { title: '冷藏入味', text: '关火后让鸡蛋在卤汁中自然降温，放凉后连卤汁冷藏浸泡至少 2 小时，食用前可重新煮热。', heat: '不开火', timerSeconds: 7200 },
    ],
    tips: ['蛋黄必须完全凝固；卤好的鸡蛋不要长时间放在室温，冷却后及时冷藏并在再次食用前彻底加热。'],
  },
  {
    id: 'seaweed-egg-drop-soup',
    title: '紫菜蛋花汤',
    subtitle: '清鲜快手，蛋花轻盈柔软',
    emoji: '🥣',
    colors: ['#b6c2a2', '#5f7065'],
    minutes: 10,
    difficulty: 1,
    rating: 4.7,
    calories: 118,
    servings: 3,
    vegetarian: true,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '紫菜', amount: 10, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 2, unit: '个', role: 'core' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '姜', amount: 2, unit: '片', role: 'support' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '洗菜打蛋', text: '紫菜快速冲洗后挤干，鸡蛋充分打散，小葱切花。', heat: '不开火' },
      { title: '煮好汤底', text: '锅中加入约 800 毫升水和姜片，大火煮开后加盐和白胡椒粉。', heat: '大火', timerSeconds: 180 },
      { title: '放入紫菜', text: '加入紫菜并用筷子拨散，让汤再次沸腾约 1 分钟。', heat: '大火', timerSeconds: 60 },
      { title: '淋入蛋花', text: '转中火保持微沸，细细淋入蛋液，待蛋花完全凝固后关火，加葱花和香油。', heat: '中火', timerSeconds: 45 },
    ],
    tips: ['蛋花要全部凝固后再食用；刚煮好的汤温度很高，盛汤和入口前都要防止蒸汽与热汤烫伤。'],
  },
  {
    id: 'green-bean-braised-noodles',
    title: '豆角焖面',
    subtitle: '面条吸汁，豆角肉香融合',
    emoji: '🍜',
    colors: ['#c6cd78', '#6e7946'],
    minutes: 38,
    difficulty: 2,
    rating: 4.8,
    calories: 568,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鲜面条', amount: 400, unit: '克', role: 'core' },
      { name: '四季豆', amount: 300, unit: '克', role: 'core', substitutes: ['豇豆'] },
      { name: '五花肉', amount: 180, unit: '克', role: 'core' },
      { name: '姜', amount: 3, unit: '片', role: 'support' },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '生抽', amount: 2.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '备肉和豆角', text: '四季豆掐去两端和老筋后掰段，五花肉切薄片，姜蒜切末。', heat: '不开火' },
      { title: '煸肉炒豆角', text: '锅中放油，下五花肉中火煸至完全变色并略出油，加入姜蒜、四季豆炒到颜色变深。', heat: '中火', timerSeconds: 420 },
      { title: '加汤预煮', text: '加入生抽、老抽、盐和约 550 毫升热水，煮开后先盛出一碗汤汁；加盖把豆角煮 6 分钟。', heat: '中火', timerSeconds: 360 },
      { title: '铺面焖熟', text: '鲜面条抖散铺在豆角上，分两次淋回汤汁，加盖小火焖 10 分钟；翻拌后确认豆角无生硬感、面条无白芯。', heat: '小火', timerSeconds: 600 },
    ],
    tips: ['四季豆必须彻底煮透至颜色变暗、没有生硬和生豆味，夹生豆角可能引起不适；五花肉也要完全熟透。'],
  },
  {
    id: 'stir-fried-rice-noodles',
    title: '炒河粉',
    subtitle: '镬气十足，河粉滑而不碎',
    emoji: '🍜',
    colors: ['#dfbd82', '#88714d'],
    minutes: 25,
    difficulty: 2,
    rating: 4.8,
    calories: 526,
    servings: 2,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '鲜河粉', amount: 500, unit: '克', role: 'core' },
      { name: '牛里脊', amount: 180, unit: '克', role: 'core' },
      { name: '豆芽', amount: 150, unit: '克', role: 'support' },
      { name: '韭黄', amount: 80, unit: '克', role: 'support', substitutes: ['小葱'] },
      { name: '洋葱', amount: 0.5, unit: '个', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌牛肉备菜', text: '牛里脊逆纹切薄片，加 1 汤匙生抽、淀粉和 1 茶匙油抓匀；河粉轻轻拨散，洋葱切丝。', heat: '不开火', timerSeconds: 600 },
      { title: '炒熟牛肉', text: '炒锅烧热放一半油，牛肉平码入锅，大火翻炒至完全变色、中心不再发红后盛出。', heat: '大火', timerSeconds: 150 },
      { title: '煎香河粉', text: '原锅补油，下洋葱炒香，放河粉摊开煎约 1 分钟，再沿锅边淋剩余生抽、老抽和糖。', heat: '大火', timerSeconds: 180 },
      { title: '加入配菜', text: '放入豆芽、韭黄和熟牛肉，快速翻拌至豆芽断生、河粉热透后立即出锅。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['牛肉必须炒到中心没有红色血水；鲜河粉容易粘连，应用锅铲翻抛，不要反复用力切断。'],
  },
  {
    id: 'zhajiang-noodles',
    title: '炸酱面',
    subtitle: '肉酱醇厚，拌面咸香满足',
    emoji: '🍜',
    colors: ['#c69668', '#684b3c'],
    minutes: 35,
    difficulty: 2,
    rating: 4.9,
    calories: 632,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 + 汤锅',
    ingredients: [
      { name: '面条', amount: 400, unit: '克', role: 'core' },
      { name: '猪肉末', amount: 250, unit: '克', role: 'core' },
      { name: '黄豆酱', amount: 100, unit: '克', role: 'core' },
      { name: '甜面酱', amount: 50, unit: '克', role: 'seasoning' },
      { name: '黄瓜', amount: 1, unit: '根', role: 'support' },
      { name: '胡萝卜', amount: 0.5, unit: '根', role: 'support' },
      { name: '姜', amount: 3, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '备酱和菜码', text: '黄豆酱、甜面酱、糖和 120 毫升清水调匀；黄瓜、胡萝卜切细丝，姜葱切末。', heat: '不开火' },
      { title: '炒熟肉末', text: '炒锅放油，下姜葱末和猪肉末，中火充分划散，炒至肉末完全变色、没有粉红肉粒。', heat: '中火', timerSeconds: 300 },
      { title: '熬浓炸酱', text: '倒入调好的酱汁，小火不停翻动约 8 分钟，熬到酱色油亮、肉末均匀挂汁。', heat: '小火', timerSeconds: 480 },
      { title: '煮面拌匀', text: '另锅水开后下入面条，按包装时间煮到无白芯，沥水装碗，放肉酱和菜码拌匀。', heat: '大火' },
    ],
    tips: ['猪肉末必须彻底炒熟至无粉红色；熬酱时容易飞溅，需用小火并避免脸和手靠近锅口。'],
  },
  {
    id: 'yangchun-noodles',
    title: '阳春面',
    subtitle: '清汤葱香，简单却很熨帖',
    emoji: '🍜',
    colors: ['#e4d3a5', '#8a815e'],
    minutes: 12,
    difficulty: 1,
    rating: 4.7,
    calories: 392,
    servings: 2,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '细面条', amount: 300, unit: '克', role: 'core' },
      { name: '小葱', amount: 3, unit: '根', role: 'support' },
      { name: '猪油', amount: 2, unit: '茶匙', role: 'seasoning', substitutes: ['香油'] },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '调好碗底', text: '两个面碗分别放入猪油、生抽、盐、糖、白胡椒粉和葱花。', heat: '不开火' },
      { title: '烧开面汤', text: '汤锅加入足量清水，大火煮至持续沸腾。', heat: '大火' },
      { title: '煮熟面条', text: '面条抖散下锅，用筷子拨开，煮到面芯完全熟透但仍有弹性。', heat: '大火', timerSeconds: 240 },
      { title: '冲汤装碗', text: '每只碗先舀入约 300 毫升滚烫面汤搅匀，再捞入面条，撒少量葱花。', heat: '不开火' },
    ],
    tips: ['面汤和碗都很烫，端取时注意防滑防烫；给儿童食用前应把面条剪短并充分晾温。'],
  },
  {
    id: 'scallion-oil-noodles',
    title: '葱油拌面',
    subtitle: '葱香焦甜，酱汁紧裹面条',
    emoji: '🍜',
    colors: ['#cbbd72', '#627447'],
    minutes: 25,
    difficulty: 2,
    rating: 4.8,
    calories: 488,
    servings: 2,
    vegetarian: true,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 + 汤锅',
    ingredients: [
      { name: '细面条', amount: 300, unit: '克', role: 'core' },
      { name: '小葱', amount: 100, unit: '克', role: 'core' },
      { name: '生抽', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '糖', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '食用油', amount: 5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '擦干香葱', text: '小葱洗净后彻底擦干，切成约 6 厘米段，葱白和葱绿分开。', heat: '不开火', tip: '葱上不能带明显水珠，否则入油会猛烈飞溅。' },
      { title: '熬制葱油', text: '冷锅放油和葱白，小火加热至微黄，再放葱绿继续熬到焦黄酥脆后捞出。', heat: '小火', timerSeconds: 720 },
      { title: '调成酱汁', text: '关火稍降温，加入生抽、老抽和糖，再开小火搅煮约 30 秒至糖融化。', heat: '小火', timerSeconds: 30 },
      { title: '煮面拌匀', text: '另锅水开后把面条煮到无白芯，沥干后趁热拌入适量葱油酱，放上酥葱段。', heat: '大火' },
    ],
    tips: ['葱油温度很高，加入含水酱油前应先关火降温，操作时保持距离，避免油花烫伤。'],
  },
  {
    id: 'yangzhou-fried-rice',
    title: '扬州炒饭',
    subtitle: '配料缤纷，米饭粒粒分明',
    emoji: '🍚',
    colors: ['#edd16e', '#b47849'],
    minutes: 25,
    difficulty: 2,
    rating: 4.9,
    calories: 548,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '冷米饭', amount: 450, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '虾仁', amount: 100, unit: '克', role: 'core' },
      { name: '火腿', amount: 80, unit: '克', role: 'support' },
      { name: '豌豆', amount: 60, unit: '克', role: 'support' },
      { name: '胡萝卜', amount: 60, unit: '克', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理配料', text: '冷米饭拨散，火腿和胡萝卜切小丁；豌豆、胡萝卜焯 2 分钟，虾仁焯到完全不透明后沥干。', heat: '大火', timerSeconds: 180 },
      { title: '炒熟鸡蛋', text: '鸡蛋充分打散；热锅放一半油，倒入蛋液快速炒成细碎且完全凝固的蛋粒，先盛出。', heat: '中火', timerSeconds: 90 },
      { title: '炒散米饭', text: '原锅补油，下火腿丁炒香，放入米饭大火翻炒并压散结块，炒到米粒干爽。', heat: '大火', timerSeconds: 240 },
      { title: '合炒调味', text: '加入蛋粒、虾仁、豌豆、胡萝卜、盐和白胡椒粉，大火炒匀热透，撒葱花出锅。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['虾仁应完全不透明、鸡蛋应完全凝固；隔夜米饭必须及时冷藏，出现异味或在室温放置过久时不要再炒食。'],
  },
  {
    id: 'claypot-rice-chinese-sausage',
    title: '腊肠煲仔饭',
    subtitle: '腊香渗入米饭，锅底带脆香',
    emoji: '🍚',
    colors: ['#d8a06f', '#774f3d'],
    minutes: 55,
    difficulty: 3,
    rating: 4.9,
    calories: 684,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '砂锅 + 汤锅',
    ingredients: [
      { name: '大米', amount: 250, unit: '克', role: 'core' },
      { name: '广式腊肠', amount: 2, unit: '根', role: 'core' },
      { name: '鸡蛋', amount: 1, unit: '个', role: 'support' },
      { name: '小白菜', amount: 180, unit: '克', role: 'support' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '蚝油', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '浸米调汁', text: '大米淘洗后浸泡 30 分钟并沥水；生抽、蚝油、糖、香油和 2 汤匙温水调成汁，腊肠斜切片。', heat: '不开火', timerSeconds: 1800 },
      { title: '煮至收水', text: '砂锅内薄抹食用油，放入大米和约 310 毫升水，大火煮开后转小火，加盖煮到水面基本消失。', heat: '小火', timerSeconds: 600 },
      { title: '铺料焖熟', text: '沿锅边摆入腊肠和姜丝，中间打入鸡蛋，盖盖继续小火焖 10 分钟，再关火焖 5 分钟。', heat: '小火', timerSeconds: 600 },
      { title: '配菜拌饭', text: '另锅把小白菜焯熟；确认腊肠热透、鸡蛋完全凝固后铺入砂锅，淋调味汁并拌匀。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['腊肠属于生制肉品时必须彻底焖熟，切面不可有生肉感；鸡蛋也应完全凝固，砂锅离火后仍很烫，端取要戴隔热手套。'],
  },
  {
    id: 'century-egg-pork-congee',
    title: '皮蛋瘦肉粥',
    subtitle: '米粥绵滑，皮蛋肉丝咸鲜',
    emoji: '🥣',
    colors: ['#d7d0ad', '#77745f'],
    minutes: 65,
    difficulty: 2,
    rating: 4.8,
    calories: 326,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '大米', amount: 120, unit: '克', role: 'core' },
      { name: '猪里脊', amount: 150, unit: '克', role: 'core' },
      { name: '皮蛋', amount: 2, unit: '个', role: 'core' },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '泡米腌肉', text: '大米淘洗后浸泡 20 分钟；猪里脊切细丝，加生抽、淀粉和少量水抓匀，皮蛋去壳切丁。', heat: '不开火', timerSeconds: 1200 },
      { title: '熬开米花', text: '锅中加入大米、姜丝和约 1.4 升水，大火煮开后转小火，锅盖留缝煮 35 分钟并不时搅底。', heat: '小火', timerSeconds: 2100 },
      { title: '煮透肉丝', text: '把肉丝逐条拨入粥中，轻轻搅散，保持小火煮 6 分钟，确认肉丝内外完全变白。', heat: '小火', timerSeconds: 360 },
      { title: '加入皮蛋', text: '放入皮蛋丁再煮 5 分钟，加盐和香油调味，关火后撒葱花。', heat: '小火', timerSeconds: 300 },
    ],
    tips: ['猪肉丝必须煮到中心无粉红色；稠粥会持续冒泡并黏在皮肤上，搅拌、盛取和入口时都要格外防烫。'],
  },
  {
    id: 'pumpkin-congee',
    title: '南瓜粥',
    subtitle: '南瓜软甜，米粥温润绵密',
    emoji: '🎃',
    colors: ['#efc765', '#c4753e'],
    minutes: 50,
    difficulty: 1,
    rating: 4.7,
    calories: 218,
    servings: 4,
    vegetarian: true,
    tastes: ['清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '大米', amount: 120, unit: '克', role: 'core' },
      { name: '南瓜', amount: 400, unit: '克', role: 'core' },
      { name: '冰糖', amount: 20, unit: '克', role: 'seasoning', substitutes: ['白糖'] },
      { name: '清水', amount: 1.4, unit: '升', role: 'seasoning' },
    ],
    steps: [
      { title: '洗米切南瓜', text: '大米淘洗后浸泡 15 分钟；南瓜去皮去瓤，切成约 2 厘米小块。', heat: '不开火', timerSeconds: 900 },
      { title: '先煮米粥', text: '大米和清水放入锅中，大火煮开后转小火，锅盖留缝煮 20 分钟，期间搅动两次。', heat: '小火', timerSeconds: 1200 },
      { title: '加入南瓜', text: '放入南瓜块，继续小火煮 20 分钟，煮到米粒开花、南瓜能被勺背轻松压碎。', heat: '小火', timerSeconds: 1200 },
      { title: '压匀调甜', text: '用勺背压碎一半南瓜并搅匀，按口味加入冰糖，煮至融化后关火。', heat: '小火', timerSeconds: 180 },
    ],
    tips: ['南瓜粥黏稠、降温慢，起锅后至少静置数分钟再入口；搅拌时手臂不要靠近冒泡的粥面，防止烫伤。'],
  },
  {
    id: 'dough-drop-soup',
    title: '疙瘩汤',
    subtitle: '面疙瘩筋软，番茄汤酸香',
    emoji: '🥣',
    colors: ['#edaa7e', '#b85c45'],
    minutes: 30,
    difficulty: 2,
    rating: 4.7,
    calories: 328,
    servings: 3,
    vegetarian: true,
    tastes: ['咸鲜', '酸甜'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '面粉', amount: 160, unit: '克', role: 'core' },
      { name: '番茄', amount: 2, unit: '个', role: 'core' },
      { name: '鸡蛋', amount: 2, unit: '个', role: 'core' },
      { name: '小白菜', amount: 100, unit: '克', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '盐', amount: 0.75, unit: '茶匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '拌小疙瘩', text: '面粉放入大碗，一边少量多次洒入约 80 毫升清水，一边用筷子快速搅成大小均匀的小疙瘩。', heat: '不开火' },
      { title: '炒番茄汤底', text: '汤锅放油和葱白，加入番茄块和一半盐，中火炒软出汁，再加约 900 毫升热水煮开。', heat: '中火', timerSeconds: 300 },
      { title: '煮熟面疙瘩', text: '保持汤沸腾，分批撒入面疙瘩并及时搅散，煮约 6 分钟至最大的疙瘩中心没有干面粉。', heat: '中火', timerSeconds: 360 },
      { title: '加入蛋和菜', text: '放小白菜煮软，淋入蛋液，待蛋花完全凝固后加剩余盐和生抽调味。', heat: '中火', timerSeconds: 120 },
    ],
    tips: ['要切开最大的面疙瘩确认无生面芯，蛋花也应完全凝固；浓汤和疙瘩都很蓄热，食用前充分晾温。'],
  },
  {
    id: 'hot-sour-soup',
    title: '酸辣汤',
    subtitle: '酸香胡椒辣，配料丰富暖胃',
    emoji: '🥣',
    colors: ['#c99670', '#754b3f'],
    minutes: 28,
    difficulty: 2,
    rating: 4.8,
    calories: 196,
    servings: 4,
    vegetarian: true,
    tastes: ['酸爽', '微辣'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '嫩豆腐', amount: 200, unit: '克', role: 'core' },
      { name: '鸡蛋', amount: 1, unit: '个', role: 'core' },
      { name: '香菇', amount: 4, unit: '朵', role: 'support' },
      { name: '木耳', amount: 60, unit: '克（泡发后）', role: 'support' },
      { name: '竹笋', amount: 100, unit: '克', role: 'support' },
      { name: '陈醋', amount: 3, unit: '汤匙', role: 'seasoning' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切细配料', text: '豆腐、香菇、木耳和竹笋分别切细丝；淀粉加 3 汤匙清水调匀，鸡蛋打散。', heat: '不开火' },
      { title: '煮熟汤料', text: '锅中加入约 1 升水，水开后放香菇、木耳和竹笋煮 5 分钟，再放豆腐、生抽和盐。', heat: '中火', timerSeconds: 420 },
      { title: '勾芡淋蛋', text: '汤保持微沸，一边搅动一边淋入水淀粉；汤略稠后细细淋入蛋液，等蛋花完全凝固。', heat: '中火', timerSeconds: 120 },
      { title: '调酸和辣', text: '关火后加入陈醋、白胡椒粉和香油搅匀，试味后立即盛出。', heat: '不开火' },
    ],
    tips: ['蛋花要完全凝固，香菇和木耳要煮透；勾芡汤温度高且不易散热，入口前务必小口试温。'],
  },
  {
    id: 'corn-pork-rib-soup',
    title: '玉米排骨汤',
    subtitle: '玉米清甜，排骨汤鲜而不腻',
    emoji: '🌽',
    colors: ['#e5cb70', '#8a8c56'],
    minutes: 95,
    difficulty: 2,
    rating: 4.9,
    calories: 426,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '猪排骨', amount: 600, unit: '克', role: 'core' },
      { name: '甜玉米', amount: 2, unit: '根', role: 'core' },
      { name: '胡萝卜', amount: 1, unit: '根', role: 'support' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯洗排骨', text: '排骨用冷水浸泡 20 分钟后冲净，冷水下锅，加两片姜和黄酒；煮开 3 分钟后捞出，用温水洗净浮沫。', heat: '大火', timerSeconds: 180 },
      { title: '开始炖汤', text: '排骨放入干净汤锅，加入剩余姜片和约 1.8 升热水，大火煮开后转小火炖 45 分钟。', heat: '小火', timerSeconds: 2700 },
      { title: '加入玉米', text: '玉米切段、胡萝卜切滚刀块，一起放入汤中，继续小火炖 25 分钟。', heat: '小火', timerSeconds: 1500 },
      { title: '检查调味', text: '确认排骨最厚处完全熟透、肉能轻松离骨后加盐，煮 2 分钟并撒葱花。', heat: '中火', timerSeconds: 120 },
    ],
    tips: ['排骨贴骨位置必须无粉红色和血水；开盖时先让蒸汽散开，汤和骨块都很烫，儿童食用需拆骨并晾温。'],
  },
  {
    id: 'kelp-pork-rib-soup',
    title: '海带排骨汤',
    subtitle: '海带软滑，汤底鲜醇清润',
    emoji: '🍲',
    colors: ['#aebc91', '#536c5d'],
    minutes: 100,
    difficulty: 2,
    rating: 4.8,
    calories: 398,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '猪排骨', amount: 600, unit: '克', role: 'core' },
      { name: '海带结', amount: 300, unit: '克（泡发后）', role: 'core' },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '洗海带焯骨', text: '泡发海带结反复冲洗掉沙粒；排骨冷水下锅，加两片姜和黄酒，煮开 3 分钟后捞出洗净。', heat: '大火', timerSeconds: 180 },
      { title: '慢炖排骨', text: '排骨、剩余姜片和约 1.8 升热水放入汤锅，大火煮开后撇沫，转小火炖 50 分钟。', heat: '小火', timerSeconds: 3000 },
      { title: '加入海带', text: '放入洗净的海带结，继续小火炖 25 分钟，煮到海带柔软、排骨肉容易离骨。', heat: '小火', timerSeconds: 1500 },
      { title: '调味出锅', text: '检查排骨贴骨处完全熟透后，加盐和白胡椒粉煮 2 分钟，撒葱花。', heat: '中火', timerSeconds: 120 },
    ],
    tips: ['排骨必须炖到贴骨处没有粉红色和血水；海带汤保温时间长，开盖避开蒸汽，盛出后充分晾温再喝。'],
  },
  {
    id: 'tremella-lotus-seed-soup',
    title: '银耳莲子羹',
    subtitle: '银耳软糯，莲子清甜绵润',
    emoji: '🥣',
    colors: ['#eee1bd', '#ac8f69'],
    minutes: 160,
    difficulty: 1,
    rating: 4.7,
    calories: 226,
    servings: 4,
    vegetarian: true,
    tastes: ['清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '干银耳', amount: 20, unit: '克', role: 'core' },
      { name: '干莲子', amount: 80, unit: '克', role: 'core' },
      { name: '红枣', amount: 8, unit: '颗', role: 'support' },
      { name: '枸杞', amount: 10, unit: '克', role: 'support' },
      { name: '冰糖', amount: 50, unit: '克', role: 'seasoning' },
      { name: '清水', amount: 1.6, unit: '升', role: 'seasoning' },
    ],
    steps: [
      { title: '泡发银耳莲子', text: '银耳和莲子分别用冷水泡 2 小时；银耳完全展开后剪去黄色硬蒂，撕成小朵，莲子去除苦芯。', heat: '不开火', timerSeconds: 7200 },
      { title: '小火慢煮', text: '银耳、莲子和清水放入汤锅，大火煮开后转小火，锅盖留缝煮 50 分钟并间歇搅动。', heat: '小火', timerSeconds: 3000 },
      { title: '加入红枣', text: '红枣洗净去核后加入，继续小火煮 20 分钟，直到银耳出胶、莲子能轻松压碎。', heat: '小火', timerSeconds: 1200 },
      { title: '加糖和枸杞', text: '加入冰糖和枸杞，再煮 5 分钟至糖完全融化，关火静置片刻。', heat: '小火', timerSeconds: 300 },
    ],
    tips: ['莲子要煮到中心软透、没有硬芯；甜羹黏稠且降温慢，搅拌和食用时要防止热糖水烫伤。'],
  },
  {
    id: 'red-bean-soup',
    title: '红豆汤',
    subtitle: '红豆绵沙，甜汤温润朴实',
    emoji: '🫘',
    colors: ['#c98278', '#713f42'],
    minutes: 320,
    difficulty: 1,
    rating: 4.7,
    calories: 248,
    servings: 4,
    vegetarian: true,
    tastes: ['浓郁'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '红豆', amount: 220, unit: '克', role: 'core' },
      { name: '陈皮', amount: 1, unit: '小片', role: 'support' },
      { name: '冰糖', amount: 60, unit: '克', role: 'seasoning' },
      { name: '清水', amount: 1.6, unit: '升', role: 'seasoning' },
    ],
    steps: [
      { title: '挑豆浸泡', text: '红豆挑去破损豆和杂质，冲洗干净后用足量冷水浸泡 4 小时；陈皮洗净泡软。', heat: '不开火', timerSeconds: 14400 },
      { title: '大火煮开', text: '红豆沥去泡豆水，与陈皮、清水放入汤锅，大火煮开后保持沸腾 10 分钟并撇去浮沫。', heat: '大火', timerSeconds: 600 },
      { title: '煮至软烂', text: '转小火、锅盖留缝煮 55 分钟，中途搅动并补少量热水，直到豆粒开花、中心完全软烂。', heat: '小火', timerSeconds: 3300 },
      { title: '加糖完成', text: '加入冰糖继续煮 5 分钟，搅到融化后关火；静置至温度适口再盛出。', heat: '小火', timerSeconds: 300 },
    ],
    tips: ['红豆必须充分煮透到中心没有硬芯和生豆味，不能用泡豆代替煮熟；甜汤很蓄热，入口前要彻底晾温。'],
  },
]
