import type { Recipe } from './types'

export const recipesBatchA: Recipe[] = [
  {
    id: 'braised-pork-belly',
    title: '红烧肉',
    subtitle: '酱色红亮，五花肉软糯入味',
    emoji: '🥩',
    colors: ['#d69a72', '#843f2f'],
    minutes: 85,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炖锅 · 1 口锅',
    ingredients: [
      { name: '带皮五花肉', amount: 600, unit: '克', role: 'core', substitutes: ['去皮五花肉', '猪梅花肉'] },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '八角', amount: 1, unit: '颗', role: 'seasoning', substitutes: ['桂皮 1 小段'] },
      { name: '冰糖', amount: 25, unit: '克', role: 'seasoning', substitutes: ['白砂糖'] },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切块焯洗', text: '五花肉切成约 3 厘米见方的块，冷水下锅煮开后再煮 3 分钟，捞出用温水洗净浮沫并充分沥干。', heat: '大火', timerSeconds: 180 },
      { title: '炒糖上色', text: '锅中放油和冰糖，小火炒至糖融化并呈浅琥珀色；关小火放入肉块，翻动至表面均匀裹上糖色。', heat: '小火', timerSeconds: 300, tip: '肉块要沥干再下锅，减少热糖遇水飞溅。' },
      { title: '加料慢炖', text: '加入姜、葱、八角、生抽、老抽和黄酒，倒入没过肉块的热水；煮开后加盖，小火炖约 50 分钟。', heat: '小火', timerSeconds: 3000 },
      { title: '收汁熟透', text: '拣去葱和八角，确认肉块中心完全熟透后转中火收汁，期间轻轻翻动，待汤汁能薄薄裹住肉块即可。', heat: '中火', timerSeconds: 600 },
    ],
    tips: ['焯水只用于去除浮沫，肉块仍需经过后续炖煮并确认中心熟透。', '糖色炒到浅琥珀色即可，颜色过深会发苦；不熟悉炒糖色时可直接用老抽调色。'],
  },
  {
    id: 'sweet-sour-pork-ribs',
    title: '糖醋排骨',
    subtitle: '酸甜均衡，排骨亮润脱骨',
    emoji: '🍖',
    colors: ['#e0a06f', '#9d4938'],
    minutes: 60,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['酸甜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '猪肋排', amount: 650, unit: '克', role: 'core', substitutes: ['猪小排'] },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '香醋', amount: 3, unit: '汤匙', role: 'seasoning', substitutes: ['米醋'] },
      { name: '冰糖', amount: 35, unit: '克', role: 'seasoning', substitutes: ['白砂糖'] },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '排骨焯水', text: '排骨用清水浸泡 10 分钟后洗净，冷水下锅，加入两片姜和黄酒；煮开后撇去浮沫，再煮 3 分钟并捞出沥干。', heat: '大火', timerSeconds: 180 },
      { title: '煎香表面', text: '炒锅放油，中火把排骨煎至各面微黄，加入剩余姜片、葱结和冰糖翻炒至糖融化。', heat: '中火', timerSeconds: 480 },
      { title: '调味焖熟', text: '加入生抽、老抽和两汤匙香醋，倒入约 500 毫升热水；煮开后加盖小火焖 30 分钟，直至排骨熟透。', heat: '小火', timerSeconds: 1800 },
      { title: '补醋收汁', text: '拣去葱姜，转中火收汁；汤汁变浓时加入剩余香醋，翻匀至酸甜汁包裹排骨后关火。', heat: '中火', timerSeconds: 360 },
    ],
    tips: ['带骨肉成熟较慢，食用前可检查最厚处靠骨肉质，确认没有血色且已经熟透。', '最后补少量醋能保留香气，收汁时要勤翻动，避免糖分粘锅。'],
  },
  {
    id: 'yu-xiang-pork',
    title: '鱼香肉丝',
    subtitle: '酸甜微辣，肉丝滑嫩下饭',
    emoji: '🥢',
    colors: ['#d68d68', '#873d36'],
    minutes: 30,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['酸爽', '微辣'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '猪里脊', amount: 300, unit: '克', role: 'core', substitutes: ['猪后腿瘦肉', '鸡胸肉'] },
      { name: '冬笋', amount: 120, unit: '克', role: 'core', substitutes: ['茭白'] },
      { name: '泡发木耳', amount: 70, unit: '克', role: 'support' },
      { name: '胡萝卜', amount: 60, unit: '克', role: 'support' },
      { name: '姜末', amount: 1, unit: '茶匙', role: 'support' },
      { name: '蒜末', amount: 2, unit: '茶匙', role: 'support' },
      { name: '葱花', amount: 2, unit: '汤匙', role: 'support' },
      { name: '泡椒碎', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['郫县豆瓣酱 1 汤匙'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['米醋'] },
      { name: '白糖', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 2, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌制肉丝', text: '里脊逆纹切细丝，加半汤匙生抽、1 茶匙淀粉和 1 汤匙清水抓匀，最后拌入少量食用油，静置 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '备菜调碗汁', text: '冬笋、木耳和胡萝卜切细丝；把剩余生抽、香醋、白糖、1 茶匙淀粉和 3 汤匙清水调匀。', heat: '不开火' },
      { title: '滑炒肉丝', text: '炒锅烧热放一半油，倒入肉丝快速划散，中火炒至肉丝完全变色并熟透，盛出备用。', heat: '中火', timerSeconds: 180 },
      { title: '合炒入味', text: '原锅补油，炒香泡椒、姜末和蒜末，加入三种蔬菜丝炒至断生；放回肉丝，淋入碗汁，大火炒至汁液明亮，撒葱花出锅。', heat: '大火', timerSeconds: 240 },
    ],
    tips: ['切生肉的刀和砧板使用后应及时清洗，避免再直接接触即食食材。', '碗汁下锅前再次搅匀，防止淀粉沉底造成咸甜不均。'],
  },
  {
    id: 'kung-pao-chicken',
    title: '宫保鸡丁',
    subtitle: '糊辣荔枝味，鸡丁嫩香花生脆',
    emoji: '🐔',
    colors: ['#d58b55', '#8c392e'],
    minutes: 30,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['微辣', '酸甜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '去骨鸡腿肉', amount: 400, unit: '克', role: 'core', substitutes: ['鸡胸肉'] },
      { name: '熟花生米', amount: 60, unit: '克', role: 'core', substitutes: ['熟腰果'] },
      { name: '小葱', amount: 4, unit: '根', role: 'support' },
      { name: '姜', amount: 3, unit: '片', role: 'support' },
      { name: '大蒜', amount: 3, unit: '瓣', role: 'support' },
      { name: '干辣椒', amount: 6, unit: '个', role: 'seasoning', substitutes: ['辣椒碎 1 茶匙'] },
      { name: '花椒', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['花椒粉 0.25 茶匙'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['米醋'] },
      { name: '白糖', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '淀粉', amount: 2, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切丁腌味', text: '鸡腿肉切成约 1.5 厘米的丁，加半汤匙生抽、1 茶匙淀粉和 1 汤匙清水抓匀，腌 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '调汁备料', text: '葱白切小段，姜蒜切片，干辣椒剪段；把剩余生抽、香醋、白糖、1 茶匙淀粉和 3 汤匙清水调成碗汁。', heat: '不开火' },
      { title: '炒熟鸡丁', text: '锅烧热放油，鸡丁平码入锅，中火炒至表面微黄、中心完全不透明且无粉红色，先盛出。', heat: '中火', timerSeconds: 300 },
      { title: '糊辣合炒', text: '原锅小火炒香花椒和干辣椒，加入姜蒜、葱白和鸡丁；转大火淋入碗汁，翻炒至汁液裹匀，关火后拌入熟花生米。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['处理生鸡肉后要清洗双手、刀具和砧板，盛熟鸡丁不要使用装过生肉的容器。', '花生米最后加入，能减少回软；对花生过敏时可省略或换成确认安全的熟坚果。'],
  },
  {
    id: 'twice-cooked-pork',
    title: '回锅肉',
    subtitle: '酱香微辣，蒜苗脆嫩肉片焦香',
    emoji: '🥩',
    colors: ['#cf8d61', '#784531'],
    minutes: 45,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['微辣', '浓郁'],
    cookware: '汤锅 + 炒锅',
    ingredients: [
      { name: '带皮五花肉', amount: 450, unit: '克', role: 'core', substitutes: ['猪二刀肉'] },
      { name: '青蒜苗', amount: 200, unit: '克', role: 'core', substitutes: ['青椒', '蒜薹'] },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '郫县豆瓣酱', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['不辣豆瓣酱'] },
      { name: '甜面酱', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['黄豆酱'] },
      { name: '豆豉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '生抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '白糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '煮熟整肉', text: '五花肉冷水下锅，加姜片；煮开后转中火约 20 分钟，直到最厚处中心完全变色，捞出放至不烫手。', heat: '中火', timerSeconds: 1200 },
      { title: '切片备菜', text: '五花肉擦干后切成约 2 毫米薄片；青蒜苗把白色茎部和绿色叶部分开，斜切成段。', heat: '不开火' },
      { title: '煸出灯盏窝', text: '炒锅放少量油，下肉片中火煸至边缘微卷、析出部分油脂，把肉片拨到锅边。', heat: '中火', timerSeconds: 360 },
      { title: '炒酱合味', text: '锅中油里炒香豆瓣酱和豆豉，加入甜面酱、生抽和糖；先放蒜苗茎炒断生，再放叶和肉片，大火翻匀出锅。', heat: '大火', timerSeconds: 180 },
    ],
    tips: ['整块肉的厚度不同，预煮时间需相应调整，以最厚处中心完全熟透为准。', '豆瓣酱、甜面酱和豆豉都有咸味，通常不必再额外加盐。'],
  },
  {
    id: 'farmhouse-stir-fried-pork',
    title: '农家小炒肉',
    subtitle: '青椒焦香，肉片咸鲜带辣',
    emoji: '🌶️',
    colors: ['#8fa95e', '#6f4532'],
    minutes: 25,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '咸鲜'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '五花肉', amount: 220, unit: '克', role: 'core', substitutes: ['猪梅花肉'] },
      { name: '猪瘦肉', amount: 150, unit: '克', role: 'core', substitutes: ['五花肉'] },
      { name: '青尖椒', amount: 250, unit: '克', role: 'core', substitutes: ['薄皮青椒', '青圆椒'] },
      { name: '大蒜', amount: 4, unit: '瓣', role: 'support' },
      { name: '姜', amount: 2, unit: '片', role: 'support' },
      { name: '豆豉', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['豆豉酱 2 茶匙'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切片腌肉', text: '五花肉和瘦肉分别切薄片；瘦肉加入半汤匙生抽和黄酒抓匀，静置 8 分钟。', heat: '不开火', timerSeconds: 480 },
      { title: '煸香青椒', text: '青椒斜切段，干锅中火煸炒至表面出现少量焦斑、椒香散出，盛出备用。', heat: '中火', timerSeconds: 240 },
      { title: '炒熟肉片', text: '锅中放油，先下五花肉煸出部分油脂，再加入瘦肉片、姜蒜和豆豉，翻炒至所有肉片中心熟透。', heat: '中火', timerSeconds: 360 },
      { title: '合炒调味', text: '放回青椒，加入剩余生抽和老抽，大火快速翻炒至青椒断生、肉片均匀上色后关火。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['不能食辣时换用青圆椒，并去净椒籽和白筋。', '生瘦肉和熟配菜应使用不同容器，肉片要炒至中心不再呈粉红色。'],
  },
  {
    id: 'beijing-sauce-pork-strips',
    title: '京酱肉丝',
    subtitle: '甜面酱醇厚，肉丝配葱爽口',
    emoji: '🥢',
    colors: ['#c68b66', '#754231'],
    minutes: 30,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '猪里脊', amount: 350, unit: '克', role: 'core', substitutes: ['猪后腿瘦肉', '鸡胸肉'] },
      { name: '豆腐皮', amount: 3, unit: '张', role: 'core', substitutes: ['生菜叶'] },
      { name: '大葱白', amount: 2, unit: '根', role: 'support' },
      { name: '甜面酱', amount: 3, unit: '汤匙', role: 'seasoning', substitutes: ['黄豆酱 2 汤匙加糖 1 茶匙'] },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '白糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '淀粉', amount: 2, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '腌制肉丝', text: '里脊逆纹切丝，加入黄酒、半汤匙生抽、1 茶匙淀粉和 1 汤匙清水，抓匀后腌 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '准备配菜', text: '大葱白切成细丝，铺在盘底；豆腐皮用沸水烫 1 分钟，沥干后切成便于卷食的小方片。', heat: '大火', timerSeconds: 60 },
      { title: '滑炒肉丝', text: '锅烧热放油，肉丝下锅快速划散，中火炒至完全变色并熟透，先盛出。', heat: '中火', timerSeconds: 240 },
      { title: '裹酱装盘', text: '原锅小火炒香甜面酱和白糖，加入剩余生抽及 2 汤匙清水调开；放回肉丝，转大火翻至酱汁均匀包裹，盛在葱丝上。', heat: '大火', timerSeconds: 120 },
    ],
    tips: ['甜面酱品牌咸度不同，可先尝酱汁再决定是否加完生抽。', '豆腐皮烫后应使用干净容器盛放，不要接触处理生肉的刀板。'],
  },
  {
    id: 'moo-shu-pork',
    title: '木须肉',
    subtitle: '鸡蛋蓬松，木耳黄瓜清香',
    emoji: '🍳',
    colors: ['#e2bd65', '#738857'],
    minutes: 30,
    difficulty: 1,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '猪里脊', amount: 250, unit: '克', role: 'core', substitutes: ['鸡胸肉'] },
      { name: '鸡蛋', amount: 3, unit: '个', role: 'core' },
      { name: '泡发木耳', amount: 80, unit: '克', role: 'core', substitutes: ['鲜香菇'] },
      { name: '黄瓜', amount: 1, unit: '根', role: 'support', substitutes: ['西葫芦'] },
      { name: '胡萝卜', amount: 60, unit: '克', role: 'support' },
      { name: '小葱', amount: 1, unit: '根', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '处理木耳', text: '木耳用冷水泡发后去根、撕小朵，放入沸水煮 2 分钟并沥干；黄瓜和胡萝卜切菱形片。', heat: '大火', timerSeconds: 120 },
      { title: '腌肉炒蛋', text: '里脊切片，加黄酒、半汤匙生抽和淀粉抓匀；鸡蛋加盐打散，下热锅快速炒成大块后盛出。', heat: '中火', timerSeconds: 180 },
      { title: '炒熟肉片', text: '原锅补少量油，放葱花炒香，加入肉片中火翻炒至中心完全变色并熟透。', heat: '中火', timerSeconds: 240 },
      { title: '合炒蔬菜', text: '加入木耳和胡萝卜炒 2 分钟，再放黄瓜、鸡蛋和剩余生抽，大火翻匀约 1 分钟后出锅。', heat: '大火', timerSeconds: 180 },
    ],
    tips: ['干木耳宜冷藏泡发并尽快烹调，不要在室温下长时间浸泡。', '木耳入热油可能迸溅，焯好后要充分沥水再下锅。'],
  },
  {
    id: 'beef-brisket-potato-stew',
    title: '土豆炖牛腩',
    subtitle: '牛腩酥软，土豆吸满浓香汤汁',
    emoji: '🥔',
    colors: ['#c8a067', '#76513d'],
    minutes: 110,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炖锅 · 1 口锅',
    ingredients: [
      { name: '牛腩', amount: 700, unit: '克', role: 'core', substitutes: ['牛肋条'] },
      { name: '土豆', amount: 500, unit: '克', role: 'core', substitutes: ['山药'] },
      { name: '胡萝卜', amount: 1, unit: '根', role: 'support' },
      { name: '洋葱', amount: 0.5, unit: '个', role: 'support' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '八角', amount: 1, unit: '颗', role: 'seasoning', substitutes: ['桂皮 1 小段'] },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '牛腩焯洗', text: '牛腩切成约 4 厘米块，冷水浸泡 15 分钟后换水下锅；煮开撇沫，再煮 3 分钟，捞出用温水洗净。', heat: '大火', timerSeconds: 180 },
      { title: '炒香上色', text: '锅中放油，炒香洋葱、姜和八角，加入牛腩煸至表面微干，再放生抽、老抽和黄酒炒匀。', heat: '中火', timerSeconds: 480 },
      { title: '慢炖牛腩', text: '倒入约 1.2 升热水，煮开后加盖小火炖 60 分钟，期间检查水量并保持轻微沸腾。', heat: '小火', timerSeconds: 3600 },
      { title: '加入根茎', text: '土豆和胡萝卜切滚刀块放入锅中，加盐调味，继续小火炖 20 至 25 分钟，直到牛腩熟透、土豆软而不碎。', heat: '小火', timerSeconds: 1500 },
    ],
    tips: ['牛腩不同部位软化速度有差异，若仍韧可补热水继续炖，不要只按计时出锅。', '土豆发芽或大面积变绿时不宜使用。'],
  },
  {
    id: 'beef-brisket-daikon-stew',
    title: '萝卜炖牛腩',
    subtitle: '萝卜清甜，牛腩醇厚不腻',
    emoji: '🍲',
    colors: ['#d4cfad', '#7c6b4d'],
    minutes: 105,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '炖锅 · 1 口锅',
    ingredients: [
      { name: '牛腩', amount: 700, unit: '克', role: 'core', substitutes: ['牛肋条'] },
      { name: '白萝卜', amount: 650, unit: '克', role: 'core', substitutes: ['青萝卜'] },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '白胡椒粒', amount: 0.5, unit: '茶匙', role: 'seasoning', substitutes: ['白胡椒粉 0.25 茶匙'] },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '焯净牛腩', text: '牛腩切成 4 厘米块，冷水下锅，加一半姜片和黄酒；水开后撇净浮沫，再煮 3 分钟，捞出温水洗净。', heat: '大火', timerSeconds: 180 },
      { title: '先炖牛肉', text: '牛腩放入炖锅，加入剩余姜片、葱结、白胡椒粒和约 1.3 升热水，煮开后转小火加盖炖 60 分钟。', heat: '小火', timerSeconds: 3600 },
      { title: '加入萝卜', text: '白萝卜去皮切滚刀块，加入锅中继续小火炖 25 分钟；中途轻轻翻动，让萝卜浸入汤中。', heat: '小火', timerSeconds: 1500 },
      { title: '调味熟透', text: '确认牛腩中心熟透且达到喜欢的软度，加入盐再煮 5 分钟；拣去葱结，撇去表面多余油脂后盛出。', heat: '小火', timerSeconds: 300 },
    ],
    tips: ['盐接近出锅时再加，萝卜的清甜味会更突出。', '焯水后的牛腩仍未熟透，必须完成后续炖煮；汤量不足时只补热水。'],
  },
  {
    id: 'tomato-beef-brisket-stew',
    title: '番茄牛腩',
    subtitle: '番茄酸香浓厚，牛腩软烂多汁',
    emoji: '🍅',
    colors: ['#df8b6f', '#a54435'],
    minutes: 110,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['酸爽', '浓郁'],
    cookware: '炖锅 · 1 口锅',
    ingredients: [
      { name: '牛腩', amount: 700, unit: '克', role: 'core', substitutes: ['牛肋条'] },
      { name: '番茄', amount: 5, unit: '个（约 800 克）', role: 'core', substitutes: ['罐装去皮番茄 700 克'] },
      { name: '洋葱', amount: 0.5, unit: '个', role: 'support' },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '番茄酱', amount: 2, unit: '汤匙', role: 'seasoning', substitutes: ['多加 1 个熟番茄'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '白糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '牛腩焯水', text: '牛腩切成约 4 厘米块，冷水下锅，加两片姜和黄酒；煮开撇沫后再煮 3 分钟，捞出用温水洗净。', heat: '大火', timerSeconds: 180 },
      { title: '炒出番茄汁', text: '番茄切块；锅中放油，炒香洋葱和剩余姜片，加入三分之二番茄与番茄酱，中火炒至番茄出汁。', heat: '中火', timerSeconds: 600 },
      { title: '合炖牛腩', text: '放入牛腩，加生抽、白糖和约 800 毫升热水，煮开后加盖小火炖 65 分钟，水量不足时补热水。', heat: '小火', timerSeconds: 3900 },
      { title: '补番茄调味', text: '加入剩余番茄和盐，再炖 15 分钟；确认牛腩中心熟透且软度合适，开盖将汤汁收至略浓即可。', heat: '小火', timerSeconds: 900 },
    ],
    tips: ['分两次加入番茄，既能形成浓汤，也能保留少量番茄块。', '牛腩未软时继续小火炖并补充热水，不要用大火快速烧干汤汁。'],
  },
  {
    id: 'scallion-lamb-stir-fry',
    title: '葱爆羊肉',
    subtitle: '葱香旺火，羊肉鲜嫩不膻',
    emoji: '🧅',
    colors: ['#cdbd7e', '#706447'],
    minutes: 25,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '羊腿肉', amount: 400, unit: '克', role: 'core', substitutes: ['羊里脊', '肥牛片'] },
      { name: '大葱白', amount: 3, unit: '根', role: 'core', substitutes: ['洋葱 1 个'] },
      { name: '香菜', amount: 2, unit: '根', role: 'support' },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '香醋', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['米醋'] },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning', substitutes: ['黑胡椒粉'] },
      { name: '白糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切肉腌味', text: '羊肉逆纹切成薄片，加半汤匙生抽、白胡椒粉、淀粉和 1 汤匙清水抓匀，静置 10 分钟。', heat: '不开火', timerSeconds: 600 },
      { title: '切葱调汁', text: '大葱白斜切成约 1 厘米厚片；把剩余生抽、香醋、白糖和 1 汤匙清水调匀。', heat: '不开火' },
      { title: '旺火炒羊肉', text: '锅充分烧热后放油，羊肉单层下锅快速拨散，大火炒至肉片完全变色并熟透。', heat: '大火', timerSeconds: 150 },
      { title: '爆葱出锅', text: '加入葱片继续大火翻炒约 1 分钟，沿锅边淋入调味汁，快速翻匀；葱片刚断生时关火，撒香菜。', heat: '大火', timerSeconds: 90 },
    ],
    tips: ['羊肉切得薄且锅温足，才能缩短炒制时间；下锅后仍要确认肉片中心不见生色。', '羊肉不要一次堆得过多，锅较小时可分两次炒。'],
  },
  {
    id: 'cumin-lamb',
    title: '孜然羊肉',
    subtitle: '孜然焦香，羊肉外焦里嫩',
    emoji: '🍢',
    colors: ['#c99552', '#74503a'],
    minutes: 30,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['香辣', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '羊腿肉', amount: 450, unit: '克', role: 'core', substitutes: ['羊里脊', '牛里脊'] },
      { name: '洋葱', amount: 0.5, unit: '个', role: 'support' },
      { name: '香菜', amount: 3, unit: '根', role: 'support' },
      { name: '孜然粒', amount: 2, unit: '茶匙', role: 'seasoning' },
      { name: '孜然粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '辣椒粉', amount: 1, unit: '茶匙', role: 'seasoning', substitutes: ['甜椒粉'] },
      { name: '生抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '淀粉', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 2, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切块腌制', text: '羊肉切成约 2 厘米小块，加生抽、淀粉、半茶匙孜然粉和 1 汤匙食用油抓匀，腌 12 分钟。', heat: '不开火', timerSeconds: 720 },
      { title: '焙香孜然', text: '孜然粒放入干燥炒锅，小火焙约 40 秒，闻到香味后立即盛出；洋葱切粗丝，香菜切段。', heat: '小火', timerSeconds: 40 },
      { title: '煎炒羊肉', text: '锅中放剩余油，中大火把羊肉尽量单层铺开，煎至表面焦黄，再翻炒至中心完全熟透。', heat: '大火', timerSeconds: 420 },
      { title: '撒料合炒', text: '加入洋葱炒至略软，撒入焙香孜然粒、剩余孜然粉、辣椒粉和盐，大火翻匀约 30 秒，关火拌入香菜。', heat: '大火', timerSeconds: 90 },
    ],
    tips: ['孜然和辣椒粉容易焦糊，应在羊肉熟透后再加入并快速翻匀。', '羊肉块大小要均匀，较大块应切开检查中心，不见生色再出锅。'],
  },
  {
    id: 'soy-braised-pork-ribs',
    title: '红烧排骨',
    subtitle: '酱香醇厚，排骨软嫩入味',
    emoji: '🍖',
    colors: ['#cd8d69', '#804233'],
    minutes: 70,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 · 1 口锅',
    ingredients: [
      { name: '猪肋排', amount: 700, unit: '克', role: 'core', substitutes: ['猪小排'] },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '八角', amount: 1, unit: '颗', role: 'seasoning', substitutes: ['桂皮 1 小段'] },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '冰糖', amount: 18, unit: '克', role: 'seasoning', substitutes: ['白砂糖'] },
      { name: '黄酒', amount: 1.5, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '排骨去沫', text: '排骨冷水下锅，加入两片姜和一半黄酒，煮开后撇净浮沫，再煮 3 分钟；捞出温水洗净并沥干。', heat: '大火', timerSeconds: 180 },
      { title: '煎香调色', text: '锅中放油，排骨中火煎至表面微黄，加入冰糖、剩余姜片、八角和葱结，翻炒至糖融化。', heat: '中火', timerSeconds: 480 },
      { title: '加汁焖烧', text: '加入生抽、老抽和剩余黄酒，倒入约 650 毫升热水；煮开后加盖小火焖 35 分钟。', heat: '小火', timerSeconds: 2100 },
      { title: '熟透收汁', text: '检查靠骨肉质已熟透且没有血色，拣去香料，转中火收汁至浓而不干，让排骨均匀裹汁。', heat: '中火', timerSeconds: 480 },
    ],
    tips: ['排骨厚度不同，焖制时间应以靠骨部位完全熟透为准。', '收汁后糖分浓度高，要用锅铲轻推并留少量汁，避免粘锅发苦。'],
  },
  {
    id: 'steamed-pork-rice-powder',
    title: '粉蒸肉',
    subtitle: '米粉软糯，五花肉咸香不腻',
    emoji: '🍚',
    colors: ['#d8b681', '#8c5a43'],
    minutes: 90,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '蒸锅 · 1 口锅',
    ingredients: [
      { name: '带皮五花肉', amount: 500, unit: '克', role: 'core', substitutes: ['猪梅花肉'] },
      { name: '土豆', amount: 350, unit: '克', role: 'core', substitutes: ['红薯', '南瓜'] },
      { name: '蒸肉米粉', amount: 120, unit: '克', role: 'core', substitutes: ['大米 100 克加糯米 20 克炒香打粗粉'] },
      { name: '姜末', amount: 1, unit: '茶匙', role: 'support' },
      { name: '葱花', amount: 1, unit: '汤匙', role: 'support' },
      { name: '腐乳汁', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['豆瓣酱 1 茶匙'] },
      { name: '生抽', amount: 1.5, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '白糖', amount: 0.5, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '切片腌肉', text: '五花肉切成约 5 毫米厚片，加入姜末、腐乳汁、生抽、黄酒、白糖和香油抓匀，冷藏腌 20 分钟。', heat: '不开火', timerSeconds: 1200 },
      { title: '裹上米粉', text: '土豆去皮切厚块铺在耐热碗底；肉片加入蒸肉米粉和约 4 汤匙清水拌匀，让每片肉都湿润裹粉。', heat: '不开火' },
      { title: '足汽蒸制', text: '肉片平码在土豆上，蒸锅水烧开后放入，盖严锅盖，中火持续蒸 55 分钟，期间留意锅内水量。', heat: '中火', timerSeconds: 3300 },
      { title: '检查熟度', text: '取一片最厚的肉检查，确认中心完全熟透、米粉无硬芯；未达到时继续蒸 10 分钟，出锅撒葱花。', heat: '中火', timerSeconds: 600 },
    ],
    tips: ['蒸制中途补水应使用热水，并避免水滴直接冲进碗里。', '不同蒸肉米粉含盐量不同，加入生抽和腐乳汁前可先查看配料说明并适量减盐。'],
  },
  {
    id: 'pork-belly-preserved-mustard',
    title: '梅菜扣肉',
    subtitle: '梅菜醇香，扣肉软润入味',
    emoji: '🥩',
    colors: ['#a77b5c', '#5e4437'],
    minutes: 140,
    difficulty: 3,
    servings: 5,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '汤锅 + 炒锅 + 蒸锅',
    ingredients: [
      { name: '带皮五花肉', amount: 700, unit: '克', role: 'core', substitutes: ['去皮五花肉'] },
      { name: '梅干菜', amount: 180, unit: '克', role: 'core', substitutes: ['芽菜'] },
      { name: '姜', amount: 5, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '白糖', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '食用油', amount: 1, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '煮肉洗菜', text: '五花肉冷水下锅，加姜、葱和黄酒，煮开后转中火 25 分钟至中心熟透；梅干菜反复淘洗去沙，挤干切碎。', heat: '中火', timerSeconds: 1500 },
      { title: '煎皮切片', text: '肉块擦干，肉皮抹少量老抽；锅中放油，肉皮朝下加盖小火煎至棕红，放凉后切约 7 毫米厚片。', heat: '小火', timerSeconds: 360, tip: '肉皮入锅可能溅油，必须擦干并先关小火、盖上锅盖操作。' },
      { title: '炒菜装碗', text: '梅干菜下锅炒干水汽，加入生抽、剩余老抽、白糖和约 100 毫升煮肉汤；肉片皮朝下排入碗中，上面铺梅干菜。', heat: '中火', timerSeconds: 480 },
      { title: '蒸软倒扣', text: '蒸锅水开后放入肉碗，中火蒸 60 分钟；确认肉片热透软烂，用盘盖住碗口，小心隔热倒扣并淋上碗中原汁。', heat: '中火', timerSeconds: 3600 },
    ],
    tips: ['梅干菜容易藏沙，要多换几次水淘洗，尝味后再决定是否补盐。', '倒扣时碗和汤汁都很烫，应戴隔热手套并让盘子完全盖住碗口。'],
  },
  {
    id: 'four-happiness-meatballs',
    title: '四喜丸子',
    subtitle: '大丸子软嫩多汁，酱汁咸鲜醇厚',
    emoji: '🍲',
    colors: ['#c58a64', '#764637'],
    minutes: 75,
    difficulty: 3,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '浓郁'],
    cookware: '炒锅 + 炖锅',
    ingredients: [
      { name: '猪肉末', amount: 600, unit: '克', role: 'core', substitutes: ['猪牛混合肉末'] },
      { name: '荸荠', amount: 100, unit: '克', role: 'core', substitutes: ['莲藕'] },
      { name: '上海青', amount: 6, unit: '棵', role: 'support', substitutes: ['小白菜'] },
      { name: '姜末', amount: 2, unit: '茶匙', role: 'support' },
      { name: '葱花', amount: 2, unit: '汤匙', role: 'support' },
      { name: '鸡蛋', amount: 1, unit: '个', role: 'seasoning' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '老抽', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '淀粉', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '白糖', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 300, unit: '毫升', role: 'seasoning' },
    ],
    steps: [
      { title: '调制肉馅', text: '荸荠去皮切碎，与肉末、姜末、葱花、鸡蛋、1 汤匙生抽、黄酒和 1 汤匙淀粉混合，顺一个方向搅至黏稠。', heat: '不开火' },
      { title: '团圆定形', text: '双手蘸少量清水，把肉馅均分成 4 个大丸子并来回摔打紧实；油温约六成热时逐个放入，炸至表面定形上色后捞出。', heat: '中火', timerSeconds: 480, tip: '下丸子时贴近油面轻放，避免高处投入造成热油飞溅。' },
      { title: '加汁焖透', text: '炖锅放入丸子，加剩余生抽、老抽、白糖和约 700 毫升热水；煮开后加盖小火焖 35 分钟，使丸子中心彻底熟透。', heat: '小火', timerSeconds: 2100 },
      { title: '配菜收汁', text: '上海青焯熟后围在盘边；取一只丸子从中心检查无粉红生肉，盛盘后将原汤用剩余淀粉调成薄芡并淋上。', heat: '中火', timerSeconds: 300 },
    ],
    tips: ['油炸只负责定形和上色，丸子中心仍可能未熟，必须完成焖煮并检查内部。', '肉丸较大，分量或尺寸改变时需相应调整焖煮时间。'],
  },
  {
    id: 'green-pepper-stuffed-pork',
    title: '青椒酿肉',
    subtitle: '青椒清香微辣，肉馅鲜嫩多汁',
    emoji: '🫑',
    colors: ['#86a95f', '#4d7548'],
    minutes: 40,
    difficulty: 2,
    servings: 3,
    vegetarian: false,
    tastes: ['咸鲜', '微辣'],
    cookware: '平底锅 · 1 口锅',
    ingredients: [
      { name: '青椒', amount: 6, unit: '个', role: 'core', substitutes: ['彩椒'] },
      { name: '猪肉末', amount: 350, unit: '克', role: 'core', substitutes: ['鸡肉末', '猪牛混合肉末'] },
      { name: '香菇', amount: 3, unit: '朵', role: 'support', substitutes: ['荸荠 60 克'] },
      { name: '姜末', amount: 1, unit: '茶匙', role: 'support' },
      { name: '葱花', amount: 1, unit: '汤匙', role: 'support' },
      { name: '生抽', amount: 2, unit: '汤匙', role: 'seasoning' },
      { name: '蚝油', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['生抽 1 汤匙加糖少许'] },
      { name: '淀粉', amount: 2, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '食用油', amount: 1.5, unit: '汤匙', role: 'seasoning' },
    ],
    steps: [
      { title: '调制肉馅', text: '香菇切碎，与肉末、姜末、葱花、1 汤匙生抽、1 茶匙淀粉、香油和 2 汤匙清水混合，顺一个方向搅至黏稠。', heat: '不开火' },
      { title: '处理填馅', text: '青椒洗净擦干，切成长段并去籽去白筋；把肉馅填入椒段，压紧后在肉馅露出面薄薄拍淀粉。', heat: '不开火' },
      { title: '两面煎香', text: '平底锅放油，先将露馅面朝下中火煎至定形，再翻动青椒煎出虎皮状斑点。', heat: '中火', timerSeconds: 480 },
      { title: '焖熟收汁', text: '加入蚝油、剩余生抽和约 180 毫升热水，加盖小火焖 10 分钟；切开最厚一只确认肉馅中心熟透，再开盖收汁。', heat: '小火', timerSeconds: 600 },
    ],
    tips: ['煎好的表面颜色不能代表肉馅中心已熟，必须完成加盖焖煮并检查。', '处理青椒后若皮肤有灼热感，应及时用流动水和清洁剂清洗双手，避免揉眼。'],
  },
  {
    id: 'winter-melon-meatball-soup',
    title: '冬瓜丸子汤',
    subtitle: '冬瓜清甜，手打丸子鲜嫩',
    emoji: '🥣',
    colors: ['#cddbb7', '#718b69'],
    minutes: 35,
    difficulty: 2,
    servings: 4,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '冬瓜', amount: 500, unit: '克', role: 'core', substitutes: ['丝瓜'] },
      { name: '猪肉末', amount: 350, unit: '克', role: 'core', substitutes: ['鸡肉末'] },
      { name: '姜', amount: 4, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '蛋清', amount: 1, unit: '个', role: 'seasoning', substitutes: ['清水 2 汤匙'] },
      { name: '淀粉', amount: 1, unit: '汤匙', role: 'seasoning' },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
      { name: '香油', amount: 1, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '搅打肉馅', text: '肉末加入蛋清、淀粉、半茶匙盐、白胡椒粉和 2 汤匙清水，顺一个方向搅至黏稠，再加入一半葱花拌匀。', heat: '不开火' },
      { title: '冬瓜煮汤', text: '冬瓜去皮去瓤后切约 1 厘米厚片；汤锅加入 1.2 升清水和姜片，煮开后放冬瓜，中火煮 5 分钟。', heat: '中火', timerSeconds: 300 },
      { title: '挤入丸子', text: '保持汤面微沸，用虎口挤出大小均匀的丸子，以蘸水小勺逐个送入锅中；全部下锅后轻轻推动防粘。', heat: '小火', timerSeconds: 300 },
      { title: '煮熟调味', text: '小火继续煮约 8 分钟，撇去浮沫；取最大丸子切开确认中心完全熟透，加入剩余盐和香油，撒葱花。', heat: '小火', timerSeconds: 480 },
    ],
    tips: ['丸子大小会影响成熟时间，最大的丸子中心无粉红色后再关火。', '挤丸子前后都要洗手，剩余生肉馅应及时冷藏，不宜放在室温下久置。'],
  },
  {
    id: 'lotus-root-pork-rib-soup',
    title: '莲藕排骨汤',
    subtitle: '莲藕粉糯，排骨汤清甜鲜香',
    emoji: '🥣',
    colors: ['#d2c4ad', '#8a7564'],
    minutes: 105,
    difficulty: 1,
    servings: 5,
    vegetarian: false,
    tastes: ['咸鲜', '清淡'],
    cookware: '汤锅 · 1 口锅',
    ingredients: [
      { name: '猪肋排', amount: 700, unit: '克', role: 'core', substitutes: ['猪脊骨'] },
      { name: '莲藕', amount: 700, unit: '克', role: 'core', substitutes: ['山药'] },
      { name: '姜', amount: 6, unit: '片', role: 'support' },
      { name: '小葱', amount: 2, unit: '根', role: 'support' },
      { name: '红枣', amount: 4, unit: '颗', role: 'support', substitutes: ['省略'] },
      { name: '黄酒', amount: 1, unit: '汤匙', role: 'seasoning', substitutes: ['料酒'] },
      { name: '盐', amount: 1, unit: '茶匙', role: 'seasoning' },
      { name: '白胡椒粉', amount: 0.25, unit: '茶匙', role: 'seasoning' },
    ],
    steps: [
      { title: '排骨焯洗', text: '排骨冷水下锅，放两片姜和黄酒；煮开后撇去浮沫，再煮 3 分钟，捞出用温水逐块洗净。', heat: '大火', timerSeconds: 180 },
      { title: '处理莲藕', text: '莲藕去皮，检查孔洞并冲净泥沙，切成约 3 厘米滚刀块；红枣洗净，小葱打结。', heat: '不开火' },
      { title: '小火煲汤', text: '汤锅放排骨、莲藕、剩余姜片、葱结和红枣，加入约 1.8 升热水；煮开后撇沫，加盖小火煮 75 分钟。', heat: '小火', timerSeconds: 4500 },
      { title: '熟透调味', text: '确认排骨靠骨部位完全熟透、莲藕达到喜欢的软度，拣去葱结，加入盐和白胡椒粉，再煮 5 分钟。', heat: '小火', timerSeconds: 300 },
    ],
    tips: ['莲藕孔洞容易藏泥，切开后要逐段检查并冲洗干净。', '焯排骨的汤水应弃用；正式煲汤时若需补水，应补热水以保持汤温。'],
  },
]
